--
--
/
DELETE VSDTXMAPEXT WHERE OBJNAME = '2292';
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//NORM/1.SETR//TRAD.STCO//PHYS','TXDATE','D','$05',null,'Ngày tạo yêu cầu',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//NORM/1.SETR//TRAD.STCO//PHYS','SYMBOL','C','$07','select symbol from sewithdrawdtl sew, sbsecurities sb where sew.codeid = sb.codeid and sew.txdatetxnum = ''<$FILTERID>''','Mã chứng khoán',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//NORM/1.SETR//TRAD.STCO//PHYS','SHAREHOLDERCODE','C','$02',null,'Tiểu khoản',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//NORM/1.SETR//TRAD.STCO//PHYS','QTTY','C','$10',null,'Khối lượng',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//NORM/1.SETR//TRAD.STCO//PHYS','NATIONAL','C','$02','SELECT AL.cdcontent FROM CFMAST CF, ALLCODE AL, afmast af  WHERE af.acctno=''<$FILTERID>'' and  cf.custid=af.custid  AND CF.COUNTRY=AL.CDVAL AND AL.CDNAME=''NATIONAL''','Mã quốc gia',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//NORM/1.SETR//TRAD.STCO//PHYS','DESC','C','$30',null,'Diễn giải',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//NORM/1.SETR//TRAD.STCO//PHYS','CUSTODYCD','C','$02','select UPPER(cf.custodycd) from cfmast cf, afmast af where  cf.custid=af.custid and af.acctno=''<$FILTERID>''','Tài khoản nhà đầu tư',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//NORM/2.SETR//TRAD.STCO//PHYS','TXDATE','D','$05',null,'Ngày tạo yêu cầu',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//NORM/2.SETR//TRAD.STCO//PHYS','SYMBOL','C','$07','select symbol from sewithdrawdtl sew, sbsecurities sb where sew.codeid = sb.codeid and sew.txdatetxnum = ''<$FILTERID>''','Mã chứng khoán',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//NORM/2.SETR//TRAD.STCO//PHYS','SHAREHOLDERCODE','C','$02',null,'Tiểu khoản',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//NORM/2.SETR//TRAD.STCO//PHYS','QTTY','C','$14',null,'Khối lượng',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//NORM/2.SETR//TRAD.STCO//PHYS','NATIONAL','C','$02','SELECT AL.cdcontent FROM CFMAST CF, ALLCODE AL, afmast af  WHERE af.acctno=''<$FILTERID>'' and  cf.custid=af.custid  AND CF.COUNTRY=AL.CDVAL AND AL.CDNAME=''NATIONAL''','Mã quốc gia',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//NORM/2.SETR//TRAD.STCO//PHYS','DESC','C','$30',null,'Diễn giải',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//NORM/2.SETR//TRAD.STCO//PHYS','CUSTODYCD','C','$02','select UPPER(cf.custodycd) from cfmast cf, afmast af where  cf.custid=af.custid and af.acctno=''<$FILTERID>''','Tài khoản nhà đầu tư',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//PEND/1.SETR//TRAD.STCO//PHYS','TXDATE','D','$05',null,'Ngày tạo yêu cầu',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//PEND/1.SETR//TRAD.STCO//PHYS','SYMBOL','C','$07','select symbol from sewithdrawdtl sew, sbsecurities sb where sew.codeid = sb.codeid and sew.txdatetxnum = ''<$FILTERID>''','Mã chứng khoán',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//PEND/1.SETR//TRAD.STCO//PHYS','SHAREHOLDERCODE','C','$02',null,'Tiểu khoản',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//PEND/1.SETR//TRAD.STCO//PHYS','QTTY','C','$10',null,'Khối lượng',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//PEND/1.SETR//TRAD.STCO//PHYS','NATIONAL','C','$02','SELECT AL.cdcontent FROM CFMAST CF, ALLCODE AL, afmast af  WHERE af.acctno=''<$FILTERID>'' and  cf.custid=af.custid  AND CF.COUNTRY=AL.CDVAL AND AL.CDNAME=''NATIONAL''','Mã quốc gia',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//PEND/1.SETR//TRAD.STCO//PHYS','DESC','C','$30',null,'Diễn giải',null);
INSERT INTO VSDTXMAPEXT (OBJTYPE,OBJNAME,TRFCODE,FLDNAME,FLDTYPE,AMTEXP,CMDSQL,CAPTION,ODRNUM)
VALUES ('T','2292','542.NEWM.CLAS//PEND/1.SETR//TRAD.STCO//PHYS','CUSTODYCD','C','$02','select UPPER(cf.custodycd) from cfmast cf, afmast af where  cf.custid=af.custid and af.acctno=''<$FILTERID>''','Tài khoản nhà đầu tư',null);
COMMIT;
/
