--
--
/
DELETE CMDMENU WHERE PRID = '200000';
INSERT INTO CMDMENU (CMDID,PRID,LEV,LAST,MENUTYPE,MENUCODE,MODCODE,OBJNAME,CMDNAME,EN_CMDNAME,AUTHCODE,TLTXCD)
VALUES ('230000','200000',2,'N','P',null,null,null,'Kiểm soát nguồn','Pool/Room management','YYYYYYYYYYN',null);
INSERT INTO CMDMENU (CMDID,PRID,LEV,LAST,MENUTYPE,MENUCODE,MODCODE,OBJNAME,CMDNAME,EN_CMDNAME,AUTHCODE,TLTXCD)
VALUES ('220000','200000',2,'N','P',null,null,null,'Thực hiện quyền','Coporate actions','YYYYYYYYYYN',null);
INSERT INTO CMDMENU (CMDID,PRID,LEV,LAST,MENUTYPE,MENUCODE,MODCODE,OBJNAME,CMDNAME,EN_CMDNAME,AUTHCODE,TLTXCD)
VALUES ('210000','200000',2,'N','P',null,null,null,'Kế toán sổ cái','General ledger','YYYYYYYYYYN',null);
COMMIT;
/
