--
--
/
DELETE CMDMENU WHERE PRID = '111700';
INSERT INTO CMDMENU (CMDID,PRID,LEV,LAST,MENUTYPE,MENUCODE,MODCODE,OBJNAME,CMDNAME,EN_CMDNAME,AUTHCODE,TLTXCD)
VALUES ('111708','111700',3,'Y','O','MR0008','MR','NOTBLACKLISTSYMBOL','Tra cứu DS mã CK không thuộc danh mục Blacklist của hệ thống','Tra cứu DS mã CK không thuộc danh mục Blacklist của hệ thống','YYYYYYYNNYY',null);
INSERT INTO CMDMENU (CMDID,PRID,LEV,LAST,MENUTYPE,MENUCODE,MODCODE,OBJNAME,CMDNAME,EN_CMDNAME,AUTHCODE,TLTXCD)
VALUES ('111707','111700',3,'Y','O','MR0007','MR','BLACKLISTSYMBOL','Danh sách mua Blacklist có cấp bảo lãnh','Danh sách mua Blacklist có cấp bảo lãnh','YYYYYYYNNYY',null);
INSERT INTO CMDMENU (CMDID,PRID,LEV,LAST,MENUTYPE,MENUCODE,MODCODE,OBJNAME,CMDNAME,EN_CMDNAME,AUTHCODE,TLTXCD)
VALUES ('111706','111700',3,'Y','A','MR0006','MR','MRSELLESTM','Dự tính bán chứng khoán để rút tiền','Sell estimate to cash withdraw','YYYYYYYYYYN',null);
INSERT INTO CMDMENU (CMDID,PRID,LEV,LAST,MENUTYPE,MENUCODE,MODCODE,OBJNAME,CMDNAME,EN_CMDNAME,AUTHCODE,TLTXCD)
VALUES ('111705','111700',3,'Y','A','MR0015','MR','MRRPT3009','Lưu dữ liệu báo cáo MR3009','Log data for MR3009','YYYYYYYYYYN',null);
INSERT INTO CMDMENU (CMDID,PRID,LEV,LAST,MENUTYPE,MENUCODE,MODCODE,OBJNAME,CMDNAME,EN_CMDNAME,AUTHCODE,TLTXCD)
VALUES ('111704','111700',3,'Y','O','MR0012','SA','CRBTRFLOGMR','Quản lý bảng kê GD ký quỹ','Bank voucher management','YYYYYYYYYYN',null);
INSERT INTO CMDMENU (CMDID,PRID,LEV,LAST,MENUTYPE,MENUCODE,MODCODE,OBJNAME,CMDNAME,EN_CMDNAME,AUTHCODE,TLTXCD)
VALUES ('111703','111700',3,'Y','A','MR0004','MR','MRGENERALVIEW','Tra cứu tổng hợp','General view','YYYYYYYYYYN',null);
INSERT INTO CMDMENU (CMDID,PRID,LEV,LAST,MENUTYPE,MENUCODE,MODCODE,OBJNAME,CMDNAME,EN_CMDNAME,AUTHCODE,TLTXCD)
VALUES ('111702','111700',3,'Y','R','MR0003  ','MR','RPTMASTER','Báo cáo','Reporting','YYYYYYYYYYN',null);
INSERT INTO CMDMENU (CMDID,PRID,LEV,LAST,MENUTYPE,MENUCODE,MODCODE,OBJNAME,CMDNAME,EN_CMDNAME,AUTHCODE,TLTXCD)
VALUES ('111701','111700',3,'N','T','MR0002  ','MR',null,'Giao dịch','Transaction','YYYYYYYYYYN',null);
COMMIT;
/
