--
--
/
DELETE CMDMENU WHERE PRID = '000000';
INSERT INTO CMDMENU (CMDID,PRID,LEV,LAST,MENUTYPE,MENUCODE,MODCODE,OBJNAME,CMDNAME,EN_CMDNAME,AUTHCODE,TLTXCD)
VALUES ('030000','000000',2,'N','P',null,null,null,'Tham số nghiệp vụ','Business parameters','YYYYYYYYYYN',null);
INSERT INTO CMDMENU (CMDID,PRID,LEV,LAST,MENUTYPE,MENUCODE,MODCODE,OBJNAME,CMDNAME,EN_CMDNAME,AUTHCODE,TLTXCD)
VALUES ('020000','000000',2,'N','P',null,null,null,'Tham số hệ thống','System parameters','YYYYYYYYYYN',null);
INSERT INTO CMDMENU (CMDID,PRID,LEV,LAST,MENUTYPE,MENUCODE,MODCODE,OBJNAME,CMDNAME,EN_CMDNAME,AUTHCODE,TLTXCD)
VALUES ('010000','000000',2,'N','P',null,null,null,'Quản trị hệ thống','System administration','YYYYYYYYYYN',null);
COMMIT;
/
