--
--
/
DELETE SYSVAR WHERE VARNAME = 'MSBSREP02';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('REPRESENT','MSBSREP02','Trần Quý Hải','Giám đốc khối vận hành',null,'N');
COMMIT;
/
