--
--
/
DELETE SYSVAR WHERE VARNAME = 'RUNSTATUS';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('BANKGW','RUNSTATUS','N','0001','Co dang goi ham chay khong - va ai chay','N');
COMMIT;
/
