--
--
/
DELETE SYSVAR WHERE VARNAME = 'MAXDEBTCF';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('MARGIN','MAXDEBTCF','18000000000','Hạn mức nợ tối đa của một khách hàng','Max debt for one customer','Y');
COMMIT;
/
