--
--
/
DELETE SYSVAR WHERE VARNAME = 'HOSEBREAKSIZE';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','HOSEBREAKSIZE','19000','Hose breaking size','Hose breaking size','N');
COMMIT;
/
