--
--
/
DELETE SYSVAR WHERE VARNAME = 'MAXTRADEFEE';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('DEFINED','MAXTRADEFEE','0.5','Max trading fee','Phi giao dich toi da','N');
COMMIT;
/
