--
--
/
DELETE SYSVAR WHERE VARNAME = 'NORMALLASS';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','NORMALLASS','000,001,002','Normal class',null,'N');
COMMIT;
/
