--
--
/
DELETE SYSVAR WHERE VARNAME = 'MESSDF1005TITLE';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','MESSDF1005TITLE','MESSDF1005TITLE','Thông báo khoản vay quá hạn !','Thông báo khoản vay quá hạn !','N');
COMMIT;
/
