--
--
/
DELETE SYSVAR WHERE VARNAME = 'MAXSPLITORDER';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('OD','MAXSPLITORDER','100','SL lenh chia toi da','SL lenh chia toi da','Y');
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('OD','MAXSPLITORDER','100','SL lenh chia toi da','SL lenh chia toi da','Y');
COMMIT;
/
