--
--
/
DELETE ALLCODE WHERE CDNAME = 'FLDTYPE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','FLDTYPE','N','Số',2,'Y','Số');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','FLDTYPE','C','Ký tự',1,'Y','Ký tự');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','FLDTYPE','D','Ngày',0,'Y','Ngày');
COMMIT;
/
