--
--
/
DELETE ALLCODE WHERE CDNAME = 'PURPOSE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','PURPOSE','002','Phân phối',2,'Y','Phân phối');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','PURPOSE','001','Sản xuất',1,'Y','Sản xuất');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','PURPOSE','000',' ---',0,'Y',' ---');
COMMIT;
/
