--
--
/
DELETE ALLCODE WHERE CDNAME = 'BANKCODE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('CF','BANKCODE','004','VIB bank',4,'Y','VIB bank');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('CF','BANKCODE','003','Incombank',3,'Y','Incombank');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('CF','BANKCODE','002','BIDV',2,'Y','BIDV');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('CF','BANKCODE','001','Vietcombank',1,'Y','Vietcombank');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('CF','BANKCODE','000','----------',0,'Y','----------');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','052','Ng⮠h஧ techcombank Nam Dinh (017)',64,'Y','Ng⮠h஧ techcombank Nam Dinh (017)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','119','Ngan Hang An Binh(004)',63,'Y','Ngan Hang An Binh(004)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','046','Ngan Hang OCEAN(041) ',62,'Y','Ngan Hang OCEAN(041) ');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','045','Ngan Hang Lien Viet(476)',61,'Y','Ngan Hang Lien Viet(476)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','051','Ng⮠h஧ OCEAN (030)',60,'Y','Ng⮠h஧ OCEAN (030)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','049','Ngan hang Phat trien nha Dong Bang S�ng cuu Long MHB(049)',59,'Y','Ngan hang Phat trien nha Dong Bang S�ng cuu Long MHB(049)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','044','Ngan Hang MB(006)',58,'Y','Ngan Hang MB(006)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','043','GP Bank(281)',57,'Y','GP Bank(281)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','118','NH An Binh (008)',56,'Y','NH An Binh (008)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','042','NH Lien viet chi nhanh Dong Do (027)',55,'Y','NH Lien viet chi nhanh Dong Do (027)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','041','NH Bao Viet',54,'Y','NH Bao Viet');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','039','Ngan hang VIB (686)',53,'Y','Ngan hang VIB (686)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','038','NH Viet Thai (082)',52,'Y','NH Viet Thai (082)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','037','NH MSB - CN Thanh Xuan(738)',51,'Y','NH MSB - CN Thanh Xuan(738)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','117','NH Lien Viet - CN HCM',50,'Y','NH Lien Viet - CN HCM');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','036','Ngân hàng VCB HO 2(028)',49,'Y','Ngân hàng VCB HO 2(028)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','116','Vietcombank Nha Trang',48,'Y','Vietcombank Nha Trang');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','035','Ngân hàng BIDV Quang Trung (140)',47,'Y','Ngân hàng BIDV Quang Trung (140)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','034','Ngân hàng Liên Việt - CN Hà nội (024)',46,'Y','Ngân hàng Liên Việt - CN Hà nội (024)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','033','Ngân hàng MSB -CN Thanh xuân (119)',45,'Y','Ngân hàng MSB -CN Thanh xuân (119)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','032','Ngân hàng VIB - HO (544)',44,'Y','Ngân hàng VIB - HO (544)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','031','Ngân hàng tiền Phong (001)',43,'Y','Ngân hàng tiền Phong (001)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','115','VCB Can Tho',42,'Y','VCB Can Tho');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','114','VCB Vung Tau',41,'Y','VCB Vung Tau');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','029','Ngân hàng PG (TK 543)',40,'Y','Ngân hàng PG (TK 543)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','028','Ngân hàng VCB Hải phòng(798)',39,'Y','Ngân hàng VCB Hải phòng(798)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','027','Ngân hàng Techcombank ĐN()',38,'Y','Ngân hàng Techcombank ĐN()');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','026','Ngân hàng PG (627)',37,'Y','Ngân hàng PG (627)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','025','Ngân hàng IVB tự doanh  (021)',36,'Y','Ngân hàng IVB tự doanh  (021)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','024','Ngân hàng BIDV CN Nam định()',35,'Y','Ngân hàng BIDV CN Nam định()');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','023','Ngân hàng GP bank – Phòng GD Kim Mã(416)',34,'Y','Ngân hàng GP bank – Phòng GD Kim Mã(416)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','022','Ngân hàng Techcombank HO',33,'Y','Ngân hàng Techcombank HO');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','021','Ngân hàng SHB (688)',32,'Y','Ngân hàng SHB (688)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','019','Ngân hàng Chinfonbank - CN Hà nội (841)',31,'Y','Ngân hàng Chinfonbank - CN Hà nội (841)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','018','Ngân hàng Habubank hội sở(470)',30,'Y','Ngân hàng Habubank hội sở(470)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','017','NH TeckComBank so GD NHNN',29,'Y','NH TeckComBank so GD NHNN');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','016','Ngân hàng Techcombank Vĩnh Yên(120)',28,'Y','Ngân hàng Techcombank Vĩnh Yên(120)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','113','NH Viet A - CN Tan Binh',27,'Y','NH Viet A - CN Tan Binh');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','015','Ngân hàng Ocean()',26,'Y','Ngân hàng Ocean()');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','112','NH GP Bank(TK 4166)',25,'Y','NH GP Bank(TK 4166)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','111','NH GP Bank(TK 4174)',24,'Y','NH GP Bank(TK 4174)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','190','NH Quan Doi - CN Ton Duc Thang (TK 3003)',23,'Y','NH Quan Doi - CN Ton Duc Thang (TK 3003)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','180','NH Quan Doi - CN Ton Duc Thang (TK 2007)',22,'Y','NH Quan Doi - CN Ton Duc Thang (TK 2007)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','014','Ngân hàng VCB NN( (349)',21,'Y','Ngân hàng VCB NN( (349)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','013','Ngân hàng MB (301)',20,'Y','Ngân hàng MB (301)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','012','Ngân hàng BIDV Quang trung (978)',19,'Y','Ngân hàng BIDV Quang trung (978)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','170','Ngân hàng Sacombank - TK 047',18,'Y','Ngân hàng Sacombank - TK 047');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','160','Ngân hàng Sacombank - TK 050',17,'Y','Ngân hàng Sacombank - TK 050');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','150','Ngân hàng Vietcombank  HCM - TK 6720',16,'Y','Ngân hàng Vietcombank  HCM - TK 6720');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','140','Ngân hàng Vietcombank  HCM - TK 6674',15,'Y','Ngân hàng Vietcombank  HCM - TK 6674');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','130','Ngân hàng NH BIDV Nam kì khởi nghĩa',14,'Y','Ngân hàng NH BIDV Nam kì khởi nghĩa');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','120','Ngân hàng Nông nghiệp HCM - TK 11777 20',13,'Y','Ngân hàng Nông nghiệp HCM - TK 11777 20');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','110','Ngân hàng Nông nghiệp  HCM - TK 11777 36',12,'Y','Ngân hàng Nông nghiệp  HCM - TK 11777 36');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','011','Ngân hàng BIDV Quang trung (969)',11,'Y','Ngân hàng BIDV Quang trung (969)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','090','Ngân hàng VCB SGD( 858)',10,'Y','Ngân hàng VCB SGD( 858)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','080','Ngân hàng IVB (001)',7,'Y','Ngân hàng IVB (001)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','060','Ngân hàng Phương Đông (đóng TK)',5,'Y','Ngân hàng Phương Đông (đóng TK)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','050','Ngân hàng VIB HO ( 384)',4,'Y','Ngân hàng VIB HO ( 384)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','040','Ngân hàng BIDV Hà Thành (538)',3,'Y','Ngân hàng BIDV Hà Thành (538)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','030','Ngân hàng MB (300)',2,'Y','Ngân hàng MB (300)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','020','Ngân hàng VCB HO (1361)',1,'Y','Ngân hàng VCB HO (1361)');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','BANKCODE','010','Ngân hàng VCB HN( )',0,'Y','Ngân hàng VCB HN( )');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('RM','BANKCODE','STB','Ngân hàng Sacombank',4,'Y','Ngân hàng Sacombank');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('RM','BANKCODE','STB','Ngân hàng Sacombank',4,'Y','Sacombank');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('RM','BANKCODE','DAB','Ngân hàng Ðông Á',3,'Y','Ngân hàng Ðông Á');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('RM','BANKCODE','BVB','Ngân hàng Bảo Việt',2,'Y','Ngân hàng B?o Vi?t');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('RM','BANKCODE','BIDV','Ngân hàng BIDV',1,'Y','Ngân hàng BIDV');
COMMIT;
/
