--
--
/
DELETE ALLCODE WHERE CDNAME = 'INTFRQCD';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('FN','INTFRQCD','L','Cuối kỳ',8,'Y','Lumpsum');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('FN','INTFRQCD','Y','Năm',7,'Y','Yearly');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('FN','INTFRQCD','H','Nửa năm',6,'Y','Haft yearly');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('FN','INTFRQCD','Q','Hàng quý',5,'Y','Quarterly');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('FN','INTFRQCD','M','Hàng tháng',4,'Y','Monthly');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','INTFRQCD','M','Ngày cố định hàng tháng',4,'N','Ngày cố định hàng tháng');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','INTFRQCD','L','Cùng kỳ hạn với gốc',0,'Y','Cùng kỳ hạn với gốc');
COMMIT;
/
