--
--
/
DELETE ALLCODE WHERE CDNAME = 'MOBILE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','MOBILE','0918868999','Email nhan thong bao',5,'Y','Email nhan thong bao');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','MOBILE','0968449217','Email nhan thong bao',4,'Y','Email nhan thong bao');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','MOBILE','0946186186','Email nhan thong bao',4,'Y','Email nhan thong bao');
COMMIT;
/
