--
--
/
DELETE ALLCODE WHERE CDNAME = 'SECTYPE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','012','Trái phiếu doanh nghiệp ',11,'Y','Trai phieu doanh nghiep');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','222','Trái phiếu và trái phiếu chuyển đổi',10,'Y','Bond and Convertible bonds');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','011','Chứng quyền',10,'Y','Covered Warrant');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','444','Trái phiếu và chứng chỉ quỹ',10,'Y','Bond and Fund certificates');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','333','Cổ phiếu và trái phiếu',9,'Y','Share and Bond');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','111','Cổ phiếu và Chứng chỉ quỹ',9,'Y','Share and Fund certificates');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','009','Giấy chứng nhận TG',8,'Y','Certificate TG');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','008','Chứng chỉ quỹ',7,'Y','Fund certificates');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','007','Chứng chỉ ủy thác',6,'Y','Trust Certification');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','006','Trái phiếu',5,'Y','Bond');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','005','Tương lai',4,'Y','Future');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','004','Quyền chọn',3,'Y','Option');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','003','Trái phiếu chuyển đổi',2,'Y','Convertible bond');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','002','Cổ phiếu ưu đãi',1,'Y','Preference shares');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','001','Cổ phiếu thường',0,'Y','Common share');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','SECTYPE','000','Tất cả',-1,'Y','All');
COMMIT;
/
