--
--
/
DELETE ALLCODE WHERE CDNAME = 'USERTYPE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','USERTYPE','Flex','User FlexCustodian',1,'Y','MaskedEditBox');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','USERTYPE','BD','Broker Desk',0,'Y','TextBox');
COMMIT;
/
