--
--
/
DELETE ALLCODE WHERE CDNAME = 'DELTD';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('FO','DELTD','Y','Có',1,'Y','Có');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('FO','DELTD','N','Không',0,'Y','Không');
COMMIT;
/
