--
--
/
DELETE ALLCODE WHERE CDNAME = 'OTFUNC';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','BENEFICIARYREGISTER','Đăng ký người thụ hưởng',16,'Y','Beneficiary register');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','UPDTRANACT','Giao dịch khác',16,'Y','TRANSACTION OTHERS');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','STOCKTRANSFER','Chuyển khoản chứng khoán',15,'Y','Stock transfer');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','ALLOWPROVIONLINE','Giới thiệu khách hàng online',15,'Y','Provi Online');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','ODDORDER','Giao dịch lô lẻ',14,'Y','Tradelot retail');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','ADMINMESSAGES','Tao thông điệp cty chứng khoán',13,'Y','Create messages');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','TERMDEPOSIT','Gửi tiết kiệm',12,'Y','Term deposit');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','BONDSTOSHARES','Chuyển đổi trái phiếu',11,'Y','Bonds to shares');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','COMPANYALERT','Cảnh báo công ty',10,'Y','Smart alert');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','MARKETALERT','Cảnh báo thị trường',9,'Y','Market alert');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','SMARTALERT','Cảnh báo thông minh',8,'Y','Smart alert');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','DEPOSIT','Tra cứu giao dịch',7,'Y','Transactions inquiry');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','GROUP_ORDER','Đặt lệnh nhóm',6,'Y','Group order');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','COND_ORDER','Đặt, sửa, hủy lệnh điều kiện',5,'Y','Conditional order');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','ORDINPUT','Đặt, sửa, hủy lệnh thông thường',4,'Y','Place order');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','ISSUEINPUT','Đăng ký quyền mua',2,'Y','Stock right off register');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','ADWINPUT','Ứng trước tiền bán',1,'Y','Advance payment');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','CASHTRANS_INTERNAL','Chuyển tiền nội bộ',0,'Y','Cash transfer internal');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','OTFUNC','CASHTRANS','Chuyển tiền ra ngoài',-1,'Y','Cash transfer');
COMMIT;
/
