--
--
/
DELETE ALLCODE WHERE CDNAME = 'EXCHANGECD';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','EXCHANGECD','CSX','Campuchia',7,'Y','Cambodia Stock Exchange');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','EXCHANGECD','LSX','Lao',6,'Y','Lao Stock Exchange');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','EXCHANGECD','BON','HNX Bond',5,'Y','HNX Bond');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','EXCHANGECD','UPC','HNX UpCom',4,'Y','HNX UpCom');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','EXCHANGECD','HNX','SGDCK HN',3,'Y','Listed HN');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','EXCHANGECD','HSX','SGDCK HCM',2,'Y','Listed HCM');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','EXCHANGECD','OTC','OTC',1,'Y','OTC');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','EXCHANGECD','ALL','Tất cả',0,'Y','All');
COMMIT;
/
