--
--
/
DELETE ALLCODE WHERE CDNAME = 'RISKTYPE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','RISKTYPE','004','Đầu tư',3,'Y','Đầu tư');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','RISKTYPE','003','Phát triển',2,'Y','Phát triển');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','RISKTYPE','002','Không thay đổi',1,'Y','Không thay đổi');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','RISKTYPE','001','Thu nhập thường xuyên',0,'Y','Thu nhập thường xuyên');
COMMIT;
/
