--
--
/
DELETE ALLCODE WHERE CDNAME = 'RATEDATE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','RATEDATE','D','Ngày giải ngân',1,'Y','Ngày giải ngân');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','RATEDATE','O','Ngày mở',0,'Y','Ngày mở');
COMMIT;
/
