--
--
/
DELETE ALLCODE WHERE CDNAME = 'AREA';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','AREA','S','Phòng GD',2,'Y','Phòng GD');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','AREA','B','Chi nhánh',1,'Y','Chi nhánh');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','AREA','A','Hội sở',0,'Y','Hội sở');
COMMIT;
/
