--
--
/
DELETE ALLCODE WHERE CDNAME = 'OTAUTHTYPE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('CF','OTAUTHTYPE','4','Xác thực Chứng thư số',2,'Y','Authorized by ');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('CF','OTAUTHTYPE','1','Xác thực OTP',1,'Y','Authorized by OTP');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('CF','OTAUTHTYPE','0','Xác thực PIN',0,'Y','Authorized by ');
COMMIT;
/
