--
--
/
DELETE allcode WHERE CDTYPE = 'OD' AND CDNAME = 'BLSTATUS';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','BLSTATUS','ALL','All',-1,'Y','All');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','BLSTATUS','PCF','Chờ xác nhận',1,'Y','Pending for confirm');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','BLSTATUS','PD','Chờ xử lý',2,'Y','Pending for process');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','BLSTATUS','RJ','Từ chối',3,'Y','Reject');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','BLSTATUS','ST','Đã gửi',4,'Y','Sent');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','BLSTATUS','PF','Khớp một phần',5,'Y','Partical Fill');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','BLSTATUS','AF','Khớp hết',6,'Y','Filled');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','BLSTATUS','PA','Đang sửa',7,'Y','Pending Replace');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','BLSTATUS','PC','Đang hủy',8,'Y','Pending Cancel');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','BLSTATUS','CC','Đã hủy',5,'Y','Đã hủy');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','BLSTATUS','EE','Hết hiệu lực',9,'Y','Hết hiệu lực');
COMMIT;
/
