--
--
/
DELETE ALLCODE WHERE CDNAME = 'CORSTATUS';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','CORSTATUS','A','Chờ kích hoạt',1,'Y','Not active yet');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','CORSTATUS','N','Chờ ngày hiệu lực',1,'Y','Not effect yet');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','CORSTATUS','F','Đã kích hoạt',1,'Y','Activated');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','CORSTATUS','P','Chưa kích hoạt',1,'Y','Pending');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','CORSTATUS','12','Hoàn tất',1,'Y','Completed');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','CORSTATUS','I','Đang kích hoạt',1,'Y','Active');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','CORSTATUS','4','Đã khớp',1,'Y','Matched');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','CORSTATUS','5','Hết hiệu lực',1,'Y','Expired');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','CORSTATUS','C','Đang hủy',1,'Y','Waiting canceled');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','CORSTATUS','3','Đã hủy',0,'Y','Canceled');
COMMIT;
/
