--
--
/
DELETE ALLCODE WHERE CDNAME = 'LISTINGSTATUS';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','LISTINGSTATUS','W','Cảnh báo',6,'Y','Warning');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','LISTINGSTATUS','H','Tạm dừng giao dịch',5,'Y','Halt');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','LISTINGSTATUS','D','Tăng vốn',4,'Y','Capital increase');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','LISTINGSTATUS','I','Giảm vốn',3,'Y','Capital decrease');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','LISTINGSTATUS','U','Hủy niêm yết',2,'Y','Unlisted');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','LISTINGSTATUS','L','Niêm yết mới',1,'Y','New listing');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','LISTINGSTATUS','N','Binh thường',0,'Y','Normal');
COMMIT;
/
