--
--
/
DELETE ALLCODE WHERE CDNAME = 'MARKETTYPE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','MARKETTYPE','001','TT Trái phiếu chuyên biệt',1,'Y','TT Trái phiếu chuyên biệt');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','MARKETTYPE','000','Khác',0,'Y','Khác');
COMMIT;
/
