--
--
/
DELETE ALLCODE WHERE CDNAME = 'UPDATELIMITMAX';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','UPDATELIMITMAX','Y','Có',2,'Y','Yes');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','UPDATELIMITMAX','C',null,1,'Y',null);
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','UPDATELIMITMAX','N','Không',0,'Y','No');
COMMIT;
/
