--
--
/
DELETE ALLCODE WHERE CDNAME = 'GWSTATUS';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('0','GWSTATUS','N','Bình thường',0,'Y','Bình thường');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('1','GWSTATUS','B','Phong tỏa',1,'Y','Phong tỏa');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('2','GWSTATUS','S','Đã gửi',2,'Y','Đã gửi');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','GWSTATUS','E','Lỗi',2,'Y','Lỗi');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','GWSTATUS','A','Hoạt động',1,'Y','Hoạt động');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','GWSTATUS','P','Chờ duyệt',0,'Y','Chờ duyệt');
COMMIT;
/
