--
--
/
DELETE ALLCODE WHERE CDNAME = 'REFERENCESTATUS';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','REFERENCESTATUS','006','Gộp',5,'Y','Gộp');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','REFERENCESTATUS','005','Chia',4,'Y','Chia');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','REFERENCESTATUS','004','Loại cổ tức',3,'Y','Loại cổ tức');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','REFERENCESTATUS','003','Thực hiện quyền',2,'Y','Thực hiện quyền');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','REFERENCESTATUS','002','Cổ tức',1,'Y','Cổ tức');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','REFERENCESTATUS','001','Thường',0,'Y','Thường');
COMMIT;
/
