--
--
/
DELETE ALLCODE WHERE CDNAME = 'TYPEBA';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','TYPEBA','002','Nội bảng',1,'Y','Nội bảng');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('GL','TYPEBA','001','Ngoại bảng',0,'Y','Ngoại bảng');
COMMIT;
/
