--
--
/
DELETE APPRVRQD WHERE OBJNAME = 'AFBLACKLISTSYMBOL';
INSERT INTO APPRVRQD (OBJNAME,RQDSTRING,MAKERID,MAKERDT,APPRVID,APPRVDT,MODNUM)
VALUES ('AFBLACKLISTSYMBOL','ALL',null,null,null,null,'1');
COMMIT;
/
