--
--
/
DELETE FILEMAP WHERE FILECODE = 'I070';
INSERT INTO FILEMAP (FILECODE,FILEROWNAME,TBLROWNAME,TBLROWTYPE,ACCTNOFLD,TBLROWMAXLENGTH,CHANGETYPE,DELTD,DISABLED,VISIBLE,LSTODR,FIELDDESC,SUMAMT)
VALUES ('I070','SYMBOL','SYMBOL','C','N',18,'U','N','Y','Y','3',null,'N');
COMMIT;
/
