CREATE OR REPLACE PROCEDURE df0023 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   F_DATE         IN       VARCHAR2,
   T_DATE         IN       VARCHAR2,
   CUSTODYCD      IN       VARCHAR2,
   CIACCTNO       IN       VARCHAR2,
   BRGID          IN       VARCHAR2
   )
IS
--
-- PURPOSE: BRIEFLY EXPLAIN THE FUNCTIONALITY OF THE PROCEDURE
-- BAO CAO TAI KHOAN TIEN TONG HOP CUA NGUOI DAU TU
-- MODIFICATION HISTORY
-- PERSON      DATE    COMMENTS
-- HUYNQ
-- ---------   ------  -------------------------------------------

   V_STROPTION      VARCHAR2 (5);            -- A: ALL; B: BRANCH; S: SUB-BRANCH
   V_STRBRID          VARCHAR2 (4);            -- USED WHEN V_NUMOPTION > 0

  V_STRCUSTODYCD VARCHAR2 (20);
   V_STRCIACCTNO  VARCHAR2 (20);
   V_STRBRGID  VARCHAR2 (10);


   V_FROMDATE     DATE;
   V_TODATE       DATE;

BEGIN
   V_STROPTION := OPT;

   IF V_STROPTION = 'A' THEN     -- TOAN HE THONG
      V_STRBRID := '%';
   ELSIF V_STROPTION = 'B' THEN
      V_STRBRID := SUBSTR(BRID,1,2) || '__' ;
   ELSE
      V_STRBRID := BRID;
   END IF;

   IF(CUSTODYCD <> 'ALL') THEN
     V_STRCUSTODYCD := CUSTODYCD;
   ELSE
     V_STRCUSTODYCD := '%';
   END IF;

   IF(CIACCTNO <> 'ALL') THEN
     V_STRCIACCTNO := CIACCTNO;
   ELSE
     V_STRCIACCTNO := '%';
   END IF;

   IF(BRGID <> 'ALL') THEN
     V_STRBRGID := BRGID;
   ELSE
     V_STRBRGID := '%';
   END IF;


   V_FROMDATE  :=  TO_DATE(F_DATE,'DD/MM/YYYY');
   V_TODATE    :=  TO_DATE(T_DATE,'DD/MM/YYYY');

OPEN PV_REFCURSOR
FOR
  SELECT CF.CUSTODYCD, CI.ACCTNO, CF.FULLNAME, NVL(GD.PHATSINHNO,0)PHATSINHNO, NVL(GD.PHATSINHCO,0) PHATSINHCO,
    (DFDEBTAMT-NVL(PS.PHATSINH,0)) CUOIKY,
    BR.BRNAME, TLPR.TLNAME
FROM CIMAST CI, CFMAST CF, TLPROFILES TLPR, BRGRP BR,
    (--GIAO DICH PHAT SINH TU CUOI KY DEN HIEN TAI
        SELECT CITR.ACCTNO, SUM(CASE WHEN APP.TXTYPE = 'C' THEN CITR.NAMT ELSE -CITR.NAMT END) PHATSINH
        FROM VW_CITRAN_ALL CITR, APPTX APP
        WHERE CITR.TXCD = APP.TXCD
            AND APP.TXTYPE IN ('C','D')
            AND APP.FIELD LIKE 'DFDEBTAMT'
            AND APP.APPTYPE = 'CI'
            AND CITR.NAMT <> 0
            AND CITR.TXDATE > V_TODATE
        GROUP BY CITR.ACCTNO
    )PS,
    (--GIAO DICH PHAT SINH TRONG KY
        SELECT CITR.ACCTNO, SUM(CASE WHEN APP.TXTYPE = 'C' THEN CITR.NAMT ELSE 0 END) PHATSINHNO,
            SUM(CASE WHEN APP.TXTYPE = 'D' THEN CITR.NAMT ELSE 0 END) PHATSINHCO
        FROM VW_CITRAN_ALL CITR, APPTX APP
        WHERE CITR.TXCD = APP.TXCD
            AND APP.TXTYPE IN ('C','D')
            AND APP.FIELD LIKE 'DFDEBTAMT'
            AND APP.APPTYPE = 'CI'
            AND CITR.TXDATE BETWEEN V_FROMDATE AND V_TODATE
            AND CITR.NAMT <> 0
        GROUP BY CITR.ACCTNO
    )GD
WHERE CI.ACCTNO = PS.ACCTNO(+)
    AND CI.ACCTNO = GD.ACCTNO(+)
    AND (
            NVL(GD.PHATSINHNO,0) <> 0
            OR
            NVL(GD.PHATSINHCO,0) <> 0
            OR
            (DFDEBTAMT-NVL(PS.PHATSINH,0)) <> 0
        )
    AND CI.CUSTID = CF.CUSTID
    AND CF.CAREBY = TLPR.TLID
    AND TLPR.BRID = BR.BRID
ORDER BY CF.CUSTODYCD, CI.ACCTNO, CF.FULLNAME
;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN;
END;                                                              -- PROCEDURE
/

