CREATE OR REPLACE PROCEDURE df0024 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   I_DATE         IN       VARCHAR2,
   BRGID          IN       VARCHAR2
   )
IS
--
-- PURPOSE: BRIEFLY EXPLAIN THE FUNCTIONALITY OF THE PROCEDURE
--
-- MODIFICATION HISTORY
-- PERSON      DATE    COMMENTS
-- DUNGNH
-- ---------   ------  -------------------------------------------

   V_STROPTION      VARCHAR2 (5);            -- A: ALL; B: BRANCH; S: SUB-BRANCH
   V_STRBRID        VARCHAR2 (4);            -- USED WHEN V_NUMOPTION > 0

  V_STRCUSTODYCD VARCHAR2 (20);
   V_STRCIACCTNO  VARCHAR2 (20);
   V_STRBRGID  VARCHAR2 (10);


   V_INDATE     DATE;

BEGIN
   V_STROPTION := OPT;

   IF V_STROPTION = 'A' THEN     -- TOAN HE THONG
      V_STRBRID := '%';
   ELSIF V_STROPTION = 'B' THEN
      V_STRBRID := SUBSTR(BRID,1,2) || '__' ;
   ELSE
      V_STRBRID := BRID;
   END IF;

   IF(BRGID <> 'ALL') THEN
     V_STRBRGID := BRGID;
   ELSE
     V_STRBRGID := '%';
   END IF;


   V_INDATE  :=  TO_DATE(I_DATE,'DD/MM/YYYY');

OPEN PV_REFCURSOR
FOR
  SELECT DF.ACCTNO, TRALL.TXNUM, TRALL.RLSAMT RLSAMT, DF.TXDATE OPNDATE,
    TRALL.TXDATE EXDATE, LN.OVERDUEDATE OVERDUEDATE,
    ROUND(CASE WHEN (TRALL.INTPAID-TRALL.INTOVDACR) = 0 THEN 0 ELSE (TRALL.INTPAID-TRALL.INTOVDACR) -
            ((0.0014/100)*TO_NUMBER(TRALL.TXDATE-DF.TXDATE)*TRALL.RLSAMT) END) PHIUYTHAC,
    TRALL.INTOVDACR INTOVDACR,  BR.BRNAME BRNAME, TYP.ACTYPE
FROM VW_DFMAST_ALL DF, BRGRP BR, DFTYPE TYP,
    (
        SELECT * FROM
        (
            SELECT ACCTNO LNACCTNO, OVERDUEDATE FROM LNSCHD
                WHERE REFTYPE IN ('P','GP')
            UNION ALL
            SELECT ACCTNO LNACCTNO, OVERDUEDATE FROM LNSCHDHIST
                WHERE REFTYPE IN ('P','GP')
        )
    )LN,
    (
        SELECT TXNUM, TXDATE, DFACCTNO,
            SUM(RLSAMT) RLSAMT,
            SUM(INTOVDACR) INTOVDACR,
            SUM(INTPAID) INTPAID
        FROM
        (
            --- TRA NO GOC
            SELECT TO_CHAR(TR.TXNUM) TXNUM, TR.TXDATE, TR.ACCTNO DFACCTNO,
                TR.NAMT RLSAMT,
                0 INTOVDACR,
                0 INTPAID
            FROM VW_DFTRAN_ALL TR, APPTX TX, VW_DFMAST_ALL DF
            WHERE TR.TXCD = TX.TXCD AND TR.ACCTNO = DF.ACCTNO
                AND TX.FIELD = 'RLSAMT' AND TX.APPTYPE = 'DF' AND TX.TXTYPE = 'C'
                AND TR.NAMT > 0
                AND DF.CIACCTNO LIKE '0011026699'
                AND TR.TXDATE = V_INDATE
            --- TRA NO LAI TREN GOC QUA HAN
            UNION ALL
            SELECT TO_CHAR(TR.TXNUM) TXNUM, TR.TXDATE, DF.ACCTNO DFACCTNO,
                0 RLSAMT,
                SUM(TR.NAMT) INTOVDACR,
                0 INTPAID
            FROM VW_LNTRAN_ALL TR, APPTX TX, VW_DFMAST_ALL DF, VW_LNMAST_ALL LN
            WHERE TR.TXCD = TX.TXCD AND DF.LNACCTNO = LN.ACCTNO
                AND TR.ACCTNO = LN.ACCTNO AND DF.LNACCTNO = LN.ACCTNO
                AND TX.FIELD IN ('INTOVDACR') AND TX.APPTYPE = 'LN' AND TX.TXTYPE = 'D'
                AND TR.NAMT > 0
                AND DF.CIACCTNO LIKE '0011026699'
                AND TR.TXDATE = V_INDATE
            GROUP BY TO_CHAR(TR.TXNUM), TR.TXDATE, DF.ACCTNO
            --- TRA NO TONG LAI
            UNION ALL
            SELECT TO_CHAR(TR.TXNUM) TXNUM, TR.TXDATE, DF.ACCTNO DFACCTNO,
                0 RLSAMT,
                0 INTOVDACR,
                SUM(TR.NAMT) INTPAID
            FROM VW_LNTRAN_ALL TR, APPTX TX, VW_DFMAST_ALL DF, VW_LNMAST_ALL LN
            WHERE TR.TXCD = TX.TXCD AND DF.LNACCTNO = LN.ACCTNO
                AND TR.ACCTNO = LN.ACCTNO AND DF.LNACCTNO = LN.ACCTNO
                AND TX.FIELD IN ('INTPAID') AND TX.APPTYPE = 'LN' AND TX.TXTYPE = 'C'
                AND TR.NAMT > 0
                AND DF.CIACCTNO LIKE '0011026699'
                AND TR.TXDATE = V_INDATE
            GROUP BY TO_CHAR(TR.TXNUM), TR.TXDATE, DF.ACCTNO
        ) TR
        GROUP BY TXNUM, TXDATE, DFACCTNO
    ) TRALL
WHERE DF.LNACCTNO = LN.LNACCTNO
    AND DF.ACCTNO = TRALL.DFACCTNO
    AND BR.BRID = SUBSTR(DF.ACCTNO,1,4)
    AND TYP.ACTYPE = DF.ACTYPE
    AND BR.BRID LIKE V_STRBRGID
ORDER BY DF.TXDATE, DF.ACCTNO

;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN;
END;                                                              -- PROCEDURE
/

