CREATE OR REPLACE PROCEDURE od0028 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   F_DATE         IN       VARCHAR2,
   T_DATE         IN       VARCHAR2,
   SYMBOL         IN       VARCHAR2

)
IS
--
-- PURPOSE: BRIEFLY EXPLAIN THE FUNCTIONALITY OF THE PROCEDURE
-- BAO CAO TINH HINH GIAO DICH CAU KHACH HANG
-- MODIFICATION HISTORY
-- PERSON      DATE    COMMENTS
-- NAMNT   20-DEC-06  CREATED
-- ---------   ------  -------------------------------------------
   V_STROPTION     VARCHAR2 (5);            -- A: ALL; B: BRANCH; S: SUB-BRANCH
   V_STRBRID       VARCHAR2 (4);                   -- USED WHEN V_NUMOPTION > 0
   V_STRSYMBOL   VARCHAR2 (20);

BEGIN
   V_STROPTION := OPT;

   IF (V_STROPTION <> 'A') AND (BRID <> 'ALL')
   THEN
      V_STRBRID := BRID;
   ELSE
      V_STRBRID := '%%';
   END IF;

   -- GET REPORT'S PARAMETERS
    IF  (SYMBOL <> 'ALL')
   THEN
      V_STRSYMBOL:= SYMBOL;
   ELSE
      V_STRSYMBOL := '%%';
   END IF;


   -- END OF GETTING REPORT'S PARAMETERS


   -- GET REPORT'S DATA

      OPEN PV_REFCURSOR
       FOR
SELECT OD.CODEID ,MAX(SB.SYMBOL) SYMBOL, SUM(CASE WHEN OD.EXECTYPE IN ('NB','BC') THEN  OD.ORDERQTTY ELSE 0 END) B_ODQTTY
                  , SUM(CASE WHEN OD.EXECTYPE IN ('NS','SS') THEN  OD.ORDERQTTY ELSE 0  END) S_ODQTTY
                  , SUM(CASE WHEN OD.EXECTYPE IN ('NB','BC') THEN  OD.EXECQTTY ELSE 0 END) B_IOQTTY
                  , SUM(CASE WHEN OD.EXECTYPE IN ('NS','SS') THEN  OD.EXECQTTY ELSE 0 END) S_IOQTTY
                  , SUM(CASE WHEN OD.EXECTYPE IN ('NB','BC') THEN  ( case when EXECAMT > MATCHAMT then EXECAMT else MATCHAMT end) ELSE 0 END) B_IOVALUE
                  , SUM(CASE WHEN OD.EXECTYPE IN ('NS','SS') THEN  ( case when EXECAMT > MATCHAMT then EXECAMT else MATCHAMT end) ELSE 0 END) S_IOVALUE,SUM(OD.FEEACR) FEEACR
 FROM
(
SELECT * FROM  ODMAST
WHERE DELTD <>'Y'
AND  TXDATE >= TO_DATE(F_DATE ,'DD/MM/YYYY')
AND  TXDATE <= TO_DATE(T_DATE ,'DD/MM/YYYY')
AND SUBSTR(AFACCTNO,1,4) LIKE V_STRBRID
and REFORDERID is null
UNION ALL
SELECT * FROM  ODMASTHIST
WHERE DELTD <>'Y'
AND  TXDATE >= TO_DATE(F_DATE ,'DD/MM/YYYY')
AND  TXDATE <= TO_DATE(T_DATE ,'DD/MM/YYYY')
AND SUBSTR(AFACCTNO,1,4) LIKE V_STRBRID
and REFORDERID is null
) OD ,
( SELECT REFORDERID FROM  ODMAST  WHERE DELTD<>'Y' AND REFORDERID IS NOT NULL
  UNION ALL
 SELECT REFORDERID FROM  ODMASTHIST  WHERE DELTD<>'Y' AND REFORDERID IS NOT NULL)ODC
,SBSECURITIES SB
WHERE OD.CODEID = SB.CODEID
AND OD.ORDERID =ODC.REFORDERID(+)
AND ODC.REFORDERID IS NULL
AND SB.SYMBOL LIKE  V_STRSYMBOL
group by  OD.CODEID
ORDER BY MAX(SB.SYMBOL)

;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN;
END;                                                              -- PROCEDURE
/

