CREATE OR REPLACE PROCEDURE od0027 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   F_DATE         IN       VARCHAR2,
   T_DATE         IN       VARCHAR2,
   AFACCTNO       IN       VARCHAR2

)
IS
--
-- PURPOSE: BRIEFLY EXPLAIN THE FUNCTIONALITY OF THE PROCEDURE
-- BAO CAO TINH HINH GIAO DICH CAU KHACH HANG
-- MODIFICATION HISTORY
-- PERSON      DATE    COMMENTS
-- NAMNT   20-DEC-06  CREATED
-- ---------   ------  -------------------------------------------
   V_STROPTION     VARCHAR2 (5);            -- A: ALL; B: BRANCH; S: SUB-BRANCH
   V_STRBRID       VARCHAR2 (4);                   -- USED WHEN V_NUMOPTION > 0
   V_STRAFACCTNO   VARCHAR2 (20);

BEGIN
   V_STROPTION := OPT;

   IF (V_STROPTION <> 'A') AND (BRID <> 'ALL')
   THEN
      V_STRBRID := BRID;
   ELSE
      V_STRBRID := '%%';
   END IF;

   -- GET REPORT'S PARAMETERS
  V_STRAFACCTNO :=AFACCTNO;

   -- END OF GETTING REPORT'S PARAMETERS


   -- GET REPORT'S DATA
  OPEN PV_REFCURSOR
       FOR
SELECT MAX( OD.AFACCTNO) AFACCTNO,MAX(CF.FULLNAME) FULLNAME,OD.TXDATE
                  , SUM(CASE WHEN OD.EXECTYPE IN ('NB','BC') THEN  OD.ORDERQTTY ELSE 0 END) B_ODQTTY
                  , SUM(CASE WHEN OD.EXECTYPE IN ('NS','SS') THEN  OD.ORDERQTTY ELSE 0  END) S_ODQTTY
                  , SUM(CASE WHEN OD.EXECTYPE IN ('NB','BC') THEN  OD.EXECQTTY ELSE 0 END) B_IOQTTY
                  , SUM(CASE WHEN OD.EXECTYPE IN ('NS','SS') THEN  OD.EXECQTTY ELSE 0 END) S_IOQTTY
                  , SUM(CASE WHEN OD.EXECTYPE IN ('NB','BC') THEN  ( CASE WHEN EXECAMT > MATCHAMT THEN EXECAMT ELSE MATCHAMT END) ELSE 0 END) B_IOVALUE
                  , SUM(CASE WHEN OD.EXECTYPE IN ('NS','SS') THEN  ( CASE WHEN EXECAMT > MATCHAMT THEN EXECAMT ELSE MATCHAMT END) ELSE 0 END) S_IOVALUE
 FROM
(
SELECT * FROM  ODMAST
WHERE DELTD <>'Y'
AND  TXDATE >= TO_DATE(F_DATE ,'DD/MM/YYYY')
AND  TXDATE <= TO_DATE(T_DATE ,'DD/MM/YYYY')
AND  AFACCTNO LIKE V_STRAFACCTNO
AND SUBSTR(AFACCTNO,1,4) LIKE V_STRBRID
AND REFORDERID IS NULL
UNION ALL
SELECT * FROM  ODMASTHIST
WHERE DELTD <>'Y'
AND  TXDATE >= TO_DATE(F_DATE ,'DD/MM/YYYY')
AND  TXDATE <= TO_DATE(T_DATE ,'DD/MM/YYYY')
AND  AFACCTNO LIKE V_STRAFACCTNO
AND SUBSTR(AFACCTNO,1,4) LIKE V_STRBRID
AND REFORDERID IS NULL
) OD,
( SELECT REFORDERID FROM  ODMAST  WHERE DELTD<>'Y' AND REFORDERID IS NOT NULL
  UNION ALL
  SELECT REFORDERID FROM  ODMASTHIST  WHERE DELTD<>'Y' AND REFORDERID IS NOT NULL)ODC
,
AFMAST AF,CFMAST CF
WHERE OD.AFACCTNO = AF.ACCTNO
AND OD.ORDERID =ODC.REFORDERID(+)
AND CF.CUSTID =AF.CUSTID
AND ODC.REFORDERID IS NULL
GROUP BY OD.TXDATE
;


EXCEPTION
   WHEN OTHERS
   THEN
      RETURN;
END;                                                              -- PROCEDURE
/

