CREATE OR REPLACE PROCEDURE od1001 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   F_DATE         IN       VARCHAR2,
   T_DATE         IN       VARCHAR2,
   PV_CUSTODYCD   IN       VARCHAR2,
   PV_CIACCTNO    IN       VARCHAR2,
   EXECTYPE       IN       VARCHAR2,
   SYMBOL         IN       VARCHAR2,
   CURRENT_INDEX         NUMBER  DEFAULT NULL,
   OFFSET_NUMBER         NUMBER  DEFAULT NULL,
   ONL                   VARCHAR2  DEFAULT NULL
   )
IS
-- MODIFICATION HISTORY
-- KET QUA KHOP LENH CUA KHACH HANG
-- PERSON      DATE    COMMENTS
-- NAMNT   15-JUN-08  CREATED
-- DUNGNH  08-SEP-09  MODIFIED
-- ---------   ------  -------------------------------------------
   V_STROPTION      VARCHAR2 (5);            -- A: ALL; B: BRANCH; S: SUB-BRANCH
   V_STRBRID        VARCHAR2 (4);            -- USED WHEN V_NUMOPTION > 0
   V_STREXECTYPE    VARCHAR2 (5);
   V_STRSYMBOL      VARCHAR2 (15);
   V_STRTRADEPLACE  VARCHAR2 (3);
   V_CIACCTNO       VARCHAR2 (20);
   V_NUMBUY         NUMBER (20,2);
   PVC_CIACCTNO      VARCHAR2 (20);
   PVC_CUSTODYCD     VARCHAR2 (20);


-- DECLARE PROGRAM VARIABLES AS SHOWN ABOVE
BEGIN
   V_STROPTION := OPT;

   IF (V_STROPTION <> 'A') AND (BRID <> 'ALL')
   THEN
      V_STRBRID := BRID;
   ELSE
      V_STRBRID := '%%';
   END IF;

    -- GET REPORT'S PARAMETERS
   --
    IF (SYMBOL <> 'ALL')
   THEN
      V_STRSYMBOL := SYMBOL;
   ELSE
      V_STRSYMBOL := '%%';
   END IF;
   --
   IF (EXECTYPE <> 'ALL')
   THEN
      V_STREXECTYPE := EXECTYPE;
   ELSE
      V_STREXECTYPE := '%%';
   END IF;
   --
   IF (  PV_CIACCTNO  <> 'ALL')
   THEN
    PVC_CIACCTNO := PV_CIACCTNO;
   ELSE
      PVC_CIACCTNO:= '%%';
   END IF;
   PVC_CUSTODYCD:=  PV_CUSTODYCD  ;


--SELECT SUM(CASE WHEN ODM.EXECTYPE = 'NB' OR ODM.EXECTYPE = 'BC' THEN NVL(ODM.EXECAMT,0) ELSE 0 END ) INTO V_NUMBUY
   -- FROM (SELECT * FROM ODMAST UNION ALL SELECT * FROM ODMASTHIST ) ODM
       -- WHERE ODM.TXDATE >= TO_DATE(F_DATE, 'DD/MM/YYYY')
           -- AND ODM.TXDATE <= TO_DATE(T_DATE, 'DD/MM/YYYY')
            --AND ODM.EXECTYPE IN ('NB','BC')
            --AND ODM.EXECAMT <> 0
            --AND ODM.DELTD <> 'Y'
           -- AND ODM.afacctno

   -- GET REPORT'S DATA
IF (ONL IS NULL OR ONL = 'ALL')THEN

 OPEN PV_REFCURSOR
       FOR
SELECT DT.*, NVL(V_NUMBUY,0) TOTALBUY  FROM
     (SELECT  ROWNUM ROWN,T.*,NVL(IO.MATCHQTTY,0) MATCHQTTY,NVL(IO.MATCHPRICE,0) MATCHPRICE,NVL(IO.MATCHQTTY,0)*NVL(IO.MATCHPRICE,0) VAL_IOD ,
     round((CASE  WHEN  NVL(T.EXECAMT,0)= 0   THEN 0 ELSE T.FEEACR *100/NVL(T.EXECAMT,0) END ),4) PERFEE,
            ((CASE  WHEN T.EXECTYPE IN('NB','BC')  THEN   NVL(IO.MATCHQTTY,0)* NVL(IO.MATCHPRICE,0) END)) MB,
            ((CASE  WHEN T.EXECTYPE IN('NS','SS','MS')  THEN   NVL(IO.MATCHQTTY,0)* NVL(IO.MATCHPRICE,0) END)) MC

      FROM (SELECT OD.ORDERID,OD.TXDATE,
            (CASE  WHEN OD.EXECTYPE IN('NB','BC','NS','SS') AND OD.REFORDERID IS NOT NULL AND OD.CORRECTIONNUMBER = 0 THEN 'C'  ELSE OD.EXECTYPE END)EXECTYPE
            ,SB.SYMBOL,(CASE WHEN OD.PRICETYPE IN ('ATO','ATC')THEN  OD.PRICETYPE  ELSE  TO_CHAR(OD.QUOTEPRICE) END )QUOTEPRICE ,
             OD.ORDERQTTY,OD.CIACCTNO,CF.FULLNAME,OD.FEEACR,
             SB.TRADEPLACE TRADEPLACE, ( CASE WHEN OD.EXECAMT > OD.MATCHAMT THEN OD.EXECAMT ELSE OD.MATCHAMT END  ) EXECAMT


               FROM
           ( SELECT* FROM ODMAST   WHERE DELTD <> 'Y' UNION ALL SELECT * FROM ODMASTHIST   WHERE DELTD<>'Y' )OD,
             SBSECURITIES SB,AFMAST AF ,CFMAST CF
             WHERE  OD.CODEID = SB.CODEID
                   AND OD.CIACCTNO = AF.ACCTNO
                   AND AF.CUSTID = CF.CUSTID
                   AND OD.TXDATE >= TO_DATE (F_DATE, 'DD/MM/YYYY')
                   AND OD.TXDATE <= TO_DATE (T_DATE, 'DD/MM/YYYY')
                   AND SB.SYMBOL like V_STRSYMBOL
                   AND AF.ACCTNO LIKE PVC_CIACCTNO
                   AND CF.CUSTODYCD  LIKE PVC_CUSTODYCD
                   AND OD.EXECTYPE like V_STREXECTYPE
              ORDER BY  UPPER(FULLNAME) DESC, UPPER(SYMBOL), TXDATE, ORDERID )T
              LEFT JOIN
                  ( SELECT * FROM IOD WHERE DELTD<>'Y'UNION ALL  SELECT * FROM IODHIST  WHERE DELTD<>'Y' ) IO
             ON IO.ORGORDERID=T.ORDERID)DT
 WHERE  DT.ROWN BETWEEN (NVL(CURRENT_INDEX,1)-1)*NVL(OFFSET_NUMBER,1000000) +1 AND NVL(CURRENT_INDEX,1)*NVL(OFFSET_NUMBER,1000000)
;

ELSE
-- DANH CHO OLL
     OPEN PV_REFCURSOR
       FOR
    SELECT DT.*, NVL(V_NUMBUY,0) TOTALBUY FROM
     (SELECT ROWNUM ROWN, T.*, NVL(IO.MATCHQTTY,0) MATCHQTTY, NVL(IO.MATCHPRICE,0) MATCHPRICE,NVL(IO.MATCHQTTY,0)*NVL(IO.MATCHPRICE,0) VAL_IOD ,
      (CASE WHEN NVL(T.EXECAMT,0)= 0 THEN 0 ELSE T.FEEACR *100/NVL(T.EXECAMT,0) END ) PERFEE
            FROM
            (
          SELECT OD.ORDERID,OD.TXDATE,
          (CASE  WHEN OD.EXECTYPE IN('NB','BC','NS','SS') AND OD.REFORDERID IS NOT NULL AND OD.CORRECTIONNUMBER = 0 THEN 'C'  ELSE OD.EXECTYPE END)EXECTYPE
            ,SB.SYMBOL,(CASE WHEN OD.PRICETYPE IN ('ATO','ATC')THEN  OD.PRICETYPE  ELSE  TO_CHAR(OD.QUOTEPRICE) END )QUOTEPRICE ,
            OD.ORDERQTTY,OD.CIACCTNO,CF.FULLNAME,OD.FEEACR,
             SB.TRADEPLACE TRADEPLACE, ( CASE WHEN OD.EXECAMT > OD.MATCHAMT THEN OD.EXECAMT ELSE OD.MATCHAMT END  ) EXECAMT
               FROM
            ( SELECT* FROM ODMAST   WHERE DELTD<>'Y' UNION ALL SELECT * FROM ODMASTHIST   WHERE DELTD<>'Y' )OD,
             SBSECURITIES SB,AFMAST AF,CFMAST CF
             WHERE  OD.CODEID = SB.CODEID
                   AND OD.CIACCTNO = AF.ACCTNO
                   AND AF.CUSTID = CF.CUSTID
                   AND OD.TXDATE >= TO_DATE (F_DATE, 'DD/MM/YYYY')
                   AND OD.TXDATE <= TO_DATE (T_DATE, 'DD/MM/YYYY')
                   AND SB.SYMBOL like V_STRSYMBOL
                   AND OD.EXECTYPE like V_STREXECTYPE
                   AND CF.REFNAME like ONL
                   ORDER BY  UPPER(FULLNAME) DESC, UPPER(SYMBOL), TXDATE, ORDERID
             )T
              LEFT JOIN
                  (SELECT * FROM IOD WHERE DELTD<>'Y'UNION ALL  SELECT * FROM IODHIST  WHERE DELTD<>'Y' ) IO
             ON IO.ORGORDERID=T.ORDERID
            ORDER BY  UPPER(T.FULLNAME) DESC, UPPER(T.SYMBOL), T.TXDATE, T.ORDERID   )DT
 WHERE  DT.ROWN BETWEEN (NVL(CURRENT_INDEX,1)-1)*NVL(OFFSET_NUMBER,1000000) +1 AND NVL(CURRENT_INDEX,1)*NVL(OFFSET_NUMBER,1000000)
 ;
END IF;

EXCEPTION
   WHEN OTHERS
   THEN
      RETURN;
END;                                                              -- PROCEDURE
/

