CREATE OR REPLACE PROCEDURE SE0015 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   F_DATE         IN       VARCHAR2,
   T_DATE         IN       VARCHAR2,
   AFACCTNO       IN       VARCHAR2,
   SYMBOL         in       VARCHAR2
  )
IS
--
-- PURPOSE: BRIEFLY EXPLAIN THE FUNCTIONALITY OF THE PROCEDURE
-- BAO CAO TAI KHOAN TIEN TONG HOP CUA NGUOI DAU TU
-- MODIFICATION HISTORY
-- PERSON      DATE    COMMENTS
-- NAMNT   20-DEC-06  CREATED
-- ---------   ------  -------------------------------------------

   CUR             PKG_REPORT.REF_CURSOR;
   V_STROPTION    VARCHAR2 (5);            -- A: ALL; B: BRANCH; S: SUB-BRANCH
   V_STRBRID      VARCHAR2 (4);                   -- USED WHEN V_NUMOPTION > 0
   V_STRAFACCTNO  VARCHAR2 (20);
   V_STRSYMBOL  VARCHAR2 (20);
BEGIN
   V_STROPTION := OPT;

   IF (V_STROPTION <> 'A') AND (BRID <> 'ALL')
   THEN
      V_STRBRID := BRID;
   ELSE
      V_STRBRID := '%%';
   END IF;

    IF (V_STRSYMBOL <> 'ALL')
   THEN
      V_STRSYMBOL := SYMBOL;
   ELSE
      V_STRSYMBOL := '%%';
   END IF;

   -- GET REPORT'S PARAMETERS


   IF (AFACCTNO <> 'ALL')
   THEN
      V_STRAFACCTNO :=  AFACCTNO;
   ELSE
      V_STRAFACCTNO := '%%';
   END IF;
   -- END OF GETTING REPORT'S PARAMETERS
--TINH NGAY NHAN THANH TOAN BU TRU

OPEN  PV_REFCURSOR FOR

SELECT TL.BUSDATE ,SB.SYMBOL ,CF.CUSTODYCD ,CF.FULLNAME ,TL.MSGAMT , TL.TLTXCD,tl.txdesc
FROM TLLOG TL,SBSECURITIES SB, AFMAST AF, CFMAST CF
WHERE SUBSTR(TL.MSGACCT,11,6)=SB.CODEID
AND SUBSTR(TL.MSGACCT,1,10) =AF.ACCTNO
AND AF.CUSTID =CF.CUSTID
AND TL.tltxcd IN ('2250','2251')
and tl.deltd <>'Y'
AND TL.busdate>= to_date(F_DATE,'DD/MM/YYYY')
AND TL.busdate<= to_date(T_DATE,'DD/MM/YYYY')
and AF.acctno LIKE V_STRAFACCTNO
AND SB.symbol LIKE V_STRSYMBOL

union all
SELECT TL.BUSDATE ,SB.SYMBOL ,CF.CUSTODYCD ,CF.FULLNAME ,TL.MSGAMT , TL.TLTXCD,tl.txdesc
FROM TLLOGALL TL,SBSECURITIES SB, AFMAST AF, CFMAST CF
WHERE SUBSTR(TL.MSGACCT,11,6)=SB.CODEID
AND SUBSTR(TL.MSGACCT,1,10) =AF.ACCTNO
AND AF.CUSTID =CF.CUSTID
and tl.deltd <>'Y'
AND TL.tltxcd IN ('2250','2251')
AND TL.busdate>= to_date(F_DATE,'DD/MM/YYYY')
AND TL.busdate<= to_date(T_DATE,'DD/MM/YYYY')
and AF.acctno LIKE V_STRAFACCTNO
AND SB.symbol LIKE V_STRSYMBOL

;




EXCEPTION
   WHEN OTHERS
   THEN
      RETURN;
END;                                                              -- PROCEDURE
/

