--
--
/
DELETE VSDTRFCODE WHERE TLTXCD = '2292';
INSERT INTO VSDTRFCODE (TRFCODE,DESCRIPTION,VSDMT,STATUS,TYPE,TLTXCD,SEARCHCODE,FILTERNAME,REQTLTXCD,AUTOCONF)
VALUES ('542.NEWM.CLAS//PEND/2.SETR//TRAD.STCO//PHYS','Rút chứng khoán HCCN','542','N','REQ','2292',null,null,null,'Y');
INSERT INTO VSDTRFCODE (TRFCODE,DESCRIPTION,VSDMT,STATUS,TYPE,TLTXCD,SEARCHCODE,FILTERNAME,REQTLTXCD,AUTOCONF)
VALUES ('542.NEWM.CLAS//PEND/1.SETR//TRAD.STCO//PHYS','Rút chứng khoán thông thường','542','N','REQ','2292',null,null,null,'Y');
INSERT INTO VSDTRFCODE (TRFCODE,DESCRIPTION,VSDMT,STATUS,TYPE,TLTXCD,SEARCHCODE,FILTERNAME,REQTLTXCD,AUTOCONF)
VALUES ('542.NEWM.CLAS//NORM/2.SETR//TRAD.STCO//PHYS','Rút chứng khoán HCCN','542','Y','REQ','2292',null,null,null,'Y');
INSERT INTO VSDTRFCODE (TRFCODE,DESCRIPTION,VSDMT,STATUS,TYPE,TLTXCD,SEARCHCODE,FILTERNAME,REQTLTXCD,AUTOCONF)
VALUES ('542.NEWM.CLAS//NORM/1.SETR//TRAD.STCO//PHYS','Rút chứng khoán thông thường','542','Y','REQ','2292',null,null,null,'Y');
COMMIT;
/
