--
--
/
DELETE VSDTRFCODE WHERE TLTXCD = '2294';
INSERT INTO VSDTRFCODE (TRFCODE,DESCRIPTION,VSDMT,STATUS,TYPE,TLTXCD,SEARCHCODE,FILTERNAME,REQTLTXCD,AUTOCONF)
VALUES ('548.INST.LINK//542.SETR//TRAD.STCO//PHYS','Từ chối rút chứng khoán','548','Y','CFN','2294','SE2294',null,'2292','Y');
INSERT INTO VSDTRFCODE (TRFCODE,DESCRIPTION,VSDMT,STATUS,TYPE,TLTXCD,SEARCHCODE,FILTERNAME,REQTLTXCD,AUTOCONF)
VALUES ('542.NEWM.CLAS//PEND/2.SETR//TRAD.STCO//PHYS.NAK','Điện rút chứng khoán bị NAK','548','Y','CFN','2294','SE2294',null,'2292','Y');
INSERT INTO VSDTRFCODE (TRFCODE,DESCRIPTION,VSDMT,STATUS,TYPE,TLTXCD,SEARCHCODE,FILTERNAME,REQTLTXCD,AUTOCONF)
VALUES ('542.NEWM.CLAS//PEND/1.SETR//TRAD.STCO//PHYS.NAK','Điện rút chứng khoán bị NAK','548','Y','CFN','2294','SE2294',null,'2292','Y');
INSERT INTO VSDTRFCODE (TRFCODE,DESCRIPTION,VSDMT,STATUS,TYPE,TLTXCD,SEARCHCODE,FILTERNAME,REQTLTXCD,AUTOCONF)
VALUES ('542.NEWM.CLAS//NORM/2.SETR//TRAD.STCO//PHYS.NAK','Điện rút chứng khoán bị NAK','548','Y','CFN','2294','SE2294',null,'2292','Y');
INSERT INTO VSDTRFCODE (TRFCODE,DESCRIPTION,VSDMT,STATUS,TYPE,TLTXCD,SEARCHCODE,FILTERNAME,REQTLTXCD,AUTOCONF)
VALUES ('542.NEWM.CLAS//NORM/1.SETR//TRAD.STCO//PHYS.NAK','Điện rút chứng khoán bị NAK','548','Y','CFN','2294','SE2294',null,'2292','Y');
COMMIT;
/
