--
--
/
DELETE VSDTRFCODE WHERE TLTXCD = '2248';
INSERT INTO VSDTRFCODE (TRFCODE,DESCRIPTION,VSDMT,STATUS,TYPE,TLTXCD,SEARCHCODE,FILTERNAME,REQTLTXCD,AUTOCONF)
VALUES ('546.NEWM.LINK//598.SETR//TBAC.','Chấp thuận chuyển khoản đóng tài khoản','546','Y','CFO','2248','SE2248',null,'2247','Y');
COMMIT;
/
