CREATE OR REPLACE FORCE VIEW V_SEARCHCD AS
SELECT S.SEARCHCODE SEARCHCODE, S.SEARCHTITLE SEARCHTITLE, S.EN_SEARCHTITLE EN_SEARCHTITLE, S.SEARCHCMDSQL SEARCHCMDSQL,
        S.OBJNAME OBJNAME, S.FRMNAME FRMNAME,S.ORDERBYCMDSQL ORDERBYCMDSQL, SF.POSITION POSITION, SF.FIELDCODE FIELDCODE,
        SF.FIELDNAME FIELDNAME, SF.EN_FIELDNAME EN_FIELDNAME, SF.FIELDTYPE FIELDTYPE, SF.FIELDSIZE FIELDSIZE, SF.MASK MASK,
        SF.OPERATOR OPERATOR, SF.FORMAT FORMAT, SF.DISPLAY DISPLAY, SF.SRCH SRCH, SF.KEY KEY, REFVALUE, S.TLTXCD,
        SF.WIDTH WIDTH, SF.LOOKUPCMDSQL LOOKUPCMDSQL, s.AUTHCODE,s.rowlimit
    FROM SEARCH S, SEARCHFLD SF
    WHERE S.SEARCHCODE = SF.SEARCHCODE;

