CREATE OR REPLACE FORCE VIEW V_SEMASTCV AS
SELECT CF.CUSTODYCD,SB.SYMBOL   ,SE.TRADE,  abs(SE.STANDING) STANDING, SE.MORTAGE+SE.STANDING MORTAGE , nvl( SEW.WAITFORTRADE,0)WAITFORTRADE, NVL(SE1.QTTY,0)BLOCKED ,NVL(SE2.QTTY,0)BLOCKW,CF.BRID
FROM SEMAST SE ,CFMAST CF, SBSECURITIES SB,
(SELECT QTTY,ACCTNO  FROM SEMASTDTL WHERE QTTYTYPE='002'  )SE1,
(SELECT QTTY,ACCTNO  FROM SEMASTDTL WHERE  QTTYTYPE='007' 
  )SE2,
(SELECT SE.TRADE  WAITFORTRADE,SE.ACCTNO , AFACCTNO||REFCODEID SEACCTNOW  FROM SEMAST SE , SBSECURITIES SB 
WHERE SE.CODEID = SB.CODEID AND SB.REFCODEID IS NOT NULL 
) SEW
WHERE SE.CUSTID = CF.CUSTID
AND SE.CODEID = NVL(SB.REFCODEID, SB.CODEID)
AND SE.ACCTNO = SE1.ACCTNO (+)
AND SE.ACCTNO = SE2.ACCTNO (+)
AND SE.ACCTNO = SEW.SEACCTNOW (+)
AND (SE.TRADE <> 0 OR  SE.STANDING <>0 OR  SE.MORTAGE+SE.STANDING <>0 OR  NVL(SE1.QTTY,0)<> 0 OR NVL(SE2.QTTY,0)<>0 OR NVL(SEW.WAITFORTRADE,0)<>0)
AND SB.REFCODEID IS NULL 
ORDER BY CF.CUSTODYCD,SYMBOL;

