create or replace force view vw_iod_all as
select "ORGORDERID","EXORDERID","CODEID","SYMBOL","CUSTODYCD","BORS","NORP","AORN","PRICE","QTTY","REFCUSTCD","MATCHPRICE","MATCHQTTY","TXNUM","TXDATE","DELTD","CONFIRM_NO","TXTIME",IODFEEACR,IODTAXSELLAMT from iod
union all
select "ORGORDERID","EXORDERID","CODEID","SYMBOL","CUSTODYCD","BORS","NORP","AORN","PRICE","QTTY","REFCUSTCD","MATCHPRICE","MATCHQTTY","TXNUM","TXDATE","DELTD","CONFIRM_NO","TXTIME",IODFEEACR,IODTAXSELLAMT from iodhist;

