create or replace force view vw_stschd_all as
select AUTOID,DUETYPE,ACCTNO,REFORDERID,TXDATE,CLEARDAY,CLEARCD,AMT,AAMT,QTTY,AQTTY,FAMT,AFACCTNO,STATUS,DELTD,TXNUM,ORGORDERID,CODEID,PAIDAMT,PAIDFEEAMT,COSTPRICE,CLEARDATE,RIGHTQTTY,ARIGHT,TRFBUYDT,TRFBUYSTS,TRFEXEAMT,TRFBUYRATE,TRFBUYEXT,DFAMT,TRFT0AMT
from STSCHD where deltd <> 'Y'
union all
select AUTOID,DUETYPE,ACCTNO,REFORDERID,TXDATE,CLEARDAY,CLEARCD,AMT,AAMT,QTTY,AQTTY,FAMT,AFACCTNO,STATUS,DELTD,TXNUM,ORGORDERID,CODEID,PAIDAMT,PAIDFEEAMT,COSTPRICE,CLEARDATE,RIGHTQTTY,ARIGHT,TRFBUYDT,TRFBUYSTS,TRFEXEAMT,TRFBUYRATE,TRFBUYEXT,DFAMT,TRFT0AMT
from STSCHDHIST where deltd <> 'Y';

