CREATE OR REPLACE FORCE VIEW VW_VSDTXREQ_HIST AS
SELECT REQ.REQID,REQ.OBJNAME,REQ.TRFCODE,REQ.OBJKEY,to_date(REQ.TXDATE,'DD/MM/RRRR')TXDATE ,REQ.Afacctno,REQ.MSGACCT,REQ.NOTES,
A5.CDCONTENT MSGSTATUS,
REQ.VSD_ERR_MSG ,to_char(req.CREATEDATE,'hh24:mi:ss') CREATEDATE ,req.tlid,tl.tlname,A6.CDCONTENT AUTOCONF,
CF.CUSTODYCD , CF.FULLNAME CUSTNAME ,
to_char(NVL(log.Timecreated, LOG2.TIMECREATED),'hh24:mi:ss') CREATEDATE2, to_date(to_char(NVL(log.Timecreated, LOG2.TIMECREATED),'DD/MM/RRRR'),'DD/MM/RRRR') TXDATE2,
CASE WHEN req.objname ='2255' AND instr(req.trfcode,'598.') >0 THEN NULL ELSE DTL.CVAL END SYMBOL,
CASE WHEN req.objname ='2255' AND instr(req.trfcode,'598.') >0 THEN NULL ELSE REQ.TXAMT END QTTY,
CASE WHEN INSTR(REQ.TRFCODE,'CLAS//NORM/1') > 0 OR INSTR(REQ.TRFCODE,'CLAS//PEND/1') >0 THEN 'TDCN'
     WHEN INSTR(REQ.TRFCODE,'CLAS//NORM/2') > 0 OR INSTR(REQ.TRFCODE,'CLAS//PEND/2') > 0 THEN 'HCCN'
       ELSE '' END TYPE , NVL(LOG.REFMSGID,LOG2.REFMSGID) REFMSGID
FROm vsdtxreqhist REQ, ALLCODE A5,tlprofiles tl,allcode a6,
     (SELECT REFERENCEID, MIN(AUTOCONF) AUTOCONF,TIMECREATED,REFMSGID  FROM
       (SELECT * FROM VSDTRFLOG LOG WHERE INSTR(LOG.FUNCNAME,'.ACK') =0 )
        GROUP BY REFERENCEID,TIMECREATED,REFMSGID
      )LOG, (SELECT * FROM VSDTXREQDTL WHERE FLDNAME = 'SYMBOL') DTL,
      (SELECT REFERENCEID, MIN(AUTOCONF) AUTOCONF,TIMECREATED,REFMSGID FROM
       (SELECT * FROM VSDTRFLOG LOG WHERE INSTR(LOG.FUNCNAME,'.ACK') > 0
               AND LOG.REFERENCEID NOT IN (SELECT REFERENCEID FROM VSDTRFLOG WHERE INSTR(LOG.FUNCNAME,'.ACK') =0))
        GROUP BY REFERENCEID,TIMECREATED,REFMSGID
      )LOG2,
          CFMAST CF, AFMAST AF
WHERE A5.CDTYPE='SA' AND A5.CDNAME='NSDSTATUS' AND A5.CDVAL=REQ.MSGSTATUS
AND A6.CDTYPE='SY' AND A6.CDNAME='YESNO' AND A6.CDVAL=nvl(LOG.AUTOCONF,'Y')
and req.tlid=tl.tlid(+)
AND REQ.REQID=LOG.REFERENCEID(+)
AND DTL.REQID(+) = REQ.REQID
AND AF.ACCTNO = SUBSTR(REQ.MSGACCT,1,10)
AND AF.CUSTID = CF.CUSTID
AND REQ.REQID = LOG2.REFERENCEID(+)
AND REQ.OBJNAME IN ('2241','2255','2292','8815'/*,'2245'*/)
UNION ALL
SELECT REQ.REQID,REQ.OBJNAME,REQ.TRFCODE,REQ.OBJKEY,
CASE WHEN VCODE.TYPE = 'INF' THEN NULL ELSE to_date(REQ.TXDATE,'DD/MM/RRRR') END TXDATE ,
CASE WHEN REQ.Afacctno = '0' THEN '' ELSE REQ.Afacctno END Afacctno ,REQ.MSGACCT,REQ.NOTES,
A5.CDCONTENT MSGSTATUS,
REQ.VSD_ERR_MSG ,
CASE WHEN VCODE.TYPE = 'INF' THEN '' ELSE to_char(req.CREATEDATE,'hh24:mi:ss') END CREATEDATE ,
req.tlid,tl.tlname,A6.CDCONTENT AUTOCONF,
DTL2.CVAL CUSTODYCD, DTL3.CVAL CUSTNAME ,
to_char(NVL(log.Timecreated, LOG2.TIMECREATED),'hh24:mi:ss') CREATEDATE2, to_date(to_char(NVL(log.Timecreated, LOG2.TIMECREATED),'DD/MM/RRRR'),'DD/MM/RRRR') TXDATE2,
'' SYMBOL, (CASE WHEN REQ.TXAMT = 0 OR REQ.OBJNAME ='2247' THEN NULL ELSE REQ.TXAMT END) QTTY,'' TYPE, NVL(LOG.REFMSGID,LOG2.REFMSGID) REFMSGID
FROm vsdtxreqhist REQ, ALLCODE A5,tlprofiles tl,allcode a6,
     (SELECT REFERENCEID, MIN(AUTOCONF) AUTOCONF,TIMECREATED,REFMSGID FROM
       (SELECT * FROM VSDTRFLOG LOG WHERE INSTR(LOG.FUNCNAME,'.ACK') =0 )
        GROUP BY REFERENCEID,TIMECREATED,REFMSGID
      )LOG,
      (SELECT REFERENCEID, MIN(AUTOCONF) AUTOCONF,TIMECREATED,REFMSGID FROM
       (SELECT * FROM VSDTRFLOG LOG WHERE INSTR(LOG.FUNCNAME,'.ACK') > 0
               AND LOG.REFERENCEID NOT IN (SELECT REFERENCEID FROM VSDTRFLOG WHERE INSTR(LOG.FUNCNAME,'.ACK') =0))
        GROUP BY REFERENCEID,TIMECREATED,REFMSGID
      )LOG2
      ,(SELECT * FROM VSDTXREQDTL WHERE FLDNAME = 'CUSTODYCD') DTL2,
      (SELECT * FROM VSDTXREQDTL WHERE FLDNAME = 'FULLNAME') DTL3,
      VSDTRFCODE VCODE
WHERE A5.CDTYPE='SA' AND A5.CDNAME='NSDSTATUS' AND A5.CDVAL=REQ.MSGSTATUS
AND A6.CDTYPE='SY' AND A6.CDNAME='YESNO' AND A6.CDVAL=nvl(LOG.AUTOCONF,'Y')
and req.tlid=tl.tlid(+)
AND REQ.REQID=LOG.REFERENCEID(+)
AND REQ.REQID = LOG2.REFERENCEID(+)
AND DTL2.REQID(+) = REQ.REQID
AND DTL3.REQID(+) = REQ.REQID
AND (REQ.OBJNAME NOT IN ('2241','2255','2292','8815','2245') OR REQ.OBJNAME IS NULL)
AND VCODE.TRFCODE = REQ.TRFCODE
UNION ALL
SELECT REQ.REQID,REQ.OBJNAME,REQ.TRFCODE,REQ.OBJKEY,
CASE WHEN VCODE.TYPE = 'INF' THEN NULL ELSE to_date(REQ.TXDATE,'DD/MM/RRRR') END TXDATE ,
CASE WHEN REQ.Afacctno = '0' THEN '' ELSE REQ.Afacctno END Afacctno ,REQ.MSGACCT,REQ.NOTES,
A5.CDCONTENT MSGSTATUS,REQ.VSD_ERR_MSG ,CASE WHEN VCODE.TYPE = 'INF' THEN '' ELSE to_char(req.CREATEDATE,'hh24:mi:ss') END CREATEDATE ,
req.tlid,tl.tlname,A6.CDCONTENT AUTOCONF,
DTL2.FLDVAL CUSTODYCD, CF.FULLNAME CUSTNAME ,
to_char(NVL(log.Timecreated, LOG2.TIMECREATED),'hh24:mi:ss') CREATEDATE2, to_date(to_char(NVL(log.Timecreated, LOG2.TIMECREATED),'DD/MM/RRRR'),'DD/MM/RRRR') TXDATE2,
DTL3.FLDVAL SYMBOL, TO_NUMBER(REPLACE(DTL1.FLDVAL,',','')) QTTY,
CASE WHEN (DTL4.FLDVAL = 'NORM' AND DTL5.FLDVAL = '1') OR (DTL4.FLDVAL = 'PEND' AND DTL5.FLDVAL = '1') THEN 'TDCN'
     WHEN (DTL4.FLDVAL = 'NORM' AND DTL5.FLDVAL = '2') OR (DTL4.FLDVAL = 'PEND' AND DTL5.FLDVAL = '2') THEN 'HCCN' END TYPE, NVL(LOG.REFMSGID,LOG2.REFMSGID) REFMSGID
FROm vsdtxreqhist REQ, ALLCODE A5,tlprofiles tl,allcode a6,
     (SELECT AUTOID,REFERENCEID, MIN(AUTOCONF) AUTOCONF,TIMECREATED,REFMSGID FROM
       (SELECT * FROM VSDTRFLOG LOG WHERE INSTR(LOG.FUNCNAME,'.ACK') =0 )
        GROUP BY REFERENCEID,TIMECREATED,REFMSGID,AUTOID
      )LOG,
      (SELECT REFERENCEID, MIN(AUTOCONF) AUTOCONF,TIMECREATED,REFMSGID FROM
       (SELECT * FROM VSDTRFLOG LOG WHERE INSTR(LOG.FUNCNAME,'.ACK') > 0
               AND LOG.REFERENCEID NOT IN (SELECT REFERENCEID FROM VSDTRFLOG WHERE INSTR(LOG.FUNCNAME,'.ACK') =0))
        GROUP BY REFERENCEID,TIMECREATED,REFMSGID
      )LOG2,
      (SELECT * FROM VSDTRFLOGDTL WHERE FLDNAME = 'QTTY') DTL1,
      (SELECT * FROM VSDTRFLOGDTL WHERE FLDNAME = 'CUSTODYCD') DTL2,
      (SELECT * FROM VSDTRFLOGDTL WHERE FLDNAME = 'SYMBOL') DTL3,
      (SELECT * FROM VSDTRFLOGDTL WHERE FLDNAME = 'SYMBOLTYPE') DTL4,
      (SELECT * FROM VSDTRFLOGDTL WHERE FLDNAME = 'SECTYPE') DTL5,
      VSDTRFCODE VCODE, CFMAST CF
WHERE A5.CDTYPE='SA' AND A5.CDNAME='NSDSTATUS' AND A5.CDVAL=REQ.MSGSTATUS
AND A6.CDTYPE='SY' AND A6.CDNAME='YESNO' AND A6.CDVAL=nvl(LOG.AUTOCONF,'Y')
and req.tlid=tl.tlid(+)
AND REQ.REQID=LOG.REFERENCEID(+)
AND REQ.REQID = LOG2.REFERENCEID(+)
AND DTL1.REFAUTOID(+) = LOG.AUTOID
AND DTL2.REFAUTOID(+) = LOG.AUTOID
AND DTL3.REFAUTOID(+) = LOG.AUTOID
AND DTL4.REFAUTOID(+) = LOG.AUTOID
AND DTL5.REFAUTOID(+) = LOG.AUTOID
AND REQ.OBJNAME IN ('2245')
AND VCODE.TRFCODE = REQ.TRFCODE
AND CF.CUSTODYCD = DTL2.FLDVAL;

