--
--
/
DELETE FLDMASTER WHERE OBJNAME = 'CF.V_USERLIMIT';
INSERT INTO FLDMASTER (MODCODE,FLDNAME,OBJNAME,DEFNAME,CAPTION,EN_CAPTION,ODRNUM,FLDTYPE,FLDMASK,FLDFORMAT,FLDLEN,LLIST,LCHK,DEFVAL,VISIBLE,DISABLE,MANDATORY,AMTEXP,VALIDTAG,LOOKUP,DATATYPE,INVNAME,FLDSOURCE,FLDDESC,CHAINNAME,PRINTINFO,LOOKUPNAME,SEARCHCODE,SRMODCODE,INVFORMAT,CTLTYPE,RISKFLD,GRNAME,TAGFIELD,TAGVALUE,TAGLIST,TAGQUERY,PDEFNAME,TAGUPDATE,FLDRND,SUBFIELD,PDEFVAL,DEFDESC,DEFPARAM)
VALUES ('CF','TLIDUSER','CF.V_USERLIMIT','TLIDUSER','Tên đăng nhập','TLID/Username',1,'M','ccccccccccccc',null,10,' ',' ',' ','Y','N','Y',' ',' ','N','C',null,null,null,null,null,null,null,null,null,null,'N','MAIN',null,null,null,'N',null,'Y',null,'N',null,null,null);
COMMIT;
/
