--
--
/
DELETE FLDMASTER WHERE OBJNAME = '9967';
INSERT INTO FLDMASTER (MODCODE,FLDNAME,OBJNAME,DEFNAME,CAPTION,EN_CAPTION,ODRNUM,FLDTYPE,FLDMASK,FLDFORMAT,FLDLEN,LLIST,LCHK,DEFVAL,VISIBLE,DISABLE,MANDATORY,AMTEXP,VALIDTAG,LOOKUP,DATATYPE,INVNAME,FLDSOURCE,FLDDESC,CHAINNAME,PRINTINFO,LOOKUPNAME,SEARCHCODE,SRMODCODE,INVFORMAT,CTLTYPE,RISKFLD,GRNAME,TAGFIELD,TAGVALUE,TAGLIST,TAGQUERY,PDEFNAME,TAGUPDATE,FLDRND,SUBFIELD,PDEFVAL,DEFDESC,DEFPARAM)
VALUES ('SE','30','9967','DESC','Mô tả','Description',3,'C',' ',' ',250,' ',' ',' ','Y','N','N',' ',' ','N','C',null,null,null,null,'##########',null,null,null,null,'T','N','MAIN',null,null,null,'N',null,'Y',null,'N',null,null,null);
INSERT INTO FLDMASTER (MODCODE,FLDNAME,OBJNAME,DEFNAME,CAPTION,EN_CAPTION,ODRNUM,FLDTYPE,FLDMASK,FLDFORMAT,FLDLEN,LLIST,LCHK,DEFVAL,VISIBLE,DISABLE,MANDATORY,AMTEXP,VALIDTAG,LOOKUP,DATATYPE,INVNAME,FLDSOURCE,FLDDESC,CHAINNAME,PRINTINFO,LOOKUPNAME,SEARCHCODE,SRMODCODE,INVFORMAT,CTLTYPE,RISKFLD,GRNAME,TAGFIELD,TAGVALUE,TAGLIST,TAGQUERY,PDEFNAME,TAGUPDATE,FLDRND,SUBFIELD,PDEFVAL,DEFDESC,DEFPARAM)
VALUES ('SE','02','9967','TLTXCD','Mã giao dịch','Mã giao dịch',2,'C','999999','999999',20,'SELECT * FROM (
select  tltxcd VALUECD,tltxcd VALUE, TLTXCD||'':''||txdesc DISPLAY ,en_txdesc EN_DISPLAY,txdesc DESCRIPTION , 1 LSTODR from tltx
UNION ALL
select  ''ALL'' VALUECD, ''ALL'' VALUE,  ''ALL'' DISPLAY , ''ALL'' EN_DISPLAY, ''ALL'' DESCRIPTION , -1 LSTODR  from DUAL
)
ORDER BY LSTODR,VALUECD ',' ',' ','Y','N','Y',' ',' ','Y','C',null,null,null,'TLTXCD','##########',null,null,null,null,'C','N','MAIN',null,null,null,'N','P_TLTXCD','Y',null,'N',null,null,null);
INSERT INTO FLDMASTER (MODCODE,FLDNAME,OBJNAME,DEFNAME,CAPTION,EN_CAPTION,ODRNUM,FLDTYPE,FLDMASK,FLDFORMAT,FLDLEN,LLIST,LCHK,DEFVAL,VISIBLE,DISABLE,MANDATORY,AMTEXP,VALIDTAG,LOOKUP,DATATYPE,INVNAME,FLDSOURCE,FLDDESC,CHAINNAME,PRINTINFO,LOOKUPNAME,SEARCHCODE,SRMODCODE,INVFORMAT,CTLTYPE,RISKFLD,GRNAME,TAGFIELD,TAGVALUE,TAGLIST,TAGQUERY,PDEFNAME,TAGUPDATE,FLDRND,SUBFIELD,PDEFVAL,DEFDESC,DEFPARAM)
VALUES ('SE','01','9967','TXDATE','Ngày suất','Sent date',1,'D','99/99/9999','99/99/9999',10,null,' ',' <$BUSDATE>','Y','N','N',' ',' ','N','D',null,null,null,null,'##########',null,null,null,null,'M','N','MAIN',null,null,null,'N','P_TXDATE','Y',null,'N',null,null,null);
COMMIT;
/
--
--
/
DELETE TLTX WHERE TLTXCD = '9967';
INSERT INTO TLTX (TLTXCD,TXDESC,EN_TXDESC,LIMIT,OFFLINEALLOW,IBT,OVRRQD,LATE,OVRLEV,PRN,LOCAL,CHAIN,DIRECT,HOSTACNO,BACKUP,TXTYPE,NOSUBMIT,DELALLOW,FEEAPP,MSQRQR,VOUCHER,MNEM,MSG_AMT,MSG_ACCT,WITHACCT,ACCTENTRY,BGCOLOR,DISPLAY,BKDATE,ADJALLOW,GLGP,VOUCHERID,CCYCD,RUNMOD,RESTRICTALLOW,REFOBJ,REFKEYFLD,MSGTYPE,CHKBKDATE,CFCUSTODYCD,CFFULLNAME,VISIBLE,CHKSINGLE)
VALUES ('9967','Xuất giao dịch Bravo','Xuất giao dịch Bravo!',0,'Y','Y','Y','0',2,'Y','N','Y','Y',' ','Y','M','1','N','N','N','CF01','AFAPPR',null,'02',' ',null,0,'Y','N','Y','N',null,'##','DB','N',null,null,null,'N','##','##','Y','N');
COMMIT;
/
