DELETE FROM rptfields WHERE objname = 'LN0015';

insert into rptfields (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE)
values ('LN', 'I_DATE', 'LN0015', 'I_DATE', 'Ðến ngày', 'From date', 1, 'M', '99/99/9999', 'dd/MM/yyyy', 10, null, null, '<$BUSDATE>', 'Y', 'N', 'Y', null, null, 'N', 'D', null, null, null, null, null, null, null, null, null, null, null, null, 'Y', null);

insert into rptfields (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE)
values ('LN', 'PV_CUSTODYCD', 'LN0015', 'PV_CUSTODYCD', 'Số TK lưu ký', 'Custody code', 3, 'M', 'cccc.cccccc', '_', 10, null, null, 'ALL', 'Y', 'N', 'N', null, null, 'N', 'C', null, null, null, null, null, null, 'CUSTODYCD_TX', 'CF', null, null, null, null, 'Y', 'T');

insert into rptfields (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE)
values ('LN', 'PV_AFACCTNO', 'LN0015', 'PV_AFACCTNO', 'Số tiểu khoản', 'Sub account', 4, 'M', 'cccc.cccccc', '_', 10, null, null, 'ALL', 'Y', 'N', 'N', null, null, 'N', 'C', null, null, null, null, null, null, 'AFMAST', 'CF', null, null, null, null, 'Y', 'T');

insert into rptfields (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE)
values ('LN', 'PV_RESTYPE', 'LN0015', 'PV_RESTYPE', 'Nguồn cho vay', 'Loan source', 5, 'M', 'cccccccccc', '_', 10, null, null, 'ALL', 'Y', 'N', 'Y', null, null, 'N', 'C', null, null, null, null, null, null, 'RSCTYPE', 'SA', null, null, null, null, 'Y', 'T');

COMMIT;

DELETE FROM rptfields WHERE objname = 'LN0016';

insert into rptfields (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE)
values ('LN', 'F_DATE', 'LN0016', 'F_DATE', 'Từ ngày', 'From date', 1, 'M', '99/99/9999', 'dd/MM/yyyy', 10, null, null, '<$BUSDATE>', 'Y', 'N', 'Y', null, null, 'N', 'D', null, null, null, null, null, null, null, null, null, null, null, null, 'Y', null);

insert into rptfields (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE)
values ('LN', 'T_DATE', 'LN0016', 'T_DATE', 'Ðến ngày', 'To date', 2, 'M', '99/99/9999', 'dd/MM/yyyy', 10, null, null, '<$BUSDATE>', 'Y', 'N', 'Y', null, null, 'N', 'D', null, null, null, null, null, null, null, null, null, null, null, null, 'Y', null);

insert into rptfields (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE)
values ('LN', 'PV_CUSTODYCD', 'LN0016', 'PV_CUSTODYCD', 'Số TK lưu ký', 'Custody code', 3, 'M', 'cccc.cccccc', '_', 10, null, null, 'ALL', 'Y', 'N', 'N', null, null, 'N', 'C', null, null, null, null, null, null, 'CUSTODYCD_TX', 'CF', null, null, null, null, 'Y', 'T');

insert into rptfields (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE)
values ('LN', 'PV_AFACCTNO', 'LN0016', 'PV_AFACCTNO', 'Số tiểu khoản', 'Sub account', 4, 'M', 'cccc.cccccc', '_', 10, null, null, 'ALL', 'Y', 'N', 'N', null, null, 'N', 'C', null, null, null, null, null, null, 'AFMAST', 'CF', null, null, null, null, 'Y', 'T');

insert into rptfields (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE)
values ('LN', 'PV_RESTYPE', 'LN0016', 'PV_RESTYPE', 'Nguồn cho vay', 'Loan source', 5, 'M', 'cccccccccc', '_', 10, null, null, 'ALL', 'Y', 'N', 'Y', null, null, 'N', 'C', null, null, null, null, null, null, 'RSCTYPE', 'SA', null, null, null, null, 'Y', 'T');

COMMIT;
