--
--
/
DELETE APPRULES WHERE APPTYPE = 'OD';
INSERT INTO APPRULES (APPTYPE,RULECD,TBLNAME,FIELD,OPERAND,ERRNUM,ERRMSG,REFID,FLDRND)
VALUES ('OD','10','OOD','OODSTATUS','IN',-200010,'Invalid status','OOD',null);
INSERT INTO APPRULES (APPTYPE,RULECD,TBLNAME,FIELD,OPERAND,ERRNUM,ERRMSG,REFID,FLDRND)
VALUES ('OD','09','ODMAST','VOUCHER','IN',-200010,'Invalid vourcher status','ODMAST',null);
INSERT INTO APPRULES (APPTYPE,RULECD,TBLNAME,FIELD,OPERAND,ERRNUM,ERRMSG,REFID,FLDRND)
VALUES ('OD','08','ODMAST','PRICETYPE','IN',-200010,'Invalid status','ODMAST',null);
INSERT INTO APPRULES (APPTYPE,RULECD,TBLNAME,FIELD,OPERAND,ERRNUM,ERRMSG,REFID,FLDRND)
VALUES ('OD','07','ODMAST','EXECTYPE','IN',-200010,'Invalid status','ODMAST',null);
INSERT INTO APPRULES (APPTYPE,RULECD,TBLNAME,FIELD,OPERAND,ERRNUM,ERRMSG,REFID,FLDRND)
VALUES ('OD','06','ODMAST','EXECAMT','>=',-200010,'Invalid quantity','ODMAST',null);
INSERT INTO APPRULES (APPTYPE,RULECD,TBLNAME,FIELD,OPERAND,ERRNUM,ERRMSG,REFID,FLDRND)
VALUES ('OD','05','ODMAST','REMAINQTTY','>=',-700054,'Invalid quantity','ODMAST',null);
INSERT INTO APPRULES (APPTYPE,RULECD,TBLNAME,FIELD,OPERAND,ERRNUM,ERRMSG,REFID,FLDRND)
VALUES ('OD','04','ODMAST','MATCHTYPE','IN',-200010,'Invalid status','ODMAST',null);
INSERT INTO APPRULES (APPTYPE,RULECD,TBLNAME,FIELD,OPERAND,ERRNUM,ERRMSG,REFID,FLDRND)
VALUES ('OD','03','ODMAST','NORK','IN',-200010,'Invalid status','ODMAST',null);
INSERT INTO APPRULES (APPTYPE,RULECD,TBLNAME,FIELD,OPERAND,ERRNUM,ERRMSG,REFID,FLDRND)
VALUES ('OD','02','ODMAST','EXECTYPE','IN',-200010,'Invalid execute type','ODMAST',null);
INSERT INTO APPRULES (APPTYPE,RULECD,TBLNAME,FIELD,OPERAND,ERRNUM,ERRMSG,REFID,FLDRND)
VALUES ('OD','01','ODMAST','ORSTATUS','IN',-200010,'Invalid status','ODMAST',null);
COMMIT;
/
