CREATE OR REPLACE FUNCTION FN_GEN_DESC_1204(P_DESCCRIPTION VARCHAR2,
                                            P_DCUSTODYCD    VARCHAR2,
                                            P_CCUSTODYCD     VARCHAR2)
  RETURN STRING IS
  V_DESC      VARCHAR2(500);
  V_DCUSTODYCD VARCHAR2(500);
  V_CCUSTODYCD  VARCHAR2(500);
BEGIN
  IF P_DESCCRIPTION IS NULL THEN
    V_DESC := 'Hoàn tất chuyển khoản từ <$88CUSTODYCD> đến <$89CUSTODYCD>';
  ELSE
    V_DESC := NVL(P_DESCCRIPTION,'');
  END IF;
  V_DCUSTODYCD := NVL(P_DCUSTODYCD, '');
  V_CCUSTODYCD  := NVL(P_CCUSTODYCD, '');
  IF LENGTH(REPLACE(V_DCUSTODYCD, '.', '')) = 10 THEN
    V_DESC := REPLACE(V_DESC, '<$88CUSTODYCD>', V_DCUSTODYCD);
  END IF;
   IF LENGTH(REPLACE(V_CCUSTODYCD, '.', '')) = 10 THEN
    V_DESC := REPLACE(V_DESC, '<$89CUSTODYCD>', V_CCUSTODYCD);
  END IF;
  RETURN V_DESC;
EXCEPTION
  WHEN OTHERS THEN
    RETURN 'Hoàn tất chuyển khoản từ 2 tài khoản lưu ký';
END;
