
delete from Searchfld where SEARCHCODE='CF0068';

insert into Searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
values (10, 'custodycd', 'Số LK', 'C', 'CF0068', 100, null, 'LIKE,=', 'N', 'Y', 'Y', 'N', 200, null, 'Description', 'N', '88', null, 'N', null, null, null, 'N');

insert into Searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
values (11, 'FULLNAME', 'Tên khách hàng', 'C', 'CF0068', 150, null, 'LIKE,=', 'N', 'Y', 'Y', 'N', 300, null, 'Description', 'N', '04', null, 'N', null, null, null, 'N');

insert into Searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
values (15, 'PRODUCCODE', 'Mã sản phẩm', 'C', 'CF0068', 100, null, 'LIKE,=', 'N', 'Y', 'Y', 'N', 150, null, 'Description', 'N', '01', null, 'N', null, null, null, 'N');

insert into Searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
values (1, 'TXDATE', 'Ngay', 'C', 'CF0068', 100, null, 'LIKE,=', 'N', 'N', 'N', 'N', 100, null, 'Description', 'N', null, null, 'N', null, null, null, 'N');

insert into Searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
values (3, 'TXNUM', 'STT', 'C', 'CF0068', 100, null, 'LIKE,=', 'N', 'N', 'N', 'N', 100, null, 'Description', 'N', null, null, 'N', null, null, null, 'N');

insert into Searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
values (13, 'AFACCTNO', 'Số tiểu khoản', 'C', 'CF0068', 100, null, 'LIKE,=', 'N', 'Y', 'N', 'N', 150, null, 'Description', 'N', '05', null, 'N', null, null, null, 'N');


commit;

