--
--
/
DELETE RPTFIELDS WHERE OBJNAME = 'SE2000';
INSERT INTO RPTFIELDS (MODCODE,FLDNAME,OBJNAME,DEFNAME,CAPTION,EN_CAPTION,ODRNUM,FLDTYPE,FLDMASK,FLDFORMAT,FLDLEN,LLIST,LCHK,DEFVAL,VISIBLE,DISABLE,MANDATORY,AMTEXP,VALIDTAG,LOOKUP,DATATYPE,INVNAME,FLDSOURCE,FLDDESC,CHAINNAME,PRINTINFO,LOOKUPNAME,SEARCHCODE,SRMODCODE,INVFORMAT,TAGFIELD,TAGLIST,TAGVALUE,ISPARAM,CTLTYPE)
VALUES ('SE','PLSENT','SE2000','PLSENT','Đại diện MSBS','Place sent',3,'M',null,'_',50,'
select varname value, varname valuecd, varvalue || '' - '' || vardesc display, rownum lstord from sysvar where grname = ''REPRESENT'' and varname in (''KBSVREP01'',''KBSVREP02'',''KBSVREP03'') order by rownum
',null,null,'Y','N','Y',null,null,'N','C',null,null,null,null,null,null,null,null,null,null,null,null,'Y','C');
INSERT INTO RPTFIELDS (MODCODE,FLDNAME,OBJNAME,DEFNAME,CAPTION,EN_CAPTION,ODRNUM,FLDTYPE,FLDMASK,FLDFORMAT,FLDLEN,LLIST,LCHK,DEFVAL,VISIBLE,DISABLE,MANDATORY,AMTEXP,VALIDTAG,LOOKUP,DATATYPE,INVNAME,FLDSOURCE,FLDDESC,CHAINNAME,PRINTINFO,LOOKUPNAME,SEARCHCODE,SRMODCODE,INVFORMAT,TAGFIELD,TAGLIST,TAGVALUE,ISPARAM,CTLTYPE)
VALUES ('SE','CFRELATION','SE2000','CFRELATION','UQ khách hàng','Sub account',2,'M','9999.999999','9999.999999',30,null,null,' ','Y','N','N',null,null,'N','C',null,null,null,null,'##########',null,null,null,null,'CUSTODYCD','SELECT FILTERCD, VALUE,  VALUECD, DISPLAY, EN_DISPLAY,  DESCRIPTION FROM VW_CFRELATION_SUBACCOUNT WHERE FILTERCD=''<$TAGFIELD>''
UNION ALL
SELECT ''NOT'' FILTERCD,''NOT'' VALUE, ''NOT'' VALUECD,''Không sử dụng UQ'' DISPLAY,''NULL'' EN_DISPLAY, ''Không sử dụng UQ'' DESCRIPTION FROM DUAL
',null,'Y','C');
INSERT INTO RPTFIELDS (MODCODE,FLDNAME,OBJNAME,DEFNAME,CAPTION,EN_CAPTION,ODRNUM,FLDTYPE,FLDMASK,FLDFORMAT,FLDLEN,LLIST,LCHK,DEFVAL,VISIBLE,DISABLE,MANDATORY,AMTEXP,VALIDTAG,LOOKUP,DATATYPE,INVNAME,FLDSOURCE,FLDDESC,CHAINNAME,PRINTINFO,LOOKUPNAME,SEARCHCODE,SRMODCODE,INVFORMAT,TAGFIELD,TAGLIST,TAGVALUE,ISPARAM,CTLTYPE)
VALUES ('SE','CUSTODYCD','SE2000','CUSTODYCD','Số TK lưu ký','Custody code',1,'M','cccc.cccccc','cccc.cccccc',10,null,null,null,'Y','N','Y',null,null,'N','C',null,null,null,'CUSTODYCD','##########',null,'CUSTODYCD_CF','CF',null,null,null,null,'Y','T');
INSERT INTO RPTFIELDS (MODCODE,FLDNAME,OBJNAME,DEFNAME,CAPTION,EN_CAPTION,ODRNUM,FLDTYPE,FLDMASK,FLDFORMAT,FLDLEN,LLIST,LCHK,DEFVAL,VISIBLE,DISABLE,MANDATORY,AMTEXP,VALIDTAG,LOOKUP,DATATYPE,INVNAME,FLDSOURCE,FLDDESC,CHAINNAME,PRINTINFO,LOOKUPNAME,SEARCHCODE,SRMODCODE,INVFORMAT,TAGFIELD,TAGLIST,TAGVALUE,ISPARAM,CTLTYPE)
VALUES ('SE','I_DATE','SE2000','I_DATE','Ngày giao dịch','On date',0,'M','99/99/9999','dd/MM/yyyy',10,null,null,'<$BUSDATE>','Y','N','Y',null,null,'N','D',null,null,null,null,null,null,null,null,null,null,null,null,'Y',null);
COMMIT;
/
