--
--
/
DELETE PRCHK WHERE TLTXCD = '2682';
INSERT INTO PRCHK (TLTXCD,CHKTYPE,TYPE,TYPEID,BRIDTYPE,PRTYPE,ACCFLDCD,TYPEFLDCD,DORC,AMTEXP,ODRNUM,UDPTYPE,DELTD,LNACCFLDCD,LNTYPEFLDCD)
VALUES ('2682','L','AFTYPE','04','0','R','06',null,'C','81++82++83++84','0','I','N',null,null);
COMMIT;
/
