--
--
/
DELETE PRCHK WHERE TLTXCD = '2643';
INSERT INTO PRCHK (TLTXCD,CHKTYPE,TYPE,TYPEID,BRIDTYPE,PRTYPE,ACCFLDCD,TYPEFLDCD,DORC,AMTEXP,ODRNUM,UDPTYPE,DELTD,LNACCFLDCD,LNTYPEFLDCD)
VALUES ('2643','L','AFTYPE','05','0','R','06',null,'C','10','0','I','N',null,null);
COMMIT;
/
