--
--
/
DELETE PRCHK WHERE TLTXCD = '2647';
INSERT INTO PRCHK (TLTXCD,CHKTYPE,TYPE,TYPEID,BRIDTYPE,PRTYPE,ACCFLDCD,TYPEFLDCD,DORC,AMTEXP,ODRNUM,UDPTYPE,DELTD,LNACCFLDCD,LNTYPEFLDCD)
VALUES ('2647','L','AFTYPE','05','0','R','06',null,'C','91++92++93++94','0','I','N',null,null);
COMMIT;
/
