--
--
/
DELETE hft_mapper WHERE BPS_FUNCTION = 'SAVE_AUTO_EXECUTE_PLAN';
INSERT INTO HFT_MAPPER (BPS_FUNCTION,BPS_KEY_FIELD,FO_FIELD,FO_FIELD_TYPE,RETURN_ID,FO_URL,REQUEST_TYPE,FO_IDX_TABLE,BPS_ACCOUNT_TYPE,BPS_ACCOUNT)
VALUES ('SAVE_AUTO_EXECUTE_PLAN',null,'MSGTYPE','VARCHAR','fe7011',null,null,null,'','');
COMMIT;
/
