--
--
/
DELETE APPTX WHERE APPTYPE = 'PR';
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('PR','0004','U','C','PRINUSED','N',null,null,null,null,'PRMASTER','PRTRAN','0');
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('PR','0003','U','D','PRINUSED','N',null,null,null,null,'PRMASTER','PRTRAN','0');
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('PR','0002','U','C','PRLIMIT','N',null,null,null,null,'PRMASTER','PRTRAN','0');
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('PR','0001','U','D','PRLIMIT','N',null,null,null,null,'PRMASTER','PRTRAN','0');
COMMIT;
/
