--
--
/
DELETE APPTX WHERE APPTYPE = 'GR';
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0034','U','U','INTDT','D',null,null,null,null,'GRMAST',null,null);
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0033','U','U','OPNDATE','D',null,null,null,null,'GRMAST',null,null);
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0032','U','U','CLSDATE','D',null,null,null,null,'GRMAST',null,null);
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0031','U','U','EXPDATE','D',null,null,null,null,'GRMAST',null,null);
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0030','U','U','LASTDATE','D',null,null,null,null,'GRMAST',null,null);
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0019','U','C','FEEAMT','N',null,null,null,null,'GRMAST','GRTRAN','0');
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0018','U','C','INTACR','N',null,null,null,null,'GRMAST','GRTRAN','4');
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0017','U','D','INTACR','N',null,null,null,null,'GRMAST','GRTRAN','4');
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0016','U','C','GRAMT','N',null,null,null,null,'GRMAST','GRTRAN','0');
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0015','U','D','GRAMT','N',null,null,null,null,'GRMAST','GRTRAN','0');
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0014','U','C','SECUREDAMT','N',null,null,null,null,'GRMAST','GRTRAN','0');
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0013','U','D','SECUREDAMT','N',null,null,null,null,'GRMAST','GRTRAN','0');
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0012','U','C','BALANCE','N',null,null,null,null,'GRMAST','GRTRAN','0');
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0011','U','D','BALANCE','N',null,null,null,null,'GRMAST','GRTRAN','0');
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0010','U','D','FEEAMT','N',null,null,null,null,'GRMAST','GRTRAN','0');
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0003','U','U','GRRATIO','N',null,null,null,null,'GRMAST','GRTRAN','4');
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0002','U','U','BALANCE','N',null,null,null,null,'GRMAST','GRTRAN','0');
INSERT INTO APPTX (APPTYPE,TXCD,TXUPDATE,TXTYPE,FIELD,FLDTYPE,OFILE,OFILEACT,IFILE,INTF,TBLNAME,TRANF,FLDRND)
VALUES ('GR','0001','U','U','STATUS','C',null,null,null,null,'GRMAST','GRTRAN',null);
COMMIT;
/
