--
--
/
DELETE SYSVAR WHERE VARNAME = 'PRICELIMIT_UPCOM';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','PRICELIMIT_UPCOM','15','Biên độ dao động giá sàn UPCOM','Bien do dao dong gia san UPCOM','Y');
COMMIT;
/
