--
--
/
DELETE SYSVAR WHERE VARNAME = 'HOSTC_TRADE_UNIT';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','HOSTC_TRADE_UNIT','10','TRADE UNIT CUA SAN HCM',null,'N');
COMMIT;
/
