--
--
/
DELETE SYSVAR WHERE VARNAME = 'HASTC_TRADE_UNIT';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','HASTC_TRADE_UNIT','1','TRADE UNIT CUA SAN HN',null,'N');
COMMIT;
/
