--
--
/
DELETE SYSVAR WHERE VARNAME = 'NAV-OVD';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','NAV-OVD','-1','Tham số chặn NAV/(Nợ - Tiền)','Tham số chặn NAV/(Nợ - Tiền)','Y');
COMMIT;
/
