--
--
/
DELETE SYSVAR WHERE VARNAME = 'TRADEBUYSELL';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','TRADEBUYSELL','N','Neu Y thi khong chan doi ung khi dat lenh vao GW',null,'N');
COMMIT;
/
