--
--
/
DELETE SYSVAR WHERE VARNAME = 'T0CUSTLIMIT';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('MARGIN','T0CUSTLIMIT','0','Hạn mức cấp bảo lãnh tự động tối đa 1 tiểu khoản 1 ngày','T0CUSTLIMIT','Y');
COMMIT;
/
