--
--
/
DELETE SYSVAR WHERE VARNAME = 'UPCOM_MAXBREAKSIZE_CNT';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','UPCOM_MAXBREAKSIZE_CNT','2000','Số lệnh tách tối đa','UPCOM: Maximum order break size','N');
COMMIT;
/
