--
--
/
DELETE SYSVAR WHERE VARNAME = 'QUOTE_DES_FOLDER';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','QUOTE_DES_FOLDER','C:\QUOTE_DES_FOLDER',null,null,'N');
COMMIT;
/
