--
--
/
DELETE SYSVAR WHERE VARNAME = 'MESSDF1005TITLE';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','MESSDF1005TITLE','MESSDF1005TITLE','ThÃ´ng bÃ¡o khoáº£n vay quÃ¡ háº¡n !','ThÃ´ng bÃ¡o khoáº£n vay quÃ¡ háº¡n !','N');
COMMIT;
/
