--
--
/
DELETE SYSVAR WHERE VARNAME = 'FEE_RATE';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','FEE_RATE','0','Tỉ lệ giảm do phí','Tỉ lệ giảm do phí','Y');
COMMIT;
/
