--
--
/
DELETE SYSVAR WHERE VARNAME = 'INTERVAL_MARKET_INFO';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','INTERVAL_MARKET_INFO','40000',null,null,'N');
COMMIT;
/
