--
--
/
DELETE SYSVAR WHERE VARNAME = 'VSDMOD';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','VSDMOD','A','A - Auto, M - Manual','A - Auto, M - Manual','N');
COMMIT;
/
