--
--
/
DELETE SYSVAR WHERE VARNAME = 'UPCOM_MINBREAKSIZE_QTTY';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','UPCOM_MINBREAKSIZE_QTTY','1000','Khối lượng tách lệnh tối thiểu','UPCOM: Minimum quantiy break size','N');
COMMIT;
/
