--
--
/
DELETE SYSVAR WHERE VARNAME = 'ONLINEMINREMAINTRF1120_AMT';
INSERT INTO SYSVAR (GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW)
VALUES ('SYSTEM','ONLINEMINREMAINTRF1120_AMT','0','So tien chuyen khoan noi bo con lai toi thieu','So tien chuyen khoan noi bo con lai toi thieu','N');
COMMIT;
/
