

DELETE FROM FLDMASTER WHERE OBJNAME = '0018' AND FLDNAME in ('02');
INSERT INTO FLDMASTER (MODCODE,FLDNAME,OBJNAME,DEFNAME,CAPTION,EN_CAPTION,ODRNUM,FLDTYPE,FLDMASK,FLDFORMAT,FLDLEN,LLIST,LCHK,DEFVAL,VISIBLE,DISABLE,MANDATORY,AMTEXP,VALIDTAG,LOOKUP,DATATYPE,INVNAME,FLDSOURCE,FLDDESC,CHAINNAME,PRINTINFO,LOOKUPNAME,SEARCHCODE,SRMODCODE,INVFORMAT,CTLTYPE,RISKFLD,GRNAME,TAGFIELD,TAGVALUE,TAGLIST,TAGQUERY,PDEFNAME,TAGUPDATE,FLDRND,SUBFIELD,PDEFVAL,DEFDESC,DEFPARAM)
VALUES ('CF','02','0018','SBTYPE','Loại lịch','Calender Type',4,'C',' ',' ',25,'SELECT CDVAL VALUECD, CDVAL VALUE, CDCONTENT DISPLAY, CDCONTENT EN_DISPLAY, CDCONTENT DESCRIPTION FROM ALLCODE WHERE CDNAME=''CLEARCD'' AND cdtype = ''FO'' ORDER BY LSTODR',' ',' ','Y','N','Y',' ',' ','N','C',null,null,null,null,'##########',null,null,null,null,'C','N','MAIN','01','[MAS10]',null,'N',null,'Y',null,'N',null,null,null);
COMMIT;
