--
--
/
DELETE ALLCODE WHERE CDNAME = 'RERFTYPE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('RE','RERFTYPE','0003','Phí hệ thống',3,'Y','Phí hệ thống');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('RE','RERFTYPE','0002','Phí quản lý',2,'Y','Phí quản lý');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('RE','RERFTYPE','0001','Phí sở giao dịch',1,'Y','Phí sở giao dịch');
COMMIT;
/
