--
--
/
DELETE ALLCODE WHERE CDNAME = 'RPMAST';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','RPMAST','015','CAOWNER',14,'Y','CAOWNER');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','RPMAST','014','TRTYPE',13,'Y','TRTYPE');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','RPMAST','013','Bán kỳ hạn',12,'Y','Bán kỳ hạn');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','RPMAST','012','Mua kỳ hạn',11,'Y','Mua kỳ hạn');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','RPMAST','011','KL kỳ hạn',10,'Y','KL kỳ hạn');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','RPMAST','010','Ngày kỳ hạn',9,'Y','Ngày kỳ hạn');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','RPMAST','009','Bán giao ngay',8,'Y','Bán giao ngay');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','RPMAST','008','Mua giao ngay',7,'Y','Mua giao ngay');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','RPMAST','007','KL giao ngay',6,'Y','KL giao ngay');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','RPMAST','006','Hệ số giao ngay',5,'Y','Hệ số giao ngay');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','RPMAST','005','Ngày GD cuối',4,'Y','Ngày GD cuối');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','RPMAST','004','Ngày kỳ hạn',3,'Y','Ngày kỳ hạn');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','RPMAST','003','Ngày giao ngay',2,'Y','Ngày giao ngay');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','RPMAST','002','Ngày mở',1,'Y','Ngày mở');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('IC','RPMAST','001','Trạng thái',0,'Y','Trạng thái');
COMMIT;
/
