--
--
/
DELETE ALLCODE WHERE CDNAME = 'EVENTCODE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('CI','EVENTCODE','CRI','Tính lãi cộng dồn',0,'Y','Tính lãi cộng dồn');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('CI','EVENTCODE','ODI','Lãi nhập gốc',0,'Y','Lãi nhập gốc');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','EVENTCODE','DBF','Debeate trading fee',0,'Y','Debeate trading fee');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','EVENTCODE','TFE','Phí GD',0,'Y','Phí GD');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('RP','EVENTCODE','IAC','Lãi cộng dồn',0,'Y','Lãi cộng dồn');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SE','EVENTCODE','DPF','Phí lưu ký',0,'Y','Phí lưu ký');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SE','EVENTCODE','ACP','Giá trung bình',0,'Y','Giá trung bình');
COMMIT;
/
