--
--
/
DELETE ALLCODE WHERE CDNAME = 'REJECTCD';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','REJECTCD','003','Vượt quá giới hạn',2,'Y','Vượt quá giới hạn');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','REJECTCD','002','Không đủ KL',1,'Y','Không đủ KL');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','REJECTCD','001','Không rõ ng.nhân',0,'Y','Không rõ ng.nhân');
COMMIT;
/
