--
--
/
DELETE ALLCODE WHERE CDNAME = 'RIGHTTYPE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','RIGHTTYPE','T','Giao dịch',2,'N','Transaction');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','RIGHTTYPE','R','Báo cáo',1,'N','Report');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','RIGHTTYPE','M','Chức năng',0,'N','Function');
COMMIT;
/
