--
--
/
DELETE allcode WHERE cdtype = 'OD' AND cdname = 'TARGETSTRATEGY';
INSERT INTO ALLCODE (CDTYPE, CDNAME, CDVAL, CDCONTENT, LSTODR, CDUSER, EN_CDCONTENT)
VALUES ('OD', 'TARGETSTRATEGY', '0', 'DMA', 1, 'Y', 'DMA');
INSERT INTO ALLCODE (CDTYPE, CDNAME, CDVAL, CDCONTENT, LSTODR, CDUSER, EN_CDCONTENT)
VALUES ('OD', 'TARGETSTRATEGY', '1', 'VWAP', 2, 'Y', 'VWAP');
INSERT INTO ALLCODE (CDTYPE, CDNAME, CDVAL, CDCONTENT, LSTODR, CDUSER, EN_CDCONTENT)
VALUES ('OD', 'TARGETSTRATEGY', '2', 'TWAP', 3, 'Y', 'TWAP');
INSERT INTO ALLCODE (CDTYPE, CDNAME, CDVAL, CDCONTENT, LSTODR, CDUSER, EN_CDCONTENT)
VALUES ('OD', 'TARGETSTRATEGY', '3', 'CARE', 4, 'Y', 'CARE');
COMMIT;
/
