DELETE ALLCODE WHERE CDNAME = 'DESCOUTSTANDING';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('FO','DESCOUTSTANDING','S','Bậc thang',1,'Y','Progressive IR');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('FO','DESCOUTSTANDING','F','Lãi suất linh hoạt',2,'Y','Flexible IR');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('FO','DESCOUTSTANDING','N',' ',3,'Y',' ');
COMMIT;
/
