--
--
/
DELETE ALLCODE WHERE CDNAME = 'TYPEDATE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','TYPEDATE','002','Ngày hiệu lực',1,'Y','Ngày hiệu lực');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('OD','TYPEDATE','001','Ngày giao dịch',0,'Y','Ngày giao dịch');
COMMIT;
/
