--
--
/
DELETE ALLCODE WHERE CDNAME = 'TDSRC';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('TD','TDSRC','O','Khác',2,'Y','Customer account');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('TD','TDSRC','B','Ngân hàng',1,'Y','Bank');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('TD','TDSRC','C','Công ty',0,'Y','Company');
COMMIT;
/
