--
--
/
DELETE ALLCODE WHERE CDNAME = 'DEALTYPE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('DF','DEALTYPE','T','Tiền CA chờ về',3,'Y','Tiền CA chờ về');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('DF','DEALTYPE','P','CK Quyền chờ về',3,'Y','CK Quyền chờ về');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('DF','DEALTYPE','R','CK chờ về',2,'Y','CK chờ về');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('DF','DEALTYPE','B','CK hạn chế CN',1,'Y','CK hạn chế CN');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('DF','DEALTYPE','N','CK giao dịch',0,'Y','CK giao dịch');
COMMIT;
/
