--
--
/
DELETE ALLCODE WHERE CDNAME = 'VISIBLE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','VISIBLE','N','Không',1,'Y','Không');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','VISIBLE','Y','Có',0,'Y','Có');
COMMIT;
/
