--
--
/
DELETE ALLCODE WHERE CDNAME = 'RATEOPCD';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','RATEOPCD','%','Percentage',1,'Y','Percentage');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','RATEOPCD','-','Minus',1,'Y','Minus');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','RATEOPCD','+','Plus',0,'Y','Plus');
COMMIT;
/
