--
--
/
DELETE ALLCODE WHERE CDNAME = 'BANKPAIDMETHOD';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','BANKPAIDMETHOD','P','Trả lãi NH khi KH trả gốc',2,'Y','Trả lãi NH khi KH trả gốc');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','BANKPAIDMETHOD','A','Trả lãi NH khi KH tất toán',1,'Y','Trả lãi NH khi KH tất toán');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('LN','BANKPAIDMETHOD','I','Trả lãi NH ngay khi thu KH',0,'Y','Trả lãi NH ngay khi thu KH');
COMMIT;
/
