--
--
/
DELETE ALLCODE WHERE CDNAME = 'OVRSTS';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','OVRSTS','2','Cần checker 2 duyệt',2,'Y','Cần checker 2 duyệt');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','OVRSTS','1','Cần checker 1 duyệt',1,'Y','Cần checker 1 duyệt');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','OVRSTS','0','Đã duyệt',0,'Y','Đã duyệt');
COMMIT;
/
