--
--
/
DELETE ALLCODE WHERE CDNAME = 'VSDTITLE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','VSDTITLE','003','Chưa xác định',2,'Y','Chưa xác định');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','VSDTITLE','002','Nữ',1,'Y','MRSS');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','VSDTITLE','001','Nam',0,'Y','SIRR');
COMMIT;
/
