--
--
/
DELETE ALLCODE WHERE CDNAME = 'DATATYPE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','DATATYPE','N','Số',2,'Y','Số');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','DATATYPE','D','Ngày',1,'Y','Ngày');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','DATATYPE','C','Ký tự',0,'Y','Ký tự');
COMMIT;
/
