--
--
/
DELETE ALLCODE WHERE CDNAME = 'CDUSER';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','CDUSER','N','Không',1,'Y','Không');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SA','CDUSER','Y','Có',0,'Y','Có');
COMMIT;
/
