--
--
/
DELETE ALLCODE WHERE CDNAME = 'TEMPLATE_TYPE';
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','TEMPLATE_TYPE','E','Thư điện tử',2,'Y','Email');
INSERT INTO ALLCODE (CDTYPE,CDNAME,CDVAL,CDCONTENT,LSTODR,CDUSER,EN_CDCONTENT)
VALUES ('SY','TEMPLATE_TYPE','S','Tin nhắn SMS',1,'Y','SMS');
COMMIT;
/
