--
--
/
DELETE RPTMASTER WHERE RPTID = 'ODER03';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('ODER03','HOST','OD','12','5','5','60','5','5','HOÀN TRẢ ỨNG TRƯỚC TIỀN BÁN LỆNH BÁN LỖI (8842)','Y',1,'1','P','ODER03','Y','A','N','V','N','N','M','000','S',-1,'Revert Advance Payment of error order (8842)',null,'0','0','0','0','N','N','Y');
COMMIT;
/
