--
--
/
DELETE RPTMASTER WHERE RPTID = 'SA0010';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('SA0010','HOST','SA','12','5','5','60','5','5','TOP BRK CÓ GIÁ TRỊ GIAO DỊCH LỚN NHẤT','Y',1,'1','L','SA0010','Y','S','N','R','N','N','M','000','S',-1,'TOP BRK CÓ GIÁ TRỊ GIAO DỊCH LỚN NHẤT',null,'0','0','0','0','N','N','Y');
COMMIT;
/
