--
--
/
DELETE RPTMASTER WHERE RPTID = 'OD8811';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('OD8811','HOST','OD','12','5','5','60','5','5','DANH SÁCH LỆNH MUA CHƯA GỬI LÊN SÀN CHỜ GIẢI TỎA (GIAO DỊCH 8811)','Y',1,'1','P','OD8811','Y','B','N','V','N','N','M','000','S',-1,'View release secured buy sending order(wait for 8811)',null,'0','0','0','0','N','N','Y');
COMMIT;
/
