--
--
/
DELETE RPTMASTER WHERE RPTID = 'SA0005';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('SA0005','HOST','SA','12','5','5','60','5','5','BÁO CÁO CHI TIẾT GIAO DỊCH CHUYỂN KHOẢN RA NGÂN HÀNG','Y',1,'1','P','SA0005','Y','S','N','R','N','N','M','000','S',-1,'Báo cáo chi tiết giao dịch chuyển khoản ra ngân hàng',null,'0','0','0','0','N','N','Y');
COMMIT;
/
