--
--
/
DELETE RPTMASTER WHERE RPTID = 'RM1003';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('RM1003','HOST','RM','12','5','5','60','5','5','DANH SÁCH TIỂU KHOẢN CẦN PHONG TOẢ BỔ XUNG THU PHÍ LƯU KÝ (6640)','Y',1,'1','P','RM1003','Y','A','N','V','N','N','M','000','S',-1,'View account must hold to transfer se fee (6640)',null,'0','0','0','0','N','N','Y');
COMMIT;
/
