--
--
/
DELETE RPTMASTER WHERE RPTID = 'OD9905';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('OD9905','HOST','OD','12','5','5','60','5','5','KSNB: SỔ LỆNH GIAO DỊCH','Y',1,'1','L','OD9905','N','S','N','R','N','N','M','000','S',-1,'Sổ lệnh giao dịch',null,'0','0','0','0','N','N','Y');
COMMIT;
/
