--
--
/
DELETE RPTMASTER WHERE RPTID = 'OD1009';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('OD1009','HOST','OD','12','5','5','60','5','5','BÁO CÁO TỔNG HỢP PHÍ VÀ THUẾ TNCN','Y',1,'1','P','OD1009','Y','S','N','R','N','N','M','000','S',-1,'Báo cáo tổng hợp phí và thuế tncn',null,'0','0','0','0','N','N','Y');
COMMIT;
/
