--
--
/
DELETE RPTMASTER WHERE RPTID = 'OD9904';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('OD9904','HOST','OD','12','5','5','60','5','5','BÁO CÁO DOANH SỐ CAREBY CTV','Y',1,'1','P','OD9904','N','S','N','R','N','Y','M','000','S',-1,'Báo cáo doanh s? careby CTV',null,'0','0','0','0','N','N','Y');
COMMIT;
/
