--
--
/
DELETE RPTMASTER WHERE RPTID = 'OD0055';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('OD0055','HOST','OD','12','5','5','60','5','5','BÁO CÁO SỔ LỆNH THEO CHI NHANH','Y',1,'1','L','OD0055','N','S','N','R','N','N','M','000','S',-1,'Bo co GDCK theo lo?i CK kim b?ng k ph mi gi?i pht sinh',null,'0','0','0','0','N','N','Y');
COMMIT;
/
