--
--
/
DELETE RPTMASTER WHERE RPTID = 'ODPTRP';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('ODPTRP','HOST','OD','12','5','5','60','5','5','DANH SÁCH LỆNH THỎA THUẬN REPO','Y',1,'1','P','ODPTRP','Y','B','N','V','N','N','M','000','S',-1,'Danh sách các lệnh thỏa thuận Repo',null,'0','0','0','0','N','N','Y');
COMMIT;
/
