--
--
/
DELETE RPTMASTER WHERE RPTID = 'TD0005';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('TD0005','HOST','TD','12','5','5','60','5','5','SAO KE TRANG THAI (KHONG CHAN CAREBY)','Y',1,'1','P',null,'Y','B','N','V','N','N','M','0  ','S',-1,'Sao ke trang thai (khong chan careby)',null,'0','0','0','0','N','N','Y');
COMMIT;
/
