--
--
/
DELETE RPTMASTER WHERE RPTID = 'SE9990';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('SE9990','HOST','SE','12','5','5','60','5','5','THÔNG TIN CHỨNG KHOÁN QUYỀN CHỜ BÁN','Y',1,'1','P','SE2242','Y','A','N','V','N','N','M','000','S',-1,'Thông tin chứng khoán quyền chờ bán',null,'0','0','0','0','N','N','Y');
COMMIT;
/
