--
--
/
DELETE RPTMASTER WHERE RPTID = 'RM6661';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('RM6661','HOST','RM','12','5','5','60','5','5','DANH SÁCH CÁC LỆNH ĐÃ GIẢI TOẢ CHỜ XÁC NHẬN (6661)','Y',1,'1','P','RM6661','Y','B','N','V','N','N','M','000','S',-1,'View unhold request waiting to complete',null,'0','0','0','0','N','N','Y');
COMMIT;
/
