--
--
/
DELETE rptmaster WHERE rptid = 'CF0029';
insert into rptmaster (RPTID, DSN, MODCODE, FONTSIZE, RHEADER, PHEADER, RDETAIL, PFOOTER, RFOOTER, DESCRIPTION, AD_HOC, RORDER, PSIZE, ORIENTATION, STOREDNAME, VISIBLE, AREA, ISLOCAL, CMDTYPE, ISCAREBY, ISPUBLIC, ISAUTO, ORD, AORS, ROWPERPAGE, EN_DESCRIPTION, STYLECODE, TOPMARGIN, LEFTMARGIN, RIGHTMARGIN, BOTTOMMARGIN, SUBRPT, ISCMP, ISDEFAULTDB)
values ('CF0029', 'HOST', 'CF', '12', '5', '5', '60', '5', '5', 'TRA CỨU HẠN MỨC CHUYỂN TIỀN RIÊNG CỦA KH', 'Y', 1, '1', 'P', 'CF0029', 'Y', 'B', 'N', 'V', 'N', 'N', 'M', '000', 'S', -1, 'LOOK UP YOUR OWN TRANSFER LIMIT', null, 0, 0, 0, 0, 'N', 'N', 'Y');
COMMIT;
/
