--
--
/
DELETE RPTMASTER WHERE RPTID = 'CA0009';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('CA0009','HOST','CA','12','5','5','60','5','5','GIẤY ĐĂNG KÝ MUA CHỨNG KHOÁN','Y',1,'1','L','CA0009','N','S','N','R','N','N','M','000','S',-1,'GIẤY ĐĂNG KÝ MUA CHỨNG KHOÁN',null,'0','0','0','0','N','N','Y');
COMMIT;
/
