--
--
/
DELETE RPTMASTER WHERE RPTID = 'RM0047';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('RM0047','HOST','RM','12','5','5','60','5','5','BẢNG KÊ CHUYỂN KHOẢN GIẢM TIỀN KH','Y',1,'1','P','RM0047','Y','A','N','R','N','Y','M','000','S',-1,'Bảng kê chuyển khoản giảm tiền KH',null,'0','0','0','0','N','N','Y');
COMMIT;
/
