--
--
/
DELETE RPTMASTER WHERE RPTID = 'SE2277';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('SE2277','HOST','SE','12','5','5','60','5','5','TẠO CHỨNG KHOÁN CHỜ GIAO DỊCH','Y',1,'1','P','SE2277','Y','A','N','V','N','N','M','000','S',-1,'Waiting for trade',null,'0','0','0','0','N','N','Y');
COMMIT;
/
