--
--
/
DELETE RPTMASTER WHERE RPTID = 'CF0008';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('CF0008','HOST','CF','12','5','5','60','5','5','BÁO CÁO ĐÓNG MỞ TIỂU KHOẢN','Y',1,'1','L','CF0008','Y','S','N','R','N','N','M','000','S',-1,'Báo cáo đóng mở tiểu khoản',null,'0','0','0','0','N','N','Y');
COMMIT;
/
