--
--
/
DELETE RPTMASTER WHERE RPTID = 'SE2231';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('SE2231','HOST','SE','12','5','5','60','5','5','TTLK TỪ CHỐI HỒ SƠ LƯU KÝ (GIAO DỊCH 2231)','Y',1,'1','P','SE9020','Y','B','N','V','N','N','M','000','S',-1,'View pending to revert send depository center (wait for 2231)',null,'0','0','0','0','N','N','Y');
COMMIT;
/
