--
--
/
DELETE RPTMASTER WHERE RPTID = 'SE2205';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('SE2205','HOST','SE','12','5','5','60','5','5','MÀN HÌNH THEO DÕI SỐ DƯ CHỨNG KHOÁN THEO SỐ LƯU KÝ','Y',1,'1','P','SE2205','Y','A','N','V','N','N','M','000','S',-1,'View the securities by custody code',null,'0','0','0','0','N','N','Y');
COMMIT;
/
