--
--
/
DELETE RPTMASTER WHERE RPTID = 'CF1111';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('CF1111','HOST','CF','12','5','5','60','5','5','HỢP ĐỒNG MỞ TÀI KHOẢN GIAO DỊCH CHỨNG KHOÁN (TỔ CHỨC)','Y',1,'1','L','CF1111','Y','S','N','R','N','N','M','000','S',-1,'Hợp đồng mở tài khoản giao dịch chứng khoán (Tổ chức)',null,'0','0','0','0','N','N','Y');
COMMIT;
/
