--
--
/
DELETE RPTMASTER WHERE RPTID = 'GR5079';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('GR5079','HOST','GR','12','5','5','60','5','5','HỢP DỒNG BẢO LÃNH CHỜ ĐÓNG','Y',1,'1','P','GR9002','Y','B','N','V','N','N','M','000','S',-1,'View guarantee contract ready to close',null,'0','0','0','0','N','N','Y');
COMMIT;
/
