--
--
/
DELETE RPTMASTER WHERE RPTID = 'SEBK92';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('SEBK92','HOST','SE','12','5','5','60','5','5','TẠO BẢNG KÊ YÊU CẦU RÚT LƯU KÝ CHỨNG KHOÁN','Y',1,'1','P','SEBK31','Y','B','N','V','N','N','M','000','S',-1,'Create list of request to withdraw securties send to depository center',null,'0','0','0','0','N','N','Y');
COMMIT;
/
