--
--
/
DELETE RPTMASTER WHERE RPTID = 'CA0003';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('CA0003','HOST','CA','12','5','5','60','5','5','BÁO CÁO TRẢ CỔ TỨC BẰNG CỔ PHIẾU','Y',1,'1','L','CA0003','Y','S','N','R','N','N','M','000','S',-1,'Báo cáo trả cổ tức bằng cổ phiếu',null,'0','0','0','0','N','N','Y');
COMMIT;
/
