--
--
/
DELETE RPTMASTER WHERE RPTID = 'SY4000';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('SY4000','HOST','SY','12','5','5','60','5','5','Quản lý thông tin user-pass GDTT (HAGW)','Y',1,'1','P','SY4000','Y','B','N','V','N','N','M','000','S',-1,'Manage user-pass onlinetraing',null,'0','0','0','0','N','N','Y');
COMMIT;
/
