--
--
/
DELETE RPTMASTER WHERE RPTID = 'CI0006';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('CI0006','HOST','CI','12','5','5','60','5','5','UỶ NHIỆM CHI','Y',1,'1','P','CI0006','Y','S','N','R','N','N','M','000','S',-1,'UỶ NHIỆM CHI',null,'0','0','0','0','N','N','Y');
COMMIT;
/
