--
--
/
DELETE RPTMASTER WHERE RPTID = 'SE0041';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('SE0041','HOST','SE','12','5','5','60','5','5','YÊU CẦU CHUYỂN KHOẢN CHỨNG KHOÁN (15A/LK)','Y',1,'1','L','SE0041','Y','S','N','R','N','N','M','000','S',-1,'Yêu cầu chuyển khoản chứng khoán (15A/LK) ',null,'0','0','0','0','N','N','Y');
COMMIT;
/
