--
--
/
DELETE RPTMASTER WHERE RPTID = 'SE0018';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('SE0018','HOST','SE','12','5','5','60','5','5','BÁO CÁO SỐ DƯ CHỨNG KHOÁN CẦM CỐ THEO TỪNG MÃ CHỨNG KHOÁN','Y',1,'1','L','SE0018','N','S','N','R','N','N','M','000','S',-1,'Báo cáo số dư chứng khoán cầm cố theo từng mã chứng khoán',null,'0','0','0','0','N','N','Y');
COMMIT;
/
