--
--
/
DELETE RPTMASTER WHERE RPTID = 'CA3392';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('CA3392','HOST','CA','12','5','5','60','5','5','HỦY CHUYỂN KHOẢN NỘI BỘ QUYỀN MUA (GIAO DỊCH 3392)','Y',1,'1','P','CA3392','Y','A','N','V','N','N','M','000','S',-1,'Cancel Transfer',null,'0','0','0','0','N','N','Y');
COMMIT;
/
