--
--
/
DELETE RPTMASTER WHERE RPTID = 'OD0090';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('OD0090','HOST','OD','12','5','5','60','5','5','BẢNG KÊ KHỚP LỆNH BÁN CHỨNG KHOÁN','Y',1,'1','L','OD0090','Y','S','N','R','N','N','M','000','S',-1,'BẢNG KÊ KHỚP LỆNH BÁN CHỨNG KHOÁN',null,'0','0','0','0','N','N','Y');
COMMIT;
/
