--
--
/
DELETE RPTMASTER WHERE RPTID = 'CFTD04';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('CFTD04','HOST','CF','12','5','5','60','5','5','BÁO CÁO P CÁC KHÁCH HÀNG','Y',1,'1','L','CFTD04','N','S','N','R','N','N','M','000','S',-1,'Báo cáo P cac khách hàng',null,'0','0','0','0','N','N','Y');
COMMIT;
/
