--
--
/
DELETE RPTMASTER WHERE RPTID = 'SE2292';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('SE2292','HOST','SE','12','5','5','60','5','5','GHI NHẬN HỒ SƠ RÚT CHỨNG KHOÁN ĐÃ ĐƯỢC GỬI LÊN TRUNG TÂM (GIAO DỊCH 2292)','Y',1,'1','P','SE2205','Y','B','N','V','N','N','M','000','S',-1,'Record 2200 (wait for 2292)',null,'0','0','0','0','N','N','Y');
COMMIT;
/
