--
--
/
DELETE RPTMASTER WHERE RPTID = 'CF3001';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('CF3001','HOST','CF','12','5','5','60','5','5','BÁO CÁO XÁC NHẬN SỐ DƯ TÀI KHOẢN LƯU KÝ CHỨNG KHOÁN - 13/LK-TV','Y',1,'1','P','CF3001','Y','S','N','R','N','N','M','000','S',-1,'BÁO CÁO XÁC NHẬN SỐ DƯ TÀI KHOẢN LƯU KÝ CHỨNG KHOÁN - 13/LK-TV',null,'0','0','0','0','N','N','Y');
COMMIT;
/
