--
--
/
DELETE RPTMASTER WHERE RPTID = 'CF0040';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('CF0040','HOST','CF','12','5','5','60','5','5','CHI TIẾT SỐ DƯ ĐƯỢC RÚT CỦA TIỂU KHOẢN','Y',1,'1','P','CF0040','Y','S','N','R','N','N','M','000','S',-1,'Báo cáo danh sách ủy quyền(HNX)',null,'0','0','0','0','N','N','Y');
COMMIT;
/
