--
--
/
DELETE rptmaster WHERE rptid = 'CI1118';
insert into rptmaster (RPTID, DSN, MODCODE, FONTSIZE, RHEADER, PHEADER, RDETAIL, PFOOTER, RFOOTER, DESCRIPTION, AD_HOC, RORDER, PSIZE, ORIENTATION, STOREDNAME, VISIBLE, AREA, ISLOCAL, CMDTYPE, ISCAREBY, ISPUBLIC, ISAUTO, ORD, AORS, ROWPERPAGE, EN_DESCRIPTION, STYLECODE, TOPMARGIN, LEFTMARGIN, RIGHTMARGIN, BOTTOMMARGIN, SUBRPT, ISCMP, ISDEFAULTDB)
values ('CI1118', 'HOST', 'CI', '12', '5', '5', '60', '5', '5', 'DANH SÁCH CÁC YÊU CẦU CHUYỂN TIỀN RA NGÂN HÀNG CHỜ DUYỆT', 'Y', 1, '1', 'P', 'CI1118', 'Y', 'B', 'N', 'V', 'N', 'N', 'M', '000', 'S', -1, 'LIST OF BANK TRANSFER REQUESTS WAITING FOR APPROVAL', null, 0, 0, 0, 0, 'N', 'N', 'Y');
COMMIT;
/
