--
--
/
DELETE RPTMASTER WHERE RPTID = 'MR3007_1';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('MR3007_1','HOST','MR','12','5','5','60','5','5','Màn hình tra soát FO – Danh sách tài sản tài khoản','Y',1,'1','P',null,'Y','B','N','V','N','N','M','000','S',-1,'MR3007_1',null,'0','0','0','0','N','N','N');
COMMIT;
/
