--
--
/
DELETE RPTMASTER WHERE RPTID = 'MR1809';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('MR1809','HOST','MR','12','5','5','60','5','5','Danh sách khách hàng chờ cấp hạn mức bảo lãnh tối đa (Giao dịch 1809)','Y',1,'1','P','MR1809','Y','B','N','V','N','N','M','000','S',-1,'General view of allocated T0 to customer',null,'0','0','0','0','N','N','Y');
COMMIT;
/
