--
--
/
DELETE RPTMASTER WHERE RPTID = 'TD0004';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('TD0004','HOST','TD','12','5','5','60','5','5','TRA CUU GIAO DICH PHAT SINH (CHAN THEO CAREBY)','Y',1,'1','P',null,'Y','B','N','V','N','N','M','0  ','S',-1,'Tra cuu giao dich phat sinh (chan theo careby)',null,'0','0','0','0','N','N','Y');
COMMIT;
/
