--
--
/
DELETE RPTMASTER WHERE RPTID = 'MR0009';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('MR0009','HOST','MR','12','5','5','60','5','5','BÁO CÁO TRẠNG THÁI CẤP HẠN MỨC MARGIN','Y',1,'1','P','MR0009','Y','S','N','R','N','N','M','000','S',-1,'BÁO CÁO TRẠNG THÁI CẤP HẠN MỨC MARGIN',null,'0','0','0','0','N','N','Y');
COMMIT;
/
