--
--
/
DELETE RPTMASTER WHERE RPTID = 'CA0040';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('CA0040','HOST','CA','12','5','5','60','5','5','BÁO CÁO THỰC HIỆN QUYỀN GIẢI THỂ TCPH','Y',1,'1','L','CA0040','Y','S','N','R','N','N','M','000','S',-1,'Báo cáo thực hiện quyền giải thể TCPH',null,'0','0','0','0','N','N','Y');
COMMIT;
/
