--
--
/
DELETE RPTMASTER WHERE RPTID = 'GR5076';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('GR5076','HOST','GR','12','5','5','60','5','5','HỢP ĐỒNG BẢO LÃNH CHỜ GIẢI TOẢ','Y',1,'1','P','GR9001','Y','B','N','V','N','N','M','000','S',-1,'View Guarantee contract ready to release',null,'0','0','0','0','N','N','Y');
COMMIT;
/
