--
--
/
DELETE RPTMASTER WHERE RPTID = 'SA0015';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('SA0015','HOST','SA','12','5','5','60','5','5','BÁO CÁO DỊCH VỤ CHỨNG KHOÁN THEO CÁC TRUNG TÂM KHÁCH HÀNG','Y',1,'1','L','SA0015','Y','S','N','R','N','N','M','000','S',-1,'BÁO CÁO DỊCH VỤ CHỨNG KHOÁN THEO CÁC TRUNG TÂM KHÁCH HÀNG',null,'0','0','0','0','N','N','Y');
COMMIT;
/
