--
--
/
DELETE RPTMASTER WHERE RPTID = 'CF0043';
INSERT INTO RPTMASTER (RPTID,DSN,MODCODE,FONTSIZE,RHEADER,PHEADER,RDETAIL,PFOOTER,RFOOTER,DESCRIPTION,AD_HOC,RORDER,PSIZE,ORIENTATION,STOREDNAME,VISIBLE,AREA,ISLOCAL,CMDTYPE,ISCAREBY,ISPUBLIC,ISAUTO,ORD,AORS,ROWPERPAGE,EN_DESCRIPTION,STYLECODE,TOPMARGIN,LEFTMARGIN,RIGHTMARGIN,BOTTOMMARGIN,SUBRPT,ISCMP,ISDEFAULTDB)
VALUES ('CF0043','HOST','CF','12','5','5','60','5','5','Gửi yêu cầu mở tài khoản lên TTLK  (Giao dịch 0043)','Y',1,'1','P','CF0043','Y','B','N','V','N','N','M','000','S',-1,'View create open account request send to VSD (Transaction 0043)',null,'0','0','0','0','N','N','N');
COMMIT;
/
