--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'CA3340';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('CA3340','Xác nhận thực hiện quyền với trung tâm lưu ký','Confirm CA action','
select * from (select a.camastid,max(a.autoid) autoid, max(a.description) description , max(b.symbol) symbol, max(a.actiondate) actiondate, max(cd.cdcontent) catype,
max(chd.codeid) codeid,
sum((case when a.catype in (''014'',''023'')then nvl(chd.qtty,0) else nvl(chd.trade,0) end)) QTTYDIS,
nvl(max(a.tocodeid),max(a.codeid)) tocodeid, max(tosym.symbol) TOSYMBOL
from camast a, sbsecurities b, allcode cd, caschd chd, sbsecurities tosym
where a.codeid = b.codeid and ((chd.status IN(''V'',''M'') and a.catype in (''014'',''023''))
or(chd.status IN(''A'') and a.catype<>''014'' and a.catype<>''023'')) and a.deltd=''N''
and a.camastid= chd.camastid and chd.deltd <> ''Y''
and cd.cdname =''CATYPE'' and cd.cdtype =''CA'' and cd.cdval = a.catype
and a.catype not in (''019'')
and nvl(a.tocodeid,a.codeid)=tosym.codeid
group by a.camastid ) where 0=0','CAMAST',null,'AUTOID DESC','3340',null,50,'N',30,'NYNNYYYNNN','Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'CA3340';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (23,'TOSYMBOL','Mã CK phân bổ','C','CA3340',100,null,'=',null,'Y','Y','N',100,null,'Codeid','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (23,'SYMBOL','Mã CK chốt SH','C','CA3340',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Symbol','N','04',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (23,'TOCODEID','Mã CK phân bổ','C','CA3340',100,null,'=',null,'N','N','N',100,null,'Codeid','N','40',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (23,'CODEID','Mã CK','C','CA3340',100,null,'=',null,'N','N','N',100,null,'Codeid','N','22',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (22,'QTTYDIS','Số lượng hiển thị','N','CA3340',100,null,'<,<=,=,>=,>','#,##0','N','N','N',100,null,'Amount','N','21',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'ACTIONDATE','Ngày TH quyền','D','CA3340',100,null,'>,>=,=,<=,<',null,'Y','Y','N',100,null,'Action date','N','07',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'CATYPE','Loại thực hiện quyền','C','CA3340',100,null,'LIKE,=',null,'Y','Y','N',400,'SELECT CDVAL VALUE, CDCONTENT DISPLAY FROM ALLCODE WHERE CDTYPE = ''CA''
AND CDNAME = ''CATYPE'' AND CDUSER=''Y''  ORDER BY LSTODR','Coporate action type','N','05',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'DESCRIPTION','Thông tin đợt TH quyền','C','CA3340',100,null,'LIKE,=',null,'Y','Y','N',400,null,'Description','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'CAMASTID','Mã TH quyền','C','CA3340',100,'cccc.cccccc.cccccc','LIKE,=','_','Y','Y','Y',120,null,'CA code','N','03',null,'N',null,null,null,'N');
COMMIT;
/
