--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'OD4004';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('OD4004','Thông tin user-pass GDTT (HAGW)','User-pass onlinetraing','SELECT * FROM (SELECT sysvalue GWUSERNAME FROM ordersys_ha WHERE sysname =''GWUSERNAME'') US, (SELECT sysvalue GWPASSWORD FROM ordersys_ha WHERE sysname =''GWPASSWORD'') PAS WHERE 0=0 ','OD4004',null,null,null,0,50,'N',30,null,'Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'OD4004';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'GWPASSWORD','Mật khẩu','C','OD4004',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Old Pass','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'GWUSERNAME','User','C','OD4004',100,null,'LIKE,=',null,'Y','Y','Y',100,null,'Username','N',null,null,'N',null,null,null,'N');
COMMIT;
/
