--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'TLPROFILES_TX';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('TLPROFILES_TX','Quản lý người sử dụng','User management','SELECT PR.TLID, PR.TLNAME, PR.TLFULLNAME, GR.GRPID, GR.GRPNAME, A.CDCONTENT TLAPARTMENT
FROM TLGROUPS GR, TLPROFILES PR, TLGRPUSERS GPR, ALLCODE A
WHERE GPR.GRPID = GR.GRPID AND PR.TLID  = GPR.TLID  AND GR.ACTIVE = ''Y'' AND GR.GRPTYPE =  ''2''
AND A.CDTYPE = ''SA'' AND A.CDNAME = ''TLGROUP'' AND TRIM(A.CDVAL) = TRIM(PR.TLGROUP)
AND GR.GRPID IN
    (
    SELECT GR.GRPID FROM TLGROUPS GR, TLPROFILES PR, TLGRPUSERS GPR
    WHERE  GPR.GRPID = GR.GRPID AND PR.TLID  = GPR.TLID  AND GR.ACTIVE = ''Y'' AND GR.GRPTYPE =  ''2''
    AND PR.TLID = ''<$TELLERID>''
    ) ','TLPROFILES_TX',null,'TLNAME',null,null,50,'Y',30,null,'Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'TLPROFILES_TX';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'TLDEPARTMENT','Phòng ban trực thuộc','C','TLPROFILES_TX',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Department','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'GRPNAME','Tên nhóm','C','TLPROFILES_TX',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Department','Y',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'GRPID','Mã nhóm','C','TLPROFILES_TX',100,null,'LIKE,=',null,'Y','Y','Y',100,null,'Department','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'TLFULLNAME','Họ tên đầy đủ','C','TLPROFILES_TX',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Fullname','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'TLNAME','Tên người sử dụng','C','TLPROFILES_TX',100,null,'LIKE,=',null,'Y','Y','N',100,null,'User name','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (0,'TLID','Mã người sử dụng','C','TLPROFILES_TX',50,null,'LIKE,=',null,'Y','Y','N',50,null,'User code','N',null,null,'N',null,null,null,'N');
COMMIT;
/
