--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'OD9995';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('OD9995','Hiển thị các lệnh nhóm','Hiển thị các lệnh nhóm','
SELECT ORDGRPID, REPLACE(ORDERID || TO_CHAR(SEQ_ODMAST.NEXTVAL,''000000''),'' '','''') ORDERID,
    DECODE(TYPE,''S'',''CK giao dịch'', ''D'', ''CK cầm cố'', ''O'', ''CK giao dịch CHƯA KHỚP'', ''M'', ''CK cầm cố CHƯA KHỚP'') TYPE , REFACCTNO,
    CODEID, SYMBOL, ACTYPE, QUOTEPRICE, ORDERQTTY,
    AFACCTNO, AFACCTNO||A.CODEID SEACCTNO, CLEARDAY, BRATIO, LIMITPRICE, PARVALUE, EFFDATE, TIMETYPE, EXPDATE, CASE WHEN TYPE IN (''M'',''D'') THEN ''MS'' ELSE ''NS'' END EXECTYPE, NORK, MATCHTYPE, VIA, CLEARCD, PRICETYPE, VOUCHER,
    CONSULTANT, DESCRIPTION, CONTRAFIRM, TRADERID, CLIENTID, OUTPRICEALLOW, ADVIDREF, FEEAMT, CUSTID CUSTNAME, GRPORDER, CASE WHEN TYPE IN (''M'',''D'') THEN 1 ELSE 0 END ISMORTAGE, CONTRACUS,
    PUTTYPE, CONTRAFIRMA, SSAFACCTNO, DEALID, TRADEUNITGTC, MODEA, TRADEUNIT, HUNDRED  FROM (
    SELECT B.ORDERID ORDGRPID, REPLACE(SUBSTR(B.ORDERID,1,4) ||SUBSTR(REPLACE(TO_CHAR(A.TXDATE,''DD/MM/RRRR''),''/'',''''),1,4) ||
    SUBSTR(REPLACE(TO_CHAR(A.TXDATE,''DD/MM/RRRR''),''/'',''''),7,2) ,'' '','''')    ORDERID, B.TYPE,
    A.CODEID,C.SYMBOL , A.ACTYPE,A.QUOTEPRICE/F.TRADEUNIT QUOTEPRICE,  B.QTTY ORDERQTTY,
    DECODE(B.TYPE,''S'',SUBSTR(B.REFID,1,10),''D'',(SELECT AFACCTNO FROM DFMAST WHERE ACCTNO=B.REFID),''O'',(SELECT AFACCTNO FROM ODMAST WHERE
    ORDERID=B.REFID),''M'',(SELECT AFACCTNO FROM DFMAST WHERE ACCTNO=B.REFID)) AFACCTNO, AFACCTNO||A.CODEID SEACCTNO, A.CLEARDAY,  ROUND(A.BRATIO,2) BRATIO, A.LIMITPRICE, C.PARVALUE,
    A.EXPDATE EFFDATE, A.TIMETYPE, A.EXPDATE, A.EXECTYPE, A.NORK, ''P'' MATCHTYPE, A.VIA, A.CLEARCD, A.PRICETYPE,B.ORDERID VOUCHER,
    ''I'' CONSULTANT,     A.AFACCTNO ||''.''||E.FULLNAME||''.''||A.MATCHTYPE||A.EXECTYPE||''.''||B.QTTY||''.''|| A.QUOTEPRICE/F.TRADEUNIT DESCRIPTION,
    CONTRAFIRM, TRADERID, CLIENTID,     ''N'' OUTPRICEALLOW, '''' ADVIDREF, 0 FEEAMT, E.FULLNAME CUSTNAME,     ''N'' GRPORDER, 0 ISMORTAGE,
    A.CONTRAFIRM CONTRACUS, ''3'' PUTTYPE, ''A'' CONTRAFIRMA, B.REFID SSAFACCTNO,
    CASE WHEN B.TYPE = ''O'' THEN A.SEACCTNO ELSE B.REFID END REFACCTNO,
    DECODE(B.TYPE,''S'','''',''D'',B.REFID,''O'','''',''M'',B.REFID) DEALID,
    1 TRADEUNITGTC, ''A'' MODEA, F.TRADEUNIT, 100 HUNDRED,e.CUSTID FROM ODMAST A,
    (SELECT * FROM ODMAPEXT WHERE DELTD <> ''Y'' AND STATUS <> ''Y'' ORDER BY ORDERID) B, SBSECURITIES C, AFMAST D, CFMAST E , SECURITIES_INFO F
    WHERE A.ORDERID = B.ORDERID AND A.CODEID=C.CODEID AND D.ACCTNO=A.AFACCTNO AND D.CUSTID=E.CUSTID AND A.CODEID=F.CODEID
    AND A.exectype =''NS'' and A.matchtype=''P'' and A.grporder=''Y''
    and A.deltd<>''Y'' ) A WHERE 0=0  ','ODMAST','frmGROUPORDERPT',null,'8877',null,50,'N',30,'NYNNYYYNNN','Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'OD9995';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (18,'MATCHTYPE','Hình thức khớp lệnh','C','OD9995',100,null,'LIKE,=',null,'N','N','N',150,null,'MATCHTYPE','N','24',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (17,'NORK','Tính hoàn chỉnh','C','OD9995',100,null,'LIKE,=',null,'N','N','N',150,null,'NORK','N','23',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (16,'EXECTYPE','Loại lệnh','C','OD9995',100,null,'LIKE,=',null,'N','N','N',150,null,'EXECTYPE','N','22',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (15,'EXPDATE','Ngày hiệu lực','D','OD9995',100,null,'LIKE,=',null,'N','N','N',200,null,'EXPDATE','N','21',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (14,'TIMETYPE','Phạm vi thời gian','C','OD9995',100,null,'LIKE,=',null,'N','N','N',150,null,'TIMETYPE','N','20',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (13,'EFFDATE','Ngày hiệu lực','D','OD9995',100,null,'LIKE,=',null,'N','N','N',200,null,'EFFDATE','N','19',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (12,'PARVALUE','Mệnh giá','N','OD9995',100,null,'<,<=,=,>=,>',null,'N','N','N',100,null,'PARVALUE','N','15',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (12,'MODEA','MODEA','C','OD9995',100,null,'=',null,'N','N','N',80,null,'MODEA','N','97',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (11,'LIMITPRICE','Giá giới hạn','N','OD9995',100,null,'<,<=,=,>=,>',null,'N','N','N',100,null,'LIMITPRICE','N','14',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (10,'CUSTNAME','Tên khách hàng','C','OD9995',100,null,'=',null,'N','N','N',80,null,'CUSTNAME','N','50',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (10,'CONTRAFIRMA','CONTRAFIRM','C','OD9995',100,null,'=',null,'N','N','N',80,null,'CONTRAFIRM','N','73',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (10,'PUTTYPE','Loại thỏa thuận','C','OD9995',100,null,'=',null,'N','N','N',80,null,'PUTTYPE','N','72',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (10,'CONTRACUS','CONTRACUS','C','OD9995',100,null,'=',null,'N','N','N',80,null,'CONTRACUS','N','71',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (10,'GRPORDER','Lệnh thỏa thuân nhóm','C','OD9995',100,null,'=',null,'N','N','N',80,null,'GRPORDER','N','55',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (10,'BRATIO','Tỷ lệ ký quỹ','N','OD9995',100,null,'<,<=,=,>=,>',null,'N','N','N',100,null,'BRATIO','N','13',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'HUNDRED','Một trăm','N','OD9995',100,null,'<,<=,=,>=,>','#,##0','N','N','N',80,null,'HUNDRED','N','99',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'ACTYPE','Mã loại hình','C','OD9995',100,null,'LIKE,=',null,'N','N','N',0,null,'ID type','N','02',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'TRADEUNIT','Đơn vị giá','N','OD9995',100,null,'<,<=,=,>=,>','#,##0','N','N','N',80,null,'TRADEUNIT','N','98',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'TRADEUNITGTC','GTC','N','OD9995',100,null,'<,<=,=,>=,>','#,##0','N','N','N',80,null,'TRADEUNITGTC','N','96',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'ISMORTAGE','Bán cầm cố','N','OD9995',100,null,'<,<=,=,>=,>','#,##0','N','N','N',80,null,'ISMORTAGE','N','60',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'FEEAMT','Giá trị phí','N','OD9995',100,null,'<,<=,=,>=,>','#,##0','N','N','N',80,null,'FEEAMT','N','40',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'CLEARDAY','Số ngày thanh toán','N','OD9995',100,null,'<,<=,=,>=,>',null,'N','N','N',100,null,'CLEARDAY','N','10',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'ADVIDREF','ADVIDREF','C','OD9995',100,null,'LIKE,=',null,'N','N','N',150,null,'ADVIDREF','N','35',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'OUTPRICEALLOW','Chấp nhận lệnh ngoài biên độ','C','OD9995',100,null,'LIKE,=',null,'N','N','N',150,null,'OUTPRICEALLOW','N','34',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'CLIENTID','CLIENTID','C','OD9995',100,null,'LIKE,=',null,'N','N','N',150,null,'CLIENTID','N','33',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'TRADERID','TRADERID','C','OD9995',100,null,'LIKE,=',null,'N','N','N',150,null,'TRADERID','N','32',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'VIA','Kênh đặt lệnh','C','OD9995',100,null,'LIKE,=',null,'N','N','N',150,null,'VIA','N','25',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'DESCRIPTION','Mô tả','C','OD9995',100,null,'LIKE,=',null,'N','N','N',150,null,'DESCRIPTION','N','30',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'CONSULTANT','Thông tin tư vấn','C','OD9995',100,null,'LIKE,=',null,'N','N','N',150,null,'CONSULTANT','N','29',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'VOUCHER','Thông tin chứng từ','C','OD9995',100,null,'LIKE,=',null,'N','N','N',150,null,'VOUCHER','N','28',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'PRICETYPE','Loại giá đặt lệnh','C','OD9995',100,null,'LIKE,=',null,'N','N','N',150,null,'PRICETYPE','N','27',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'CLEARCD','Loại lịch','C','OD9995',100,null,'LIKE,=',null,'N','N','N',150,null,'CLEARCD','N','26',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'CONTRAFIRM','Contrafirm','C','OD9995',100,null,'LIKE,=',null,'N','N','N',150,null,'CONTRAFIRM','N','31',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (6,'QUOTEPRICE','Giá','N','OD9995',100,null,'<,<=,=,>=,>',null,'Y','Y','N',100,null,'QUOTEPRICE','N','11',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'ORDERQTTY','Khối lượng','N','OD9995',100,null,'<,<=,=,>=,>',null,'Y','Y','N',100,null,'ORDERQTTY','N','12',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'SSAFACCTNO','Tai khoan vay','C','OD9995',100,'9999.999999.999999','=','_','N','N','N',100,null,'SSAFACCTNO','N','94',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'DEALID','So hieu deal','C','OD9995',100,'9999.999999.999999','=','_','N','N','N',100,null,'DEALID','N','95',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'CODEID','MA CK','C','OD9995',100,null,'=',null,'N','N','N',80,null,'CODEID','N','01',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'SYMBOL','Mã chứng khoán','C','OD9995',100,null,'LIKE,=',null,'Y','Y','N',80,null,'SYMBOL','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'TYPE','Loại','C','OD9995',100,null,'LIKE,=',null,'Y','Y','N',80,null,'ID type','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'REFACCTNO','Số tài khoản liên quan','C','OD9995',100,'9999.999999.999999','=','_','Y','Y','N',100,null,'REF account number','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'AFACCTNO','Số tiểu khoản','C','OD9995',120,null,'LIKE,=','_','Y','Y','N',100,null,'Account number','N','03',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'SEACCTNO','Số tài khoản SE','C','OD9995',100,'9999.999999.999999','=','_','Y','Y','N',100,null,'SE account number','N','06',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'ORDERID','Số hiệu lệnh','C','OD9995',100,'9999.999999.999999','LIKE,=',null,'Y','Y','Y',100,null,'Order ID','N','04',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (0,'ORDGRPID','Số lệnh tổng ','C','OD9995',100,'9999.999999.999999','LIKE,=',null,'Y','Y','N',100,null,'ORDGRPID','N',null,null,'N',null,null,null,'N');
COMMIT;
/
