--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'TLPROFILES';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('TLPROFILES','Quản lý nguời sử dụng','User management','SELECT M.TLID, M.TLNAME, M.TLFULLNAME,M.IDCODE, N.BRNAME, A3.CDCONTENT TLTITLE, M.TLPRN, A1.CDCONTENT TLGROUP, A2.cdcontent ACTIVE, M.DESCRIPTION, M.EMAIL
FROM TLPROFILES M, ALLCODE A1, BRGRP N, ALLCODE A2, ALLCODE A3 WHERE A1.CDTYPE = ''SA'' AND A1.CDNAME = ''TLGROUP''
AND A2.CDTYPE = ''SA'' AND A2.CDNAME = ''ACTIVE'' AND M.ACTIVE = A2.CDVAL
AND A3.CDTYPE(+) = ''SA'' AND A3.CDNAME(+) = ''TLTITLE'' AND M.TLTITLE = A3.CDVAL(+)
AND TRIM(A1.CDVAL)=TRIM(TLGROUP) AND M.BRID = N.BRID AND M.BRID = DECODE(''<$BRID>'',''<$HO_BRID>'', M.BRID, ''<$BRID>'')','TLPROFILES','frmTLPROFILES','TLNAME',null,null,50,'N',30,null,'Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'TLPROFILES';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (11,'EMAIL','Email','C','TLPROFILES',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Email','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'DESCRIPTION','Diễn giải','C','TLPROFILES',100,null,'LIKE,=',null,'Y','N','N',100,null,'Notes','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (8,'TLPRN','Số điện thoại','C','TLPROFILES',100,null,'LIKE,=',null,'Y','N','N',100,null,'Printer name','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'BRNAME','Chi nhánh','C','TLPROFILES',100,null,'LIKE,=',null,'Y','Y','N',100,'SELECT BRID VALUE, BRNAME DISPLAY FROM BRGRP WHERE STATUS = ''A'' ORDER BY BRID','Branch','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (6,'ACTIVE','Trạng thái','C','TLPROFILES',100,null,'LIKE,=',null,'Y','Y','N',100,'SELECT CDVAL VALUE, CDCONTENT DISPLAY  FROM ALLCODE WHERE CDNAME = ''ACTIVE'' AND CDTYPE= ''SA''','Branch','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'TLGROUP','Phòng ban trực thuộc','C','TLPROFILES',100,null,'LIKE,=',null,'Y','Y','N',100,'SELECT CDVAL VALUE, CDCONTENT DISPLAY FROM ALLCODE WHERE CDTYPE = ''SA'' AND CDNAME = ''TLGROUP'' ORDER BY LSTODR','Department','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'TLTITLE','Chức vụ','C','TLPROFILES',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Job title','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'IDCODE','Số CMT/HC','C','TLPROFILES',100,null,'LIKE,=',null,'Y','Y','N',100,null,'ID Code','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'TLFULLNAME','Họ tên đầy đủ','C','TLPROFILES',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Fullname','Y',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'TLNAME','Tên người sử dụng','C','TLPROFILES',100,null,'LIKE,=',null,'Y','Y','N',100,null,'User name','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (0,'TLID','Mã người sử dụng','C','TLPROFILES',50,null,'LIKE,=',null,'Y','Y','Y',50,null,'User code','N',null,null,'N',null,null,null,'N');
COMMIT;
/
