--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'REMAST';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('REMAST','Tài khoản đại lý/môi giới','Remiser account','SELECT MST.ACCTNO, TYP.TYPENAME, CF.FULLNAME,
CF.FULLNAME || '' ['' || A0.CDCONTENT || ''] '' REFVALUE, 
MST.DIRECTACR, MST.INDIRECTACR,
MST.BALANCE, A0.CDCONTENT DESC_RETYPE, 
DECODE(TYP.RETYPE,''D'',A2.CDCONTENT,''--'') DESC_REROLE,
A1.CDCONTENT DESC_STATUS,
MST.DIRECTFEEACR - MST.RFMATCHAMT - MST.INRFFEEACR DIRECTFEEACR,
MST.INDIRECTFEEACR - MST.INRFMATCHAMT - MST.INRFFEEACR INDIRECTFEEACR
FROM RECFLNK RF, REMAST MST, CFMAST CF, RETYPE TYP, 
ALLCODE A0, ALLCODE A1, ALLCODE A2
WHERE MST.ACTYPE=TYP.ACTYPE AND MST.CUSTID=CF.CUSTID
AND A0.CDTYPE=''RE'' AND A0.CDNAME=''RETYPE'' AND 
TYP.RETYPE=A0.CDVAL
AND A2.CDTYPE=''RE'' AND A2.CDNAME=''REROLE'' AND 
TYP.REROLE=A2.CDVAL
AND A1.CDTYPE=''RE'' AND A1.CDNAME=''STATUS'' AND 
MST.STATUS=A1.CDVAL
AND RF.CUSTID=MST.CUSTID AND RF.AUTOID=<$KEYVAL>','RE.REMAST','frmTDMAST',null,null,0,50,'N',30,null,'Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'REMAST';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (11,'INDIRECTFEEACR','DT gián tiếp','N','REMAST',80,null,'<,<=,=,>=,>,<>','#,##0.###','Y','Y','N',100,null,'InDirect FEE amount','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (10,'DIRECTFEEACR','DT trực tiếp','N','REMAST',80,null,'<,<=,=,>=,>,<>','#,##0.###','Y','Y','N',100,null,'Direct FEE amount','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'INDIRECTACR','DS gián tiếp','N','REMAST',80,null,'<,<=,=,>=,>,<>','#,##0.###','Y','Y','N',100,null,'InDirect amount','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (8,'DIRECTACR','DS trực tiếp','N','REMAST',80,null,'<,<=,=,>=,>,<>','#,##0.###','Y','Y','N',100,null,'Direct amount','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'REFVALUE','Tên đại lý/môi giới','C','REMAST',100,null,'LIKE,=',null,'N','N','N',200,null,'Remiser name','Y',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (6,'DESC_STATUS','Trạng thái','C','REMAST',80,null,'LIKE,=',null,'Y','Y','N',100,null,'Status','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'BALANCE','Hoa hồng','N','REMAST',80,null,'<,<=,=,>=,>,<>','#,##0.###','Y','Y','N',100,null,'Balance','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'TYPENAME','Loại hình','C','REMAST',100,null,'LIKE,=',null,'Y','Y','N',150,null,'Product name','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'DESC_RETYPE','Loại','C','REMAST',80,null,'LIKE,=',null,'Y','Y','N',100,null,'Type','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'DESC_REROLE','Vai trò','C','REMAST',80,null,'LIKE,=',null,'Y','Y','N',100,null,'Role','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'FULLNAME','Tên đại lý/môi giới','C','REMAST',100,null,'LIKE,=',null,'Y','Y','N',200,null,'Remiser name','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (0,'ACCTNO','Số tài khoản','C','REMAST',120,null,'LIKE,=',null,'Y','Y','Y',100,null,'Remiser account','N',null,null,'N',null,null,null,'N');
COMMIT;
/
