--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'CFPREFERENTIAL';
insert into search (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE)
values ('CFPREFERENTIAL', 'Danh sách KH được hưởng chính sách', 'Customer list is entitled to the policy', 'SELECT C.AUTOID,C.CUSTODYCD,C.AFACCTNO,C.LNTYPE,C.LNTYPE,C.LNID,C.FDATE,C.TDATE,A.CDCONTENT STATUS FROM CFPREFERENTIAL C, ALLCODE A  where 1=1 AND A.CDVAL= C.STATUS AND A.CDTYPE = ''LN'' AND A.CDNAME = ''STATUS505'' AND C.TDATE >= getcurrdate AND C.LNID=<$KEYVAL>', 'LN.CFPREFERENTIAL', 'frmLNMAST', null, null, null, 50, 'N', 0, null, 'Y', 'T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'CFPREFERENTIAL';
insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
values (2, 'TDATE', 'Đến giá trị', 'D', 'CFPREFERENTIAL', 100, null, '<,<=,=,>=,>,<>', '#,##0', 'Y', 'Y', 'N', 100, null, 'Loan amount', 'N', null, null, 'N', null, null, null, 'N');

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
values (3, 'LNTYPE', 'Loại hình tín dụng', 'C', 'CFPREFERENTIAL', 100, null, '<,<=,=,>=,>,<>', '#,##0.###0', 'Y', 'Y', 'N', 100, null, 'Loan amount', 'N', null, null, 'N', null, null, null, 'N');

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
values (5, 'AFACCTNO', 'Số tiểu khoản', 'C', 'CFPREFERENTIAL', 100, null, '<,<=,=,>=,>,<>', '#,##0.###0', 'Y', 'Y', 'N', 100, null, 'Loan amount', 'N', null, null, 'N', null, null, null, 'N');

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
values (4, 'CUSTODYCD', 'Số TK lưu ký', 'C', 'CFPREFERENTIAL', 100, null, '<,<=,=,>=,>,<>', '#,##0.###0', 'Y', 'Y', 'N', 100, null, 'Loan amount', 'Y', null, null, 'N', null, null, null, 'N');

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
values (3, 'LNID', 'Mã loại hình', 'C', 'CFPREFERENTIAL', 100, null, '=,<>,<,<=,>=,>', '#,##0', 'Y', 'Y', 'N', 100, null, 'Auto ID', 'N', null, null, 'N', null, null, null, 'N');

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
values (1, 'FDATE', 'Từ ngày', 'D', 'CFPREFERENTIAL', 100, null, '<,<=,=,>=,>,<>', '#,##0', 'Y', 'Y', 'N', 100, null, 'Loan amount', 'N', null, null, 'N', null, null, null, 'N');

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
values (-1, 'AUTOID', 'Mã QL', 'N', 'CFPREFERENTIAL', 100, null, '=,<>,<,<=,>=,>', '#,##0', 'N', 'Y', 'Y', 100, null, 'Auto ID', 'N', null, null, 'N', null, null, null, 'N');

insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
values (6, 'STATUS', 'Trạng thái', 'C', 'CFPREFERENTIAL', 100, null, '=', null, 'Y', 'Y', 'N', 100, 'SELECT CDVAL VALUE, CDCONTENT DISPLAY FROM ALLCODE WHERE CDTYPE = ''LN'' AND CDNAME = ''STATUS505'' ORDER BY LSTODR', 'status?', 'N', null, null, 'N', null, null, null, 'N');
COMMIT;
/
