--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'CFSIGN';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('CFSIGN','QUAN LY CHU KY KHACH HANG','CUSTOMER SIGN MANAGEMENT','SELECT * FROM CFSIGN','CFSIGN','FRMCFSIGN',null,null,null,50,'N',30,null,'Y','T');
COMMIT;
/
