--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'RECFDEF_BRTEMP';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('RECFDEF_BRTEMP','Loại hình đại lý/môi giới','Broker/Remiser product','SELECT (CF.CUSTID||''.''||RF.REACTYPE) REACCT, RF.AUTOID,
CFMAST.FULLNAME, TYP.ACTYPE, TYP.TYPENAME, A2.CDCONTENT
AFSTATUS,
typ.rerole,A0.CDCONTENT DESC_REROLE, A1.CDCONTENT
DESC_RETYPE, RF.EFFDATE, RF.EXPDATE,RF.ODRNUM,
(CFMAST.FULLNAME || ''/''|| TYP.TYPENAME) DESC_TYPE,
CF.CUSTID
FROM RECFDEF RF, RETYPE TYP, ALLCODE A0, ALLCODE A1,
ALLCODE A2, RECFLNK CF, CFMAST
WHERE A0.CDTYPE=''RE'' AND A0.CDNAME=''REROLE'' AND
A0.CDVAL=TYP.REROLE
AND A2.CDTYPE = ''RE'' AND A2.CDNAME = ''AFSTATUS'' AND
A2.CDVAL = TYP.AFSTATUS
AND A1.CDTYPE=''RE'' AND A1.CDNAME=''RETYPE'' AND
A1.CDVAL=TYP.RETYPE
AND RF.REACTYPE=TYP.ACTYPE
AND RF.REFRECFLNKID = CF.AUTOID
AND CF.CUSTID = CFMAST.CUSTID
and cf.status = ''A'' and rf.status = ''A''
AND TYP.REROLE in (''BM'',''RM'')
AND RF.EFFDATE <= TO_DATE((select varvalue from sysvar
where varname=''CURRDATE''),''DD/MM/YYYY'')
and TO_DATE((select varvalue from sysvar where
varname=''CURRDATE''),''DD/MM/YYYY'')< nvl(RF.CLOSEDATE -1 ,RF.EXPDATE)','RE.RECFDEF_BRTEMP','frmRECFDEF_01','ACTYPE,TYPENAME,FULLNAME',null,0,50,'N',30,null,'Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'RECFDEF_BRTEMP';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (10,'DESC_TYPE','Diễn giải','C','RECFDEF_BRTEMP',200,null,'=,LIKE',null,'N','N','N',200,null,'Type description','Y',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'AFSTATUS','Loại KH','C','RECFDEF_BRTEMP',200,null,'=,LIKE',null,'Y','Y','N',200,null,'Customer type','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (8,'ODRNUM','Thứ tự phân bổ','N','RECFDEF_BRTEMP',50,null,'<,<=,=,>=,>,<>','#,##0','Y','Y','N',100,null,'Order','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'EXPDATE','Ngày hết hạn','C','RECFDEF_BRTEMP',200,null,'=,LIKE',null,'Y','Y','N',100,null,'Expired date','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (6,'EFFDATE','Ngày hiệu lực','C','RECFDEF_BRTEMP',200,null,'=,LIKE',null,'Y','Y','N',100,null,'Effective date','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'DESC_RETYPE','Tính chất','C','RECFDEF_BRTEMP',80,null,'LIKE,=',null,'Y','Y','N',150,null,'Type','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'DESC_REROLE','Vai trò','C','RECFDEF_BRTEMP',80,null,'LIKE,=',null,'Y','Y','N',150,null,'Role','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'REROLE','Vai trò','C','RECFDEF_BRTEMP',80,null,'=,LIKE',null,'Y','Y','N',80,null,'REROLE','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'FULLNAME','Tên môi giới','C','RECFDEF_BRTEMP',200,null,'=,LIKE',null,'Y','Y','N',200,null,'Remiser name','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'TYPENAME','Tên loại hình','C','RECFDEF_BRTEMP',200,null,'=,LIKE',null,'Y','Y','N',200,null,'Product name','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'ACTYPE','Mã loại hình','C','RECFDEF_BRTEMP',200,null,'=,LIKE',null,'Y','Y','N',100,null,'Product code','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (0,'REACCT','Mã loại môi giới','C','RECFDEF_BRTEMP',100,'9999.999999.9999','=,LIKE','_','N','Y','Y',50,null,'REACCT','N',null,null,'N',null,null,null,'N');
COMMIT;
/
