--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'CFLIMITCL';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('CFLIMITCL','NH - Quản lý hạn mức tín dụng chung','Common credit limit of the bank','
SELECT MST.AUTOID, MST.BANKID, MST.LMAMT, MST.LMAMTMAX, CF.FULLNAME,
A.CDCONTENT STATUS, A0.CDCONTENT DESC_LMTYP, A1.CDCONTENT DESC_LMSUBTYPE,
A2.CDCONTENT DESC_LMCHKTYP
FROM (select mst.*from CFLIMIT MST) mst, CFMAST CF, ALLCODE A, ALLCODE A0, ALLCODE A1, ALLCODE A2
WHERE MST.BANKID=CF.CUSTID AND A.CDTYPE=''SY'' AND A.CDNAME=''APPRV_STS'' AND A.CDVAL=MST.STATUS
AND A0.CDTYPE=''CF'' AND A0.CDNAME=''LMTYP'' AND A0.CDVAL=MST.LMTYP
AND A1.CDTYPE=''CF'' AND A1.CDNAME=''LMSUBTYPE'' AND A1.CDVAL=MST.LMSUBTYPE
AND A2.CDTYPE=''CF'' AND A2.CDNAME=''LMCHKTYP'' AND A2.CDVAL=MST.LMCHKTYP
AND mst.lmsubtype =''DFMR''  ','CFLIMITCL','frmCFLIMITCL',null,null,null,50,'N',30,null,'Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'CFLIMITCL';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'DESC_LMCHKTYP','Căn cứ số dư','C','CFLIMITCL',100,null,'LIKE,=',null,'Y','Y','N',80,null,'Balance type','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (8,'DESC_LMSUBTYPE','Nghiệp vụ','C','CFLIMITCL',100,null,'LIKE,=',null,'Y','Y','N',80,null,'Sub type','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'DESC_LMTYP','Loại','C','CFLIMITCL',100,null,'LIKE,=',null,'Y','Y','N',80,null,'Type','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (6,'STATUS','Trạng thái','C','CFLIMITCL',100,null,'LIKE,=',null,'Y','Y','N',80,null,'Status','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'LMAMT','Hạn mức khách hàng','N','CFLIMITCL',100,null,'>=,<=,=','#,##0','Y','Y','N',100,null,'Limit','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'LMAMTMAX','Hạn mức tối đa','N','CFLIMITCL',100,null,'>=,<=,=','#,##0','Y','Y','N',100,null,'Limit','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'FULLNAME','Tên NH','C','CFLIMITCL',100,null,'LIKE,=',null,'Y','Y','N',200,null,'Bank name','Y',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (0,'BANKID','Mã ngân hàng','C','CFLIMITCL',100,null,'LIKE,=',null,'Y','Y','Y',80,null,'BANKID','N',null,null,'N',null,null,null,'N');
COMMIT;
/
