--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'MSBBANKREQUEST';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('MSBBANKREQUEST','Đăng ký tự động chuyển tiền MSB','Register auto tranfer/receiving cash from MSB','SELECT r.autoid, a0.cdcontent status, r.pstatus, r.cusacctno, r.bankacctno, r.bankid, r.bankorgno, cf.fullname 
, case when nvl(l.bank_status,''X'') = ''E'' then ''Error: '' || l.errnum
       when nvl(l.bank_status,''X'') = ''C'' then ''Hoat dong''
       when nvl(l.bank_status,''X'') = ''R'' then ''Da huy''
       when nvl(l.bank_status,''X'') = ''W'' then ''Cho gui''
       else ''Chua duyet''
  end bankstatus,
(CASE WHEN r.STATUS IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW,
''Y'' DELALLOW 
FROM MSBBANKREQUEST r, cfmast cf, afmast af, allcode a0, MSBBANKREQUEST_LOG l where cf.custid = af.custid and af.acctno = r.cusacctno
and a0.cdname = ''STATUS'' and a0.cdtype = ''CF'' and a0.cdval = r.status and r.autoid = l.refautoid(+)
union all
SELECT r.autoid, a0.cdcontent status, r.pstatus, r.cusacctno, r.bankacctno, r.bankid, r.bankorgno, cf.fullname 
, case when nvl(l.bank_status,''X'') = ''E'' then ''Error: '' || l.errnum
       when nvl(l.bank_status,''X'') = ''C'' then ''Hoat dong''
       when nvl(l.bank_status,''X'') = ''R'' then ''Da huy''
       when nvl(l.bank_status,''X'') = ''W'' then ''Cho gui''
       else ''Chua duyet''
  end bankstatus,
''N'' APRALLOW ,
''N'' DELALLOW
FROM msbbankrequest_hist r, cfmast cf, afmast af, allcode a0, MSBBANKREQUEST_LOG l
where cf.custid = af.custid and af.acctno = r.cusacctno 
and a0.cdname = ''STATUS'' and a0.cdtype = ''CF'' and a0.cdval = r.status and r.autoid = l.refautoid(+)','MSBBANKREQUEST','frmMSBBANKREQUEST','AUTOID',null,null,50,'N',30,null,'Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'MSBBANKREQUEST';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (101,'DELALLOW','Cho phep xoa','C','MSBBANKREQUEST',100,null,'LIKE,=',null,'N','Y','N',100,null,'Delete Allow','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (100,'APRALLOW','Cho phep duyet','C','MSBBANKREQUEST',100,null,'LIKE,=',null,'N','Y','N',100,null,'Aprove Allow','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (10,'BANKSTATUS','Trang thai NH','C','MSBBANKREQUEST',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Status','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'PSTATUS','Trang thai','C','MSBBANKREQUEST',100,null,'LIKE,=',null,'N','N','N',50,'SELECT CDVAL VALUE, CDCONTENT DISPLAY FROM ALLCODE WHERE CDTYPE = ''CF'' AND CDNAME = ''STATUS'' ORDER BY LSTODR','Status','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (8,'STATUS','Trang thai','C','MSBBANKREQUEST',100,null,'LIKE,=',null,'Y','Y','N',100,'SELECT CDVAL VALUE, CDCONTENT DISPLAY FROM ALLCODE WHERE CDTYPE = ''CF'' AND CDNAME = ''STATUS'' ORDER BY LSTODR','Status','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'BANKORGNO','Mã chi nhánh','C','MSBBANKREQUEST',100,null,'LIKE,=',null,'Y','Y','N',100,null,'BANKORGID','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'BANKID','Mã hội sở','C','MSBBANKREQUEST',100,null,'LIKE,=','_','Y','Y','N',100,null,'Bank ID','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'BANKACCTNO','Số TK ngân hàng','C','MSBBANKREQUEST',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Bank acc no','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'FULLNAME','Tên khách hàng','C','MSBBANKREQUEST',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Customer name','Y',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'CUSACCTNO','Số tiểu khoản','C','MSBBANKREQUEST',50,'9999999999','LIKE,=','_','Y','Y','N',100,null,'Sub account','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (0,'AUTOID','Mã quản lý','C','MSBBANKREQUEST',20,null,'=,<>,<,<=,>=,>','#,##0','N','N','Y',100,null,'Auto ID','N',null,null,'N',null,null,null,'N');
COMMIT;
/
