--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'LN0001';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('LN0001','Tra cứu thông tin tài khoản vay','View loan accounts','SELECT SCHD.AUTOID, MST.ACTYPE, (CASE WHEN SCHD.REFTYPE = ''P'' THEN ''Margin loan'' WHEN SCHD.REFTYPE = ''GP'' THEN ''T0 loan'' END) CATEGORY,
MST.TRFACCTNO AFACCTNO, CF.FULLNAME, SCHD.ACCTNO LNACCTNO, SCHD.RLSDATE, CF.CUSTODYCD,
SCHD.DUEDATE PRINFRQ,SCHD.intnmlacrbank,
SCHD.OVERDUEDATE PRINPERIOD,
ROUND((CASE WHEN SCHD.OVERDUEDATE > TO_DATE(SYS.BUSDATE,''DD/MM/YYYY'') THEN SCHD.NML ELSE 0 END)) PRINNML,
ROUND((CASE WHEN SCHD.OVERDUEDATE = TO_DATE(SYS.BUSDATE,''DD/MM/YYYY'') THEN SCHD.NML ELSE 0 END)) PRINDUE,
(CASE WHEN MST.FTYPE = ''DF'' THEN ''Deal'' WHEN MST.FTYPE = ''AF'' AND SCHD.REFTYPE = ''P'' THEN ''Credit line'' WHEN MST.FTYPE = ''AF'' AND SCHD.REFTYPE = ''GP'' THEN ''Bao lanh'' END) FTYPE_NAME,
ROUND(SCHD.OVD) PRINOVD, ROUND(SCHD.PAID) PRINPAID, ROUND(SCHD.INTNMLACR) INTNMLACR, ROUND(SCHD.INTDUE) INTDUE, ROUND(SCHD.INTOVD) INTOVD, ROUND(SCHD.INTOVDPRIN) INTOVDPRIN, ROUND(SCHD.INTPAID) INTPAID,
ROUND(SCHD.FEE) + ROUND(SCHD.FEEDUE) + ROUND(SCHD.FEEOVD) + ROUND(SCHD.FEEPAID) +ROUND(SCHD.FEEPAID2) FEEAMT, ROUND(SCHD.FEE) FEE, ROUND(SCHD.FEEDUE) FEEDUE, ROUND(SCHD.FEEOVD) FEEOVD,
ROUND(SCHD.FEEPAID) + ROUND(SCHD.FEEPAID2) FEEPAID,
(CASE WHEN ABS(SCHD.NML + SCHD.OVD + SCHD.INTNMLACR + SCHD.INTDUE + SCHD.INTOVD + SCHD.INTOVDPRIN + SCHD.FEE + SCHD.FEEDUE + SCHD.FEEOVD + SCHD.FEEINTNMLACR + SCHD.FEEINTDUE + SCHD.FEEINTNMLOVD + SCHD.FEEINTOVDACR) < 1 THEN ''Y'' ELSE ''N'' END) SETTLED,
decode(SCHD.reftype,''P'',SCHD.RATE1,''GP'',MST.ORATE1,0) RATE1, decode(SCHD.reftype,''P'',SCHD.RATE2,''GP'',MST.ORATE2,0) RATE2,
decode(SCHD.reftype,''P'',SCHD.RATE3,''GP'',MST.ORATE3,0) RATE3,SCHD.CFRATE1,SCHD.CFRATE2,SCHD.CFRATE3,
ROUND(SCHD.FEEINTNMLACR) FEEINTNMLACR,ROUND(SCHD.FEEINTDUE) FEEINTDUE,ROUND(SCHD.FEEINTOVDACR) FEEINTOVDACR,ROUND(SCHD.FEEINTNMLOVD) FEEINTNMLOVD,ROUND(SCHD.FEEINTPAID) FEEINTPAID,
decode(mst.rrtype, ''B'', CFB.SHORTNAME, ''Company'') BANKNAME,
refullname,  schd.mintermdate, buf.BALANCE, buf.AVLADVANCE, tl.grpname
FROM LNSCHD SCHD, LNMAST MST, CFMAST CF, CIMAST CI, AFMAST AF, CFMAST CFB,
(SELECT VARVALUE BUSDATE FROM SYSVAR WHERE VARNAME=''CURRDATE'')SYS,
(select re.afacctno, MAX(cf.fullname) refullname
    from reaflnk re, sysvar sys, cfmast cf,RETYPE
    where to_date(varvalue,''DD/MM/RRRR'') between re.frdate and re.todate
    and substr(re.reacctno,0,10) = cf.custid
    and varname = ''CURRDATE'' and grname = ''SYSTEM''
    and re.status <> ''C'' and re.deltd <> ''Y''
    AND   substr(re.reacctno,11) = RETYPE.ACTYPE
    AND  rerole IN ( ''RM'',''BM'')
    GROUP BY AFACCTNO
) re,
(
    SELECT CI.AFACCTNO, SUM(CI.BALANCE) BALANCE, SUM(AVLADVANCE) AVLADVANCE
    FROM BUF_CI_ACCOUNT CI
    GROUP BY CI.AFACCTNO
) buf,
(SELECT * FROM TLGROUPS WHERE GRPTYPE = ''2'') TL
WHERE SCHD.ACCTNO = MST.ACCTNO AND SCHD.REFTYPE IN (''P'',''GP'')
AND MST.TRFACCTNO = AF.ACCTNO AND AF.CUSTID = CF.CUSTID and mst.custbank = cfb.custid(+)
AND AF.ACCTNO = CI.AFACCTNO
and af.acctno = re.afacctno(+)
AND af.acctno = buf.afacctno(+)
AND af.careby = tl.grpid(+)
AND AF.CAREBY IN (SELECT TLGRP.GRPID FROM TLGRPUSERS TLGRP WHERE TLID =''<$TELLERID>'')','LNMAST',null,null,null,null,50,'N',30,'NYNNYYYNNN','Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'LN0001';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (200,'LOCATION','Khu vực','C','LN0001',100,null,'=',null,'Y','Y','N',100,'SELECT CDVAL VALUE, CDCONTENT DISPLAY FROM ALLCODE WHERE CDTYPE = ''SA'' AND CDNAME = ''LOCATION'' ORDER BY LSTODR','Location','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (38,'MINTERMDATE','Ngày được trả nợ tự động','D','LN0001',10,null,'=,<,<=,>=,>','__/__/____','Y','Y','N',120,null,'Minterm date','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (37,'INTNMLACRBANK','Lãi Cty trả hộ','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','Y','N',120,null,'INTNMLACRBANK','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (36,'REFULLNAME','Cán bộ QLTK','C','LN0001',20,null,'LIKE,=',null,'Y','Y','N',120,null,'ReFullname','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (35,'SETTLED','Đã tất toán','C','LN0001',20,null,'=',null,'Y','Y','N',120,null,'Finally setteled','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (34,'FEEOVD','Phí đảo nợ quá hạn','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','N','N','N',120,null,'Overdue advance fee','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (33,'FEEDUE','Phí đảo nợ đến hạn','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','N','N','N',120,null,'Due advance fee','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (32,'FEE','Phí đảo nợ trong hạn','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','N','N','N',120,null,'Maturity advance fee','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (31,'FEEPAID','Phí đảo nợ đã trả','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Paid advance fee','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (30,'FEEAMT','Phí đảo nợ','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Advance fee amount','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (29,'FEEINTPAID','Phí d.vụ đã trả','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Paid interest','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (28,'FEEINTNMLOVD','Phí d.vụ quá hạn','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Interest on overdue principal','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (27,'FEEINTOVDACR','Phí và lãi quá hạn','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Overdue interest','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (26,'FEEINTDUE','Phí d.vụ đến hạn','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Due interest','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (25,'FEEINTNMLACR','Phí d.vụ trong hạn','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Maturity interest','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (24,'INTPAID','Lãi đã trả','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Paid interest','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (23,'INTOVDPRIN','Lãi trên gốc quá hạn','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Interest on overdue principal','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (22,'INTOVD','Lãi quá hạn','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Overdue interest','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (21,'INTDUE','Lãi đến hạn','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Due interest','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (20,'INTNMLACR','Lãi trong hạn','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Maturity interest','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (19,'PRINPAID','Gốc đã trả','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Paid principal','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (18,'PRINOVD','Gốc quá hạn','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Overdue principal','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (17,'PRINDUE','Gốc đến hạn','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Due principal','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (16,'PRINNML','Gốc trong hạn','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Normal principal','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (15,'CFRATE3','Mức phí quá hạn','N','LN0001',100,null,'<,<=,=,>=,>,<>','#,##0.0000','Y','Y','N',80,null,'Fee. rate 3','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (14,'CFRATE2','Mức phí trong hạn 2','N','LN0001',100,null,'<,<=,=,>=,>,<>','#,##0.0000','Y','Y','N',80,null,'Fee. rate 2','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (13,'CFRATE1','Mức phí trong hạn 1','N','LN0001',100,null,'<,<=,=,>=,>,<>','#,##0.0000','Y','Y','N',80,null,'Fee. rate 1','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (12,'RATE3','Mức lãi suất quá hạn','N','LN0001',100,null,'<,<=,=,>=,>,<>','#,##0.0000','Y','Y','N',80,null,'Int. rate 3','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (11,'RATE2','Mức lãi suất trong hạn 2','N','LN0001',100,null,'<,<=,=,>=,>,<>','#,##0.0000','Y','Y','N',80,null,'Int. rate 2','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (10,'RATE1','Mức lãi suất trong hạn 1','N','LN0001',100,null,'<,<=,=,>=,>,<>','#,##0.0000','Y','Y','N',80,null,'Int. rate 1','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'PRINPERIOD','Ngày ĐH kỳ hạn 2','D','LN0001',20,null,'=,<,<=,>=,>','__/__/____','Y','Y','N',100,null,'Term','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (8,'PRINFRQ','Ngày ĐH kỳ hạn 1','D','LN0001',20,null,'=,<,<=,>=,>','__/__/____','Y','N','N',100,null,'Principal payment day','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7.30,'AVLADVANCE','Số tiền có thể ứng','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','Y','N','N',120,null,'Avladvance','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7.10,'GRPNAME','Nhóm careby','C','LN0001',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Careby','Y',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'RLSDATE','Ngày giải ngân','D','LN0001',10,null,'=,<,<=,>=,>','__/__/____','Y','Y','N',120,null,'Released date','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (6,'LNACCTNO','Số tài khoản vay','C','LN0001',16,null,'LIKE,=','CCCC.CC.CCCC.CCCCCC','Y','Y','N',120,null,'Loan account','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'FULLNAME','Tên khách hàng','C','LN0001',150,null,'LIKE,=',null,'Y','Y','N',120,null,'Customer name','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'AFACCTNO','Số Tiểu khoản','C','LN0001',10,null,'LIKE,=','_','Y','Y','N',120,null,'Contract number','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'FTYPE_NAME','Món vay','C','LN0001',100,null,'LIKE,=','_','Y','Y','N',100,null,'FTYPE_NAME','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'CATEGORY','Loại vay','C','LN0001',100,null,'LIKE,=','_','N','N','N',100,null,'Category','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'BANKNAME','Ngân hàng','C','LN0001',10,'CCCC','LIKE,=','_','Y','Y','N',100,null,'Product type','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (0,'ACTYPE','Mã loại hình vay','C','LN0001',10,'CCCC','LIKE,=','_','Y','Y','N',100,null,'Product type','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (-1,'CUSTODYCD','Số lưu ký','C','LN0001',100,null,'=, LIKE',null,'Y','Y','N',80,null,'Custody code','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (-1,'AUTOID','Auto ID','N','LN0001',20,null,'=,<,<=,>=,>','#,##0','N','N','Y',120,null,'Auto ID','N',null,null,'N',null,null,null,'N');
COMMIT;
/
