--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'PRMASTER';
insert into search (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE)
values ('PRMASTER', 'Kiem soat Pool/Room', 'Pool/Room Master', 'SELECT MST.PRCODE, MST.PRNAME, A0.CDCONTENT PRTYPE, SB.SYMBOL,
A1.CDCONTENT PRSTATUS, LEAST( MST.PRLIMIT,SYSVAR.MAXDEBT) PRLIMITMAX,nvl(MST.PRLIMIT,0) PRLIMIT ,
        NVL(MST.PRINUSED,0) + NVL(prlog.prinused,0) PRINUSED, NVL(prlog.prinused,0) PRSECURED,
        LEAST( MST.PRLIMIT,SYSVAR.MAXDEBT) - NVL(MST.PRINUSED,0) - NVL(prlog.prinused,0) PRAVLLIMIT, MST.EXPIREDDT,
NVL(MST.PRINUSED,0) PRUSED,NVL(prlog.prinused,0) PRINDAY, MST.PRCODE CUSTODYCD
FROM PRMASTER MST,
(SELECT CODEID, SYMBOL FROM SBSECURITIES UNION ALL SELECT CCYCD CODEID, SHORTCD SYMBOL FROM SBCURRENCY) SB,
ALLCODE A0, ALLCODE A1,
(select prcode, sum(prinused) prinused from prinusedlog where deltd <> ''Y'' group by prcode) prlog,
(SELECT VARVALUE MAXDEBT FROM SYSVAR WHERE VARNAME  LIKE ''MAXDEBT'') SYSVAR
WHERE MST.CODEID=SB.CODEID(+) AND A0.CDTYPE=''SY''
    AND A0.CDNAME=''PRTYPE'' AND A0.CDVAL=MST.PRTYP
    AND A1.CDTYPE=''SY'' AND A1.CDNAME=''PRSTATUS'' AND A1.CDVAL=MST.PRSTATUS
    and mst.prcode = prlog.prcode(+)
UNION ALL
SELECT p.policycd PRCODE , ''FO ''|| p.policycd prname, '''' PRTYPE, '''' SYMBOL, '''' PRSTATUS, 0 prlimitmax,  p.granted prlimit,
nvl(p.inused,0) + nvl(inday.poolval,0)  prinused,  nvl(inday.poolval,0) prsecured, nvl(p.granted,0) -nvl(p.inused,0) -nvl(inday.poolval,0) pravllimit, trunc(sysdate) EXPIREDDT,
nvl(p.inused,0) PRUSED ,
nvl(inday.poolval,0) PRINDAY, nvl(ac.custodycd,p.policycd) CUSTODYCD
FROM poolroom@dbl_fo p ,
    (
    SELECT poolid, sum(decode(doc,''D'', poolval, -poolval)) poolval FROM allocation@dbl_fo
    WHERE  policycd =''P'' GROUP BY poolid ) inday, accounts@dbl_fo ac
WHERE p.policytype =''P''
AND p.policycd = inday.poolid(+)
and p.policycd = ac.acctno(+)', 'PRMASTER', 'PRCODE', null, null, null, 50, 'N', 30, null, 'Y', 'T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'PRMASTER';
insert into searchfld (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
values (13, 'CUSTODYCD', 'Số tài khoản', 'C', 'PRMASTER', 50, null, '=,LIKE', null, 'Y', 'Y', 'N', 100, null, 'Custodycd', 'N', null, null, 'N', null, null, null, 'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (12,'PRSTATUS','Trạng thái','C','PRMASTER',3,null,'=,LIKE',null,'N','Y','N',100,null,'Status','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (11,'EXPIREDDT','Hết hiệu lực','D','PRMASTER',10,'__/__/____','<,<=,=,>=,>,<>',null,'N','N','N',100,null,'Expired date','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (10,'PRSECURED','Dự tính đã dùng','N','PRMASTER',20,null,'<,<=,=,>=,>,<>','#,##0','N','N','N',150,null,'In secured','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'PRINUSED','Đã sử dụng','N','PRMASTER',20,null,'<,<=,=,>=,>,<>','#,##0','N','Y','N',150,null,'In used','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (8,'PRINDAY','Dự tính trong ngày','N','PRMASTER',20,null,'<,<=,=,>=,>,<>','#,##0','Y','N','N',150,null,'In day','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'PRUSED','Dư nợ đã giải ngân','N','PRMASTER',20,null,'<,<=,=,>=,>,<>','#,##0','Y','N','N',150,null,'used','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (6,'PRLIMIT','Hạn mức cấp','N','PRMASTER',20,null,'<,<=,=,>=,>,<>','#,##0','Y','N','N',150,null,'Limit','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'PRLIMITMAX','Hạn mức tối đa','N','PRMASTER',20,null,'<,<=,=,>=,>,<>','#,##0','Y','N','N',150,null,'Limit','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'PRAVLLIMIT','Hạn mức còn lại','N','PRMASTER',20,null,'<,<=,=,>=,>,<>','#,##0','Y','N','N',150,null,'Limit','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'SYMBOL','Mã','C','PRMASTER',10,null,'=,LIKE',null,'Y','Y','N',100,null,'Symbol','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'PRTYPE','Loại','C','PRMASTER',3,null,'=,LIKE',null,'Y','Y','N',100,null,'Type','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'PRNAME','Tên','C','PRMASTER',250,null,'=,LIKE','_','Y','Y','N',250,null,'Poom/Room Name','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (0,'PRCODE','Mã hiệu','C','PRMASTER',50,null,'=,LIKE','_','Y','Y','Y',100,null,'Poom/Room code','N',null,null,'N',null,null,null,'N');
COMMIT;
/
