--
--
/
DELETE search WHERE searchcode='CI1202';
INSERT INTO search (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE)
VALUES ('CI1202', 'Tra cứu từ chối giao dịch chuyển tiền giữa 2 tài khoản lưu ký', 'Look up money transfers between 2 depository accounts', 'SELECT RM.TXDATE,RM.TXNUM,TC.DCUSTODYCD,TC.DACCTNO,CFD.FULLNAME,CFD.IDCODE LICENSE,CFD.IDDATE,TC.CCUSTODYCD,TC.CACCTNO,
       CFC.FULLNAME CUSTNAME2,CFC.IDCODE LICENSE2,CFC.IDDATE IDDATE2,T1.TLNAME MAKER, T2.TLNAME OFFICER, RM.AMT, TC.DES,
       CR.ERRORDESC, RM.FEEAMT, CASE WHEN RM.RMSTATUS = ''C'' THEN RM.AMT ELSE 0 END REAMT
  FROM CIREMITTANCE  RM,TCDT2DEPOACC_LOG TC,CFMAST CFC,CFMAST CFD,TCDTBANKREQUEST  CR,
       (SELECT TLID, TLNAME FROM TLPROFILES UNION ALL SELECT ''____'' TLID, ''____'' TLNAME FROM DUAL) T1,
       (SELECT TLID, TLNAME FROM TLPROFILES UNION ALL SELECT ''____'' TLID, ''____'' TLNAME FROM DUAL) T2
 WHERE RM.ACCTNO = TC.DACCTNO
   AND TC.DCUSTODYCD = CFD.CUSTODYCD
   AND TC.CCUSTODYCD = CFC.CUSTODYCD
   AND RM.TXDATE = TC.TXDATE
   AND RM.TXNUM = TC.TXNUM
   AND RM.DELTD =''N''
   AND TC.TXDATE = CR.TXDATE (+)
   AND TC.TXNUM = CR.TXNUM (+)
   AND NVL(CR.STATUS,''P'') NOT IN (''W'',''C'')
   AND RM.RMSTATUS <> ''R''
   AND (CASE WHEN TC.TLID IS NULL THEN ''____'' ELSE TC.TLID END) = T1.TLID
   AND (CASE WHEN TC.OFFID IS NULL THEN ''____'' ELSE TC.OFFID END) = T2.TLID', 'CI.CIMAST', null, null, '1202', 0, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T');
COMMIT;
/

DELETE searchfld WHERE searchcode='CI1202';
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (0, 'TXDATE', 'Ngày chứng từ', 'D', 'CI1202', 100, '99/99/9999', 'LIKE,=', '_', 'Y', 'Y', 'N', 100, null, 'Voucher date', 'N', '06', null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (1, 'TXNUM', 'Số chứng từ', 'C', 'CI1202', 100, '9999999999', 'LIKE,=', '_', 'Y', 'Y', 'N', 100, null, 'Voucher number', 'N', '07', null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (2, 'DCUSTODYCD', 'Số tài khoản lưu ký chuyển', 'C', 'CI1202', 100, null, 'LIKE,=', '_', 'Y', 'Y', 'N', 100, null, 'Custody code', 'N', '88', null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (3, 'DACCTNO', 'Số Tiểu khoản chuyển', 'C', 'CI1202', 100, '9999.999999', 'LIKE,=', '_', 'Y', 'Y', 'N', 100, null, 'Contract number', 'N', '03', null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (4, 'FULLNAME', 'Tên khách hàng chuyển tiền', 'C', 'CI1202', 100, null, 'LIKE,=', '_', 'Y', 'Y', 'N', 100, null, 'Customer name', 'N', '31', null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (5, 'LICENSE', 'CMND/GPKD', 'C', 'CI1202', 100, null, 'LIKE,=', '_', 'Y', 'N', 'N', 100, null, 'ID Code', 'N', '92', null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (6, 'IDDATE', 'Ngày cấp', 'D', 'CI1202', 100, '99/99/9999', 'LIKE,=', '99/99/9999', 'Y', 'N', 'N', 100, null, 'Beneficary Date', 'N', '96', null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (7, 'CCUSTODYCD', 'Số tài khoản lưu ký nhận', 'C', 'CI1202', 100, null, 'LIKE,=', '_', 'Y', 'Y', 'N', 100, null, 'Custody code', 'N', '89', null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (8, 'CACCTNO', 'Số Tiểu khoản nhận', 'C', 'CI1202', 100, '9999.999999', 'LIKE,=', '_', 'Y', 'Y', 'N', 100, null, 'Contract number', 'N', '05', null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (9, 'CUSTNAME2', 'Tên khách hàng chuyển nhận', 'C', 'CI1202', 100, null, 'LIKE,=', '_', 'Y', 'Y', 'N', 100, null, 'Customer name', 'N', '93', null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (10, 'LICENSE2', 'CMND/GPKD', 'C', 'CI1202', 100, null, 'LIKE,=', '_', 'Y', 'N', 'N', 100, null, 'ID Code', 'N', '95', null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (11, 'IDDATE2', 'Ngày cấp', 'D', 'CI1202', 100, '99/99/9999', 'LIKE,=', '99/99/9999', 'Y', 'N', 'N', 100, null, 'Beneficary Date', 'N', '98', null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (12, 'AMT', 'Số tiền chuyển', 'N', 'CI1202', 100, null, '<,<=,=,>=,>,<>', '#,##0', 'Y', 'Y', 'N', 100, null, 'Transfer amount', 'N', '10', null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (13, 'FEEAMT', 'Phí chuyển tiền', 'N', 'CI1202', 100, null, '<,<=,=,>=,>,<>', '#,##0', 'Y', 'Y', 'N', 100, null, 'Fee amount', 'N', '11', null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (14, 'REAMT', 'Số tiền chuyển', 'N', 'CI1202', 100, null, '<,<=,=,>=,>,<>', '#,##0', 'N', 'N', 'N', 100, null, 'Transfer amount', 'N', '12', null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (15, 'DES', 'Diễn giải', 'C', 'CI1202', 100, null, 'LIKE,=', '_', 'Y', 'N', 'N', 100, null, 'Desc', 'N', null, null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (16, 'MAKER', 'Người nhận', 'C', 'CI1202', 100, null, 'LIKE,=', '_', 'Y', 'Y', 'N', 100, null, 'Maker', 'N', null, null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (17, 'OFFICER', 'Người duyệt', 'C', 'CI1202', 100, null, 'LIKE,=', '_', 'Y', 'Y', 'N', 100, null, 'Officer', 'N', null, null, 'N', null, null, null, 'N');
INSERT INTO  SEARCHFLD (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY)
VALUES  (18, 'ERRORDESC', 'Mã lỗi', 'C', 'CI1202', 100, null, 'LIKE,=', '_', 'Y', 'Y', 'N', 100, null, 'Error', 'N', null, null, 'N', null, null, null, 'N');
COMMIT;
