--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'OD9979';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('OD9979','Order Exception Summary','Order Exception Summary','SELECT ''COM'' COMORSTC, MST.AFACCTNO, OOD.ORGORDERID, OOD.TXDATE, OOD.TXNUM, TO_CHAR(OOD.SYMBOL) SYMBOL,
       OOD.CUSTODYCD, CD1.CDCONTENT BORS, CD2.CDCONTENT NORP, OOD.QTTY,
       OOD.PRICE, TO_CHAR(CD3.CDCONTENT) TRADEPLACE, MST.PRICETYPE PRICETYPE
  FROM OOD, ALLCODE CD1, ALLCODE CD2, ODMAST MST, SBSECURITIES SB,
       ALLCODE CD3
 WHERE CD1.CDTYPE = ''OD''
   AND CD1.CDNAME = ''BORS''
   AND CD1.CDVAL = OOD.BORS
   AND MST.ORDERID = OOD.ORGORDERID
   AND SB.CODEID = OOD.CODEID
   AND SB.TRADEPLACE = ''001''
   AND OOD.BORS IN (''B'', ''S'')
   AND CD2.CDTYPE = ''OD''
   AND CD2.CDNAME = ''NORP''
   AND CD2.CDVAL = OOD.NORP
   AND CD3.CDTYPE = ''OD''
   AND CD3.CDNAME = ''TRADEPLACE''
   AND CD3.CDVAL = SB.TRADEPLACE
   AND OODSTATUS = ''S''
   AND ORGORDERID NOT IN (SELECT ORDERID
                            FROM STCORDERBOOK)
UNION ALL
SELECT ''STC'' COMORSTC, AF.ACCTNO, '''' ORGORDERID, TRUNC(SYSDATE) TXDATE, '''' TXNUM,
       STC.SYMBOL SYMBOL,STC.CUSTODYCD, CD1.CDCONTENT BORS, CD2.CDCONTENT NORP, STC.VOLUME QTTY,
       STC.PRICE PRICE, '''' TRADEPLACE, STC.ORDERTYPE PRICETYPE
  FROM STCORDERBOOKEXP STC, CFMAST CF, AFMAST AF, ALLCODE CD1, ALLCODE CD2
 WHERE CF.CUSTODYCD = STC.CUSTODYCD
   AND CF.CUSTID = AF.CUSTID
   AND CD1.CDTYPE = ''OD''
   AND CD1.CDNAME = ''BORS''
   AND CD1.CDVAL = STC.BSCA
   AND CD2.CDTYPE = ''OD''
   AND CD2.CDNAME = ''NORP''
   AND CD2.CDVAL = STC.NORP','ODMAST',null,null,null,null,50,'N',30,'NYNNYYYNNN','Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'OD9979';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (15,'ORGORDERID','Số hiệu lệnh','C','OD9979',150,null,'LIKE,=',null,'Y','Y','Y',110,null,'ORDER ID','N','01',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (14,'NORP','Thường / Thỏa thuận','C','OD9979',100,null,'=','_','Y','Y','N',100,'SELECT CDVAL VALUE, CDCONTENT DISPLAY FROM ALLCODE WHERE CDTYPE = ''OD'' AND CDNAME = ''BORS'' ORDER BY LSTODR','NORMAL/PUTTHROUGH','N','30',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (12,'TRADEPLACE','Nơi giao dịch','C','OD9979',100,null,'LIKE,=',null,'Y','Y','N',80,'SELECT CDVAL VALUE, CDCONTENT DISPLAY FROM ALLCODE WHERE CDTYPE = ''OD'' AND CDNAME = ''TRADEPLACE'' AND CDVAL <>''000'' ORDER BY LSTODR','TRADEPLACE','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (11,'TXNUM','Sở giao dịch','C','OD9979',100,'CCCCDCCCCCC','LIKE,=',null,'Y','Y','N',80,null,'TX.NUM','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (10,'TXDATE','Ngày giao dịch','D','OD9979',100,null,'=',null,'Y','Y','N',80,null,'TX.DATE','N','  ',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'PRICE','Giá','N','OD9979',100,null,'<,<=,=,>=,>,<>','#,##0','Y','Y','N',80,null,'PRICE','N','30',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (8,'QTTY','Khối lượng','N','OD9979',100,null,'<,<=,=,>=,>,<>','#,##0','Y','Y','N',80,null,'QUANTITY','N','30',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'SYMBOL','Chứng khoán','C','OD9979',110,null,'LIKE,=','_','Y','Y','N',80,null,'Symbol','N','  ',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'BORS','Mua / Bán','C','OD9979',100,null,'=','_','Y','Y','N',80,'SELECT CDVAL VALUE, CDCONTENT DISPLAY FROM ALLCODE WHERE CDTYPE = ''OD'' AND CDNAME = ''BORS'' ORDER BY LSTODR','BUY/SELL','N','30',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'CUSTODYCD','Mã lưu ký','C','OD9979',110,'ccc.c.cccccc','LIKE,=','_','Y','Y','N',80,null,'CUSTODY CODE','N','  ',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'AFACCTNO','Số tài khoản','C','OD9979',110,null,'LIKE,=','_','Y','Y','N',80,null,'CONTRACT NUMBER','N','  ',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'PRICETYPE','Loại lệnh','C','OD9979',100,null,'=','_','Y','Y','N',100,null,'TYPE','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (0,'COMORSTC','Company/STC','C','OD9979',100,null,'=','_','Y','Y','N',80,'SELECT ''COM'' VALUE, ''COM'' DISPLAY FROM DUAL UNION ALL SELECT ''STC'' VALUE, ''STC'' DISPLAY FROM DUAL','ComOrStc','N','30',null,'N',null,null,null,'N');
COMMIT;
/
