--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'CF0097';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('CF0097','Quản lý hạn mức User cấp cho Tiểu khoản','General view of allocated to account','SELECT USF.custodycd, USF.acctno ,USF.tliduser, USF.acclimit, usf.custid , usf.fullname, USF.ACCTNOGROUP,
        usf.TLNAME, USF.TYPERECEIVE, a1.cdcontent status
FROM
(
    Select  cf.custodycd ,  USF.acctno ,USF.tliduser, USF.acclimit, AF.custid , CF.fullname, USF.acctno ACCTNOGROUP,
        TL.TLNAME, USF.TYPERECEIVE, CASE WHEN ol.status = ''E'' THEN ''Y'' ELSE ''N'' END status
    from Useraflimit USF , AFmast AF,CFmast CF, TLprofiles TL, (SELECT DISTINCT acctno, userid, status FROM olndetail WHERE status = ''E'')  ol
    where AF.acctno =USF.acctno  and AF.custid =CF.custid and USF.TLIDUSER = TL.TLID
        AND usf.tliduser = ol.userid(+) AND usf.acctno = ol.acctno(+)
) usf, allcode a1
WHERE usf.status = a1.cdval AND a1.cdname = ''YESNO'' AND a1.cdtype = ''SY''','USERLIMIT','frmSATLID','TLIDUSER',null,null,50,'N',30,'NYNNYYYNNN','Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'CF0097';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (100,'STATUS','Trạng thái vi phạm','C','CF0097',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Status','Y','06',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'FULLNAME','Tên khách hàng','C','CF0097',100,null,'<,<=,=,>=,>','#,##0','Y','Y','N',100,null,'FULLNAME','N','10',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (6,'ACCLIMIT','GT được cấp','N','CF0097',100,null,'LIKE,=','#,##0','Y','Y','N',100,null,'ACCLIMIT','N','10',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'TYPERECEIVE','HM/BL','C','CF0097',200,null,'LIKE,=',null,'Y','Y','N',80,null,'typereceive','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'ACCTNO','Số TK','C','CF0097',100,null,'=,Like','_','Y','Y','Y',60,null,'ACCTNO','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'CUSTODYCD','Số TK lưu ký','C','CF0097',10,null,'LIKE,=','_','Y','Y','N',100,null,'Custody code','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'TLNAME','Tên User','C','CF0097',200,null,'LIKE,=',null,'Y','Y','N',80,null,'TLNAME','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'TLIDUSER','Mã User','C','CF0097',10,null,'LIKE,=',null,'Y','Y','N',80,null,'USERID','N',null,null,'N',null,null,null,'N');
COMMIT;
/
