--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'CFOL02';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('CFOL02','Danh sách khách hàng được giới thiệu từ online','Management online register','Select A.*, CASE WHEN CFN.STATUS = ''A'' AND NVL
(AFN.STATUS, ''-'') =
    ''A'' THEN CFN.CUSTODYCD ElSE '''' END CUSTODYCDNEW
FROM  (Select cfi.id, cf.custodycd, cf.fullname, nvl
(cf.mobile,
    cf.phone) mobile,
        cfi.fullname introname, A2.cdcontent sex,
cfi.mobile
    INTROMOBILE,
    cfi.idcodeintro,
        cfi.introdate, A1.cdcontent STATUS, A1.cdval
    STATUS1, cfi.Description
    From cfintro cfi, cfmast cf, allcode A1, allcode A2
    where cfi.custidintro = cf.custid
        AND A1.cdval = cfi.status AND A1.CDNAME =
    ''CFINTROSTATUS''
        AND A2.cdval = cfi.Sex AND A2.CDNAME = ''SEX'') A,
    CFMAST CFN, (SELECT CUSTID, MAX(STATUS) STATUS FROM AFMAST WHERE LENGTH(PSTATUS) > 1 GROUP BY CUSTID) AFN
WHERE A.IDCODEINTRO = CFN.IDCODE(+)
    AND CFN.CUSTID = AFN.CUSTID(+)','CFOL02',null,null,'0021',null,50,'N',30,'NYNNYYYNNN','Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'CFOL02';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (12,'DESCRIPTION','Ghi chú','C','CFOL02',500,null,'LIKE,=',null,'Y','Y','N',500,null,'NOTES','N','30',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (11,'CUSTODYCDNEW','Số lưu ký KH mới','C','CFOL02',100,null,'LIKE,=',null,'Y','Y','N',100,null,'CUSTODYCDNEW','N','30',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (10,'STATUS1','Trạng thái','C','CFOL02',100,null,'LIKE,=',null,'N','N','N',100,'SELECT  CDVAL VALUECD, CDVAL VALUE, CDCONTENT DISPLAY
FROM ALLCODE WHERE CDTYPE = ''CF''
AND CDNAME = ''CFINTROSTATUS'' ORDER BY LSTODR','STATUS','N','40',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'STATUS','Trạng thái','C','CFOL02',100,null,'LIKE,=',null,'Y','Y','N',100,'SELECT  CDVAL VALUECD, CDVAL VALUE, CDCONTENT DISPLAY
FROM ALLCODE WHERE CDTYPE = ''CF''
AND CDNAME = ''CFINTROSTATUS'' ORDER BY LSTODR','STATUS','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (8,'INTRODATE','Ngày giới thiệu','D','CFOL02',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Intro Date','N','19',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'IDCODEINTRO','CMND KH được giới thiệu','C','CFOL02',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Intro IDCode','N','06',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (6,'INTROMOBILE','Sđt KH được giới thiệu','C','CFOL02',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Intro Mobile','N','98',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'SEX','Giới tính','C','CFOL02',100,null,'LIKE,=',null,'Y','Y','N',100,'SELECT  CDVAL VALUECD, CDVAL VALUE, CDCONTENT DISPLAY
FROM ALLCODE WHERE CDTYPE = ''CF''
AND CDNAME = ''SEX'' ORDER BY LSTODR','Sex','N','97',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'INTRONAME','Tên KH được giới thiệu','C','CFOL02',300,null,'LIKE,=',null,'Y','Y','N',300,null,'Full Name','N','99',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'MOBILE','Sđt người giới thiệu','C','CFOL02',100,null,'LIKE,=',null,'Y','Y','N',100,null,'Intro mobile','N','22',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'FULLNAME','Tên người giới thiệu','C','CFOL02',300,null,'LIKE,=',null,'Y','Y','N',300,null,'Intro Name','N','90',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'ID','ID','C','CFOL02',100,null,'LIKE,=',null,'N','Y','Y',100,null,'ID','N','01',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'CUSTODYCD','Số lưu ký giới thiệu','C','CFOL02',100,null,'LIKE,=',null,'Y','Y','N',100,null,'CUSTODYCD','N','88',null,'N',null,null,null,'N');
COMMIT;
/
