--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'OD8812';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('OD8812','View trading allocation(wait for 8812)','View trading allocation(wait for 8812)','SELECT OD.ORDERID,OD.CODEID,SEC.SYMBOL,B.CUSTODYCD,OD.AFACCTNO,OD.SEACCTNO,OD.CIACCTNO,B.BSCA BORS,B.NORP,OD.NORK AORN,
OD.QUOTEPRICE EXPRICE, OD.ORDERQTTY EXQTTY, A.VOLUME QTTY,A.PRICE PRICE,A.ORDERNUMBER REFORDERID, A.REFCONFIRMNUMBER CONFIRM_NO,
OD.BRATIO,OD.CLEARDAY,OD.CLEARCD, B.CUSTODYCD || ''.'' || B.BSCA || ''.'' || SEC.SYMBOL || ''.'' || A.VOLUME || ''.'' || A.PRICE  DESCRIPTION,
CASE B.BSCA = ''B'' THEN A.PRICE*A.VOLUME ELSE 0 END DCRAMT, CASE B.BSCA = ''B'' THEN A.VOLUME ELSE 0 END DCRQTTY
FROM ODMAST OD,SBSECURITIES SEC,STCTRADEBOOK A,STCORDERBOOK B WHERE OD.ORDERID=B.ORDERID AND  A.ORDERNUMBER=B.ORDERNUMBER AND OD.CODEID=SEC.CODEID AND SEC.TRADEPLACE=''001''
MINUS
SELECT OD.ORDERID,OD.CODEID,SEC.SYMBOL,B.CUSTODYCD,OD.AFACCTNO,OD.SEACCTNO,OD.CIACCTNO,B.BSCA BORS,B.NORP,OD.NORK AORN,
OD.QUOTEPRICE EXPRICE, OD.ORDERQTTY EXQTTY, A.VOLUME QTTY,A.PRICE PRICE,A.ORDERNUMBER REFORDERID, A.REFCONFIRMNUMBER CONFIRM_NO,
OD.BRATIO,OD.CLEARDAY,OD.CLEARCD , B.CUSTODYCD || ''.'' || B.BSCA || ''.'' || SEC.SYMBOL || ''.'' || A.VOLUME || ''.'' || A.PRICE  DESCRIPTION
FROM ODMAST OD,SBSECURITIES SEC, STCTRADEBOOK A,STCORDERBOOK B,STCTRADEALLOCATION C  WHERE OD.ORDERID=B.ORDERID AND  A.ORDERNUMBER=B.ORDERNUMBER
AND A.REFCONFIRMNUMBER=C.REFCONFIRMNUMBER AND OD.CODEID=SEC.CODEID AND C.DELTD<>''Y'' AND SEC.TRADEPLACE=''001''','ODMAST',null,null,'8812',50,50,'N',30,'NYNNYYYNNN','Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'OD8812';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (21,'DESCRIPTION','Diễn giải','C','OD8812',100,'CCCC','LIKE,=','_','Y','Y','N',200,null,'Description','N','30',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (20,'SEACCTNO','Số tài khoản SE','C','OD8812',100,'9999.999999.999999','LIKE,=','_','N','N','N',100,null,'SE account number','N','06',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (19,'CONFIRM_NO','Số xác nhận','C','OD8812',100,null,'LIKE,=','_','Y','Y','N',100,null,'CONFIRM_NO','N','16',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (18,'BRATIO','Tỷ lệ ký quỹ','N','OD8812',100,null,'<,<=,=,>=,>,<>',null,'Y','Y','N',100,null,'Secured ratio','N','15',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (17,'CLEARDAY','Số ngày thanh toán','C','OD8812',100,null,'LIKE,=','_','Y','Y','N',100,null,'Clearing day','N','14',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (16,'CLEARCD','Loại lịch thanh toán','C','OD8812',100,null,'LIKE,=','_','Y','Y','N',100,null,'Clearing calendar','N','09',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (14,'REFORDERID','Số hiệu lệnh tham chiếu','C','OD8812',100,null,'LIKE,=','_','Y','Y','Y',100,null,'Reference order ID','N','07',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (13,'QTTY','Khối lượng khớp','N','OD8812',100,null,'<,<=,=,>=,>,<>',null,'Y','Y','N',100,null,'Matching quantity','N','11',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (12,'PRICE','Giá khớp','N','OD8812',100,null,'<,<=,=,>=,>,<>',null,'Y','Y','N',100,null,'Matching price','N','10',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (11,'EXQTTY','Place quantity','N','OD8812',100,null,'<,<=,=,>=,>,<>',null,'Y','Y','N',100,null,'Place quantity','N','13',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (10,'EXPRICE','Place price','N','OD8812',100,null,'<,<=,=,>=,>,<>',null,'Y','Y','N',100,null,'Place price','N','12',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (9,'CIACCTNO','Số tài khoản CI','C','OD8812',100,'9999.999999','LIKE,=','_','N','N','N',100,null,'CI account number','N','05',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (8,'AFACCTNO','Số Tiểu khoản','C','OD8812',100,null,'LIKE,=','_','Y','Y','N',100,null,'Contract number','N','04',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (7,'AORN','All or None','C','OD8812',100,null,'LIKE,=','_','Y','Y','N',100,null,'All or None','N','85',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (6,'NORP','Lệnh thường / Lệnh thỏa thuận','C','OD8812',100,null,'LIKE,=','_','Y','Y','N',100,null,'Normal or putthought','N','84',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'BORS','Mua / Bán','C','OD8812',100,null,'LIKE,=','_','Y','Y','N',100,null,'Buy or Sell','N','83',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'CUSTODYCD','Số tài khoản lưu ký','C','OD8812',100,'ccc.c.cccccc','LIKE,=','_','Y','Y','N',100,null,'Custody code','N','82',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'SYMBOL','Chứng khoán','C','OD8812',100,null,'LIKE,=','_','Y','Y','N',100,null,'Symbol','N','81',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'CODEID','Chứng khoán','C','OD8812',100,null,'LIKE,=','_','N','N','N',100,null,'Symbol','N','80',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'ORDERID','Số hiệu lệnh gốc','C','OD8812',100,'9999.999999.999999','LIKE,=','_','Y','Y','Y',100,null,'Order ID','N','03',null,'N',null,null,null,'N');
COMMIT;
/
