--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'ICCFTYPESCHDMAPVIEW';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('ICCFTYPESCHDMAPVIEW','Gán lịch biểu lãi tiền gửi với loại hình tiền gửi','Gán lịch biểu lãi tiền gửi với loại hình tiền gửi','SELECT TYP.AUTOID, IC.ACTYPE, IC.ACNAME,TYP.ACTYPE CITYPE, CI.TYPENAME, IC.EFFECTIVEDT
FROM ICCFTYPESCHDMAP TYP, CITYPE CI, ICCFTYPESCHD IC
WHERE TYP.actype=CI.actype AND CI.ACTYPE=''<$KEYVAL>'' AND TYP.REFID= IC.AUTOID
ORDER BY TYP.AUTOID','SA.ICCFTYPESCHDMAP','frmICCFTYPESCHDMAP',null,null,null,50,'N',30,null,'Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'ICCFTYPESCHDMAPVIEW';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'EFFECTIVEDT','Ngày hiệu lực','D','ICCFTYPESCHDMAPVIEW',100,null,'<,<=,=,>=,>,<>','DD/MM/YYYY','Y','Y','N',150,null,'Efective date','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'TYPENAME','Tên loại hình','C','ICCFTYPESCHDMAPVIEW',100,null,'LIKE,=',null,'Y','Y','N',200,null,'Product name','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'CITYPE','Loại hình','C','ICCFTYPESCHDMAPVIEW',50,null,'LIKE,=',null,'Y','Y','N',100,null,'Product code','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'ACNAME','Tên biểu','C','ICCFTYPESCHDMAPVIEW',100,null,'LIKE,=',null,'Y','Y','N',200,null,'Product name','Y',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'ACTYPE','Mã biểu','C','ICCFTYPESCHDMAPVIEW',50,null,'LIKE,=',null,'Y','Y','N',100,null,'Product code','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (0,'AUTOID','Mã quản lý','N','ICCFTYPESCHDMAPVIEW',20,null,'=,<>,<,<=,>=,>','#,##0','N','Y','Y',100,null,'Auto ID','N',null,null,'N',null,null,null,'N');
COMMIT;
/
