--
--
/
DELETE SEARCH WHERE SEARCHCODE = 'SE2277';
INSERT INTO SEARCH (SEARCHCODE,SEARCHTITLE,EN_SEARCHTITLE,SEARCHCMDSQL,OBJNAME,FRMNAME,ORDERBYCMDSQL,TLTXCD,CNTRECORD,ROWPERPAGE,AUTOSEARCH,INTERVAL,AUTHCODE,ROWLIMIT,CMDTYPE)
VALUES ('SE2277','Tra cứu chứng khoán chờ giao dịch','Waiting for trade','
SELECT SB.CODEID ,SB.SYMBOL,iss.ISSUERID , ISS.FULLNAME,SEINFO.BASICPRICE PRICE ,al.cdcontent tradeplace , SB.PARVALUE FROM SBSECURITIES SB , SECURITIES_INFO SEINFO, ISSUERS ISS ,
allcode al WHERE SB.CODEID = SEINFO.CODEID AND SB.ISSUERID = ISS.ISSUERID and tradeplace in(''001'',''002'') AND SECTYPE<>''004''
and sb.tradeplace = al.cdval and al.cdtype=''OD'' AND CDNAME=''TRADEPLACE'' AND  REFCODEID IS NULL AND
SB.CODEID NOT IN ( SELECT REFCODEID FROM SBSECURITIES WHERE REFCODEID IS NOT NULL )','SBSECURITIES',null,null,'2277',null,50,'N',30,'NYNNYYYNNN','Y','T');
COMMIT;
/
--
--
/
DELETE SEARCHFLD WHERE SEARCHCODE = 'SE2277';
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'TRADEPLACE','Nơi giao dịch','C','SE2277',100,null,'LIKE,=','_','Y','Y','N',200,null,'TradePlace','N',null,null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (5,'PRICE','Giá','C','SE2277',100,null,'LIKE,=','_','Y','Y','N',200,null,'Price','N','09',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (4,'PARVALUE','Mệnh giá','N','SE2277',100,null,'<,<=,=,>=,>,<>',null,'Y','N','N',150,null,'Parvalue','N','11',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'FULLNAME','Tên','C','SE2277',100,null,'LIKE,=','_','Y','Y','N',200,null,'Full name','Y','05',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (3,'ISSUERID','Mã tổ chức phát hành','C','SE2277',100,'cccccc','LIKE,=','_','Y','N','N',100,null,'ISSUERID','N','04',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (2,'CODEID','Mã chứng khoán','C','SE2277',100,'cccccc','LIKE,=','_','Y','N','N',100,null,'Symbol','N','03',null,'N',null,null,null,'N');
INSERT INTO SEARCHFLD (POSITION,FIELDCODE,FIELDNAME,FIELDTYPE,SEARCHCODE,FIELDSIZE,MASK,OPERATOR,FORMAT,DISPLAY,SRCH,KEY,WIDTH,LOOKUPCMDSQL,EN_FIELDNAME,REFVALUE,FLDCD,DEFVALUE,MULTILANG,ACDTYPE,ACDNAME,FIELDCMP,FIELDCMPKEY)
VALUES (1,'SYMBOL','Chứng khoán','C','SE2277',100,'ccccccccccccccc','LIKE,=','_','Y','Y','N',150,null,'Symbol','N',null,null,'N',null,null,null,'N');
COMMIT;
/
