--
--
/
DELETE HFT_REMAP_FIELD WHERE BPS_FUNCTION = 'BD_GET_ACCOUNT_INFO';
INSERT INTO HFT_REMAP_FIELD (BPS_MODULE,BPS_FUNCTION,ACTION,FO_FIELD,BPS_FIELD,BPS_FIELD_TYPE,BPS_DEFAULT_VALUE)
VALUES (null,'BD_GET_ACCOUNT_INFO','RENAME','PP0','PP',null,null);
INSERT INTO HFT_REMAP_FIELD (BPS_MODULE,BPS_FUNCTION,ACTION,FO_FIELD,BPS_FIELD,BPS_FIELD_TYPE,BPS_DEFAULT_VALUE)
VALUES (null,'BD_GET_ACCOUNT_INFO','ADD',null,'AUTOADV','VARCHAR','N');
INSERT INTO HFT_REMAP_FIELD (BPS_MODULE,BPS_FUNCTION,ACTION,FO_FIELD,BPS_FIELD,BPS_FIELD_TYPE,BPS_DEFAULT_VALUE)
VALUES (null,'BD_GET_ACCOUNT_INFO','RENAME','EXECBUYAMT','TOTALORDERAMOUNT',null,null);
INSERT INTO HFT_REMAP_FIELD (BPS_MODULE,BPS_FUNCTION,ACTION,FO_FIELD,BPS_FIELD,BPS_FIELD_TYPE,BPS_DEFAULT_VALUE)
VALUES (null,'BD_GET_ACCOUNT_INFO','RENAME','DEBT','OUTSTANDING',null,null);
COMMIT;
/
