--
--
/
DELETE FILEMASTER WHERE FILECODE = 'I048';
INSERT INTO FILEMASTER (EORI,FILECODE,FILENAME,FILEPATH,TABLENAME,SHEETNAME,ROWTITLE,DELTD,EXTENTION,PAGE,PROCNAME,PROCFILLTER,OVRRQD,MODCODE,RPTID,CMDCODE)
VALUES ('T','I048','Import thay đổi chi nhánh cho khách hàng',null,'TBLCFCHGBRID','1',1,'N','.xls',100,null,'PR_FILE_TBLCFCHGBRID','Y','CF',null,'CF');
COMMIT;
/
