--
--
/
DELETE FILEMASTER WHERE FILECODE = 'C038';
INSERT INTO FILEMASTER (EORI,FILECODE,FILENAME,FILEPATH,TABLENAME,SHEETNAME,ROWTITLE,DELTD,EXTENTION,PAGE,PROCNAME,PROCFILLTER,OVRRQD,MODCODE,RPTID,CMDCODE)
VALUES ('D','C038','SMS_TOKENCV',null,'SMS_TOKENCV','1',1,'N','.xls',100,null,null,'N',null,'N',null);
COMMIT;
/
