--
--
/
DELETE FILEMASTER WHERE FILECODE = 'I025';
INSERT INTO FILEMASTER (EORI,FILECODE,FILENAME,FILEPATH,TABLENAME,SHEETNAME,ROWTITLE,DELTD,EXTENTION,PAGE,PROCNAME,PROCFILLTER,OVRRQD,MODCODE,RPTID,CMDCODE)
VALUES ('I','I025','DS nguồn Room Margin',null,'SECURITIES_INFO_IMPORT','1',1,'N','.xls',100,'PR_ROOM_MARGIN_APPROVE',null,'N',null,null,null);
COMMIT;
/
