--
--
/
DELETE FILEMASTER WHERE FILECODE = 'I040';
INSERT INTO FILEMASTER (EORI,FILECODE,FILENAME,FILEPATH,TABLENAME,SHEETNAME,ROWTITLE,DELTD,EXTENTION,PAGE,PROCNAME,PROCFILLTER,OVRRQD,MODCODE,RPTID,CMDCODE)
VALUES ('I','I040','Import file SL giao dịch TB ngày',null,'SECURITIES_INFO_IMPORT','1',1,'N','.xls',100,'T0_AVRTRADEQTTY_APPROVE','T0_AVRTRADEQTTY_MAKE','Y',null,null,null);
COMMIT;
/
