--
--
/
DELETE FILEMASTER WHERE FILECODE = 'I050';
INSERT INTO FILEMASTER (EORI,FILECODE,FILENAME,FILEPATH,TABLENAME,SHEETNAME,ROWTITLE,DELTD,EXTENTION,PAGE,PROCNAME,PROCFILLTER,OVRRQD,MODCODE,RPTID,CMDCODE)
VALUES ('I','I050','Thiết lập giá chặn vay Margin',null,'SECURITIES_INFO_IMPORT','1',1,'N','.xls',100,'PR_PRICE_MARGIN_APPROVE',null,'N',null,null,null);
COMMIT;
/
