--
--
/
DELETE FILEMASTER WHERE FILECODE = 'I006';
INSERT INTO FILEMASTER (EORI,FILECODE,FILENAME,FILEPATH,TABLENAME,SHEETNAME,ROWTITLE,DELTD,EXTENTION,PAGE,PROCNAME,PROCFILLTER,OVRRQD,MODCODE,RPTID,CMDCODE)
VALUES ('I','I006','DS số dư tiền không lưu ký tại công ty',null,'OTHERCIACCTNO_TEMP','1',1,'N','.xls',100,'CAL_OTHERCIACCTNO_ACTION','FILLTER_OTHERCIACCTNO_ACTION','Y',null,null,null);
COMMIT;
/
